using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Rask.Generators;

public sealed partial class RoutesGenerator
{
    /// <summary>
    ///     Emits the project's ONE <c>Routes</c> class, in its root namespace. A page whose type name is
    ///     unique is a flat <c>Routes.{Page}(...)</c>; pages sharing a type name nest under the namespace
    ///     segments that follow the group's common prefix (<c>Routes.Admin.HomePage()</c>).
    /// </summary>
    private static void EmitRoutesClass(SourceProductionContext spc, List<Candidate> routed,
        Dictionary<string, Candidate> byFqn, bool supportsExtensionMembers, string rootNamespace)
    {
        var root = new RoutesNode("Routes");
        foreach (var group in routed.GroupBy(c => c.TypeName, StringComparer.Ordinal))
        {
            var pages = group.OrderBy(c => c.FullyQualifiedName, StringComparer.Ordinal).ToList();
            if (pages.Count == 1)
            {
                root.Pages.Add(pages[0]);
                continue;
            }

            var segments = pages.Select(c => SplitNamespace(c.Namespace)).ToList();
            var common = CommonPrefixLength(segments);
            for (var i = 0; i < pages.Count; i++)
            {
                var node = root;
                foreach (var segment in segments[i].Skip(common))
                {
                    node = node.Child(segment);
                }

                // Two pages with one namespace and one type name are nested types of different classes;
                // the first keeps the helper, as it always has.
                if (node.Pages.All(p => !string.Equals(p.TypeName, pages[i].TypeName, StringComparison.Ordinal)))
                {
                    node.Pages.Add(pages[i]);
                }
            }
        }

        var routesFqn = string.IsNullOrEmpty(rootNamespace) ? "global::Routes" : $"global::{rootNamespace}.Routes";
        RejectCollisions(spc, root, routesFqn);

        var body = new StringBuilder();
        var extensions = new SortedDictionary<string, StringBuilder>(StringComparer.Ordinal);
        EmitRoutesNode(spc, body, root, routesFqn, byFqn, supportsExtensionMembers ? extensions : null, isRoot: true);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        // The route helpers carry a <summary> and no <param>, which is warning-clean on its own — but
        // the pragma keeps it that way if a <param> is ever added here, since CS1573 then fires for
        // every parameter left undocumented and would break every consumer's build, not ours.
        sb.AppendLine("#pragma warning disable CS1573 // parameter has no matching param tag");
        sb.AppendLine();
        AppendInNamespace(sb, rootNamespace, body.ToString());

        // The per-page Url()/Go() blocks live in each PAGE's namespace, so the import that brings the page
        // into scope brings its helpers too; they forward to the fully qualified Routes method.
        foreach (var entry in extensions)
        {
            sb.AppendLine();
            AppendInNamespace(sb, entry.Key, entry.Value.ToString());
        }

        spc.AddSource("Routes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitRoutesNode(SourceProductionContext spc, StringBuilder sb, RoutesNode node,
        string fqn, Dictionary<string, Candidate> byFqn, SortedDictionary<string, StringBuilder>? extensions,
        bool isRoot)
    {
        if (isRoot)
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine("///     Type-safe URLs for this assembly's <c>[Route]</c> pages — one method per page, taking that");
            sb.AppendLine("///     page's route parameters. Build links with these rather than with path strings.");
            sb.AppendLine("/// </summary>");
        }
        else
        {
            sb.Append("/// <summary>The URLs of the <c>").Append(EscapeXml(node.Name))
                .AppendLine("</c> pages whose type name another page shares.</summary>");
        }

        sb.Append("public static partial class ").AppendLine(node.Name);
        sb.AppendLine("{");

        var members = new StringBuilder();
        foreach (var c in node.Pages.OrderBy(c => c.TypeName, StringComparer.Ordinal))
        {
            StringBuilder? ext = null;
            if (extensions is not null)
            {
                if (!extensions.TryGetValue(c.Namespace, out ext))
                {
                    ext = new StringBuilder();
                    extensions[c.Namespace] = ext;
                }
                else
                {
                    ext.AppendLine();
                }
            }

            EmitRouteFactory(spc, members, ext, c, byFqn, $"{fqn}.{c.TypeName}");
            members.AppendLine();
        }

        foreach (var child in node.Children.Values)
        {
            var nested = new StringBuilder();
            EmitRoutesNode(spc, nested, child, $"{fqn}.{child.Name}", byFqn, extensions, isRoot: false);
            AppendIndented(members, nested.ToString(), "    ");
            members.AppendLine();
        }

        sb.Append(members);
        sb.AppendLine("}");
    }

    private static string[] SplitNamespace(string ns) =>
        string.IsNullOrEmpty(ns) ? [] : ns.Split('.');

    private static int CommonPrefixLength(List<string[]> segments)
    {
        var length = segments.Min(s => s.Length);
        for (var i = 0; i < length; i++)
        {
            var segment = segments[0][i];
            if (segments.Any(s => !string.Equals(s[i], segment, StringComparison.Ordinal)))
            {
                return i;
            }
        }

        return length;
    }

    private static void AppendInNamespace(StringBuilder sb, string ns, string body)
    {
        if (string.IsNullOrEmpty(ns))
        {
            sb.Append(body);
            return;
        }

        sb.Append("namespace ").AppendLine(ns);
        sb.AppendLine("{");
        AppendIndented(sb, body, "    ");
        sb.AppendLine("}");
    }

    private static void AppendIndented(StringBuilder sb, string text, string indent)
    {
        foreach (var line in text.Replace("\r\n", "\n").TrimEnd('\n').Split('\n'))
        {
            if (line.Length > 0)
            {
                sb.Append(indent);
            }

            sb.AppendLine(line);
        }
    }

    // A project's assembly name can carry characters a namespace cannot (My-App); MSBuild's own default
    // RootNamespace maps them to '_', and the fallback does the same.
    private static string SanitizeNamespace(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return string.Empty;
        }

        var segments = name.Split('.').Select(segment =>
        {
            var chars = segment.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_').ToArray();
            var id = new string(chars);
            return id.Length == 0 || char.IsDigit(id[0]) ? "_" + id : id;
        });
        return string.Join(".", segments);
    }

    private sealed class RoutesNode(string name)
    {
        public string Name { get; } =
            SyntaxFacts.GetKeywordKind(name.TrimStart('@')) != SyntaxKind.None ? "@" + name.TrimStart('@') : name;

        public List<Candidate> Pages { get; } = [];

        public SortedDictionary<string, RoutesNode> Children { get; } = new(StringComparer.Ordinal);

        public RoutesNode Child(string segment)
        {
            if (!Children.TryGetValue(segment, out var child))
            {
                child = new RoutesNode(segment);
                Children[segment] = child;
            }

            return child;
        }

        public IEnumerable<Candidate> AllPages() =>
            Pages.Concat(Children.Values.SelectMany(c => c.AllPages()));
    }
}
