namespace Rask.Generators;

public sealed partial class RoutesGenerator
{
    // The half of `@rask/routes` that is the same in every project: the route value, `Go`, and the formatters
    // that write a value into a URL exactly as RouteValueFormatter does. It rides in front of the generated
    // `Routes` table so the module is one self-contained file — nothing to vendor, nothing to resolve.
    //
    // The helpers live on two objects rather than as loose functions: this file is compiled inside the app's
    // own TypeScript program, and a project with `noUnusedLocals` would otherwise fail on a formatter its
    // routes happen not to need.
    private const string TypeScriptRuntime = """
        // <auto-generated/>
        // Generated from this project's [Route] pages. Do not edit: the next build overwrites it, and the
        // C# `Routes` class is the source of truth for every page, parameter name and type in here.

        declare const generated: unique symbol

        /** A page's URL. Only `Routes.*` makes one, so a path typed by hand never navigates. */
        export interface Route {
          readonly [generated]: true
          /** The address, under the app's path base: what an `href` takes. */
          readonly Url: string
          /** Spread onto an `<a>` for an in-app link: `<a {...Routes.HomePage().Link}>Home</a>`. */
          readonly Link: { href: string; 'data-rask-nav': '' }
          /** Navigates here. `.Go().Replacing()` replaces the history entry instead of pushing one. */
          Go(): GoTo
        }

        /** What `Go()` hands back. */
        export interface GoTo {
          /** Replaces the current history entry, so the navigation adds no Back-button stop. */
          Replacing(): void
        }

        type Host = { navigate?: (url: string, replace?: boolean) => void }
        type Format<T> = (value: T) => string
        type Query = [key: string, values: string[]][]

        // Uri.EscapeDataString: everything but A-Z a-z 0-9 - . _ ~ is percent-encoded, which is
        // encodeURIComponent plus the five characters it lets through.
        const escape = (value: string) =>
          encodeURIComponent(value).replace(/[!'()*]/g, c => '%' + c.charCodeAt(0).toString(16).toUpperCase())
        const two = (value: number) => String(value).padStart(2, '0')
        const clock = (value: Date) =>
          `${two(value.getMonth() + 1)}/${two(value.getDate())}/${String(value.getFullYear()).padStart(4, '0')} ` +
          `${two(value.getHours())}:${two(value.getMinutes())}:${two(value.getSeconds())}`

        // One formatter per C# type, each writing what RouteValueFormatter.Format writes for it.
        const format = {
          text: escape,
          number: (value: number) => escape(String(value)),
          boolean: (value: boolean) => (value ? 'true' : 'false'),
          // DateOnly and TimeOnly arrive in their wire form (2026-10-06, 13:05:09) and leave in .NET's invariant one.
          date: (value: string) => escape(value.replace(/^(\d+)-(\d+)-(\d+)$/, '$2/$3/$1')),
          time: (value: string) => escape(value.slice(0, 5)),
          stamp: (value: Date) => escape(clock(value)),
          offset(value: Date) {
            const minutes = -value.getTimezoneOffset()
            const size = Math.abs(minutes)
            return escape(`${clock(value)} ${minutes < 0 ? '-' : '+'}${two(Math.floor(size / 60))}:${two(size % 60)}`)
          },
        }

        const url = {
          /** A required path segment. */
          segment: <T>(value: T | null | undefined, write: Format<T>) => (value == null ? '' : write(value)),
          /** An optional path segment: left out, slash and all, when there is no value. */
          optional: <T>(value: T | null | undefined, write: Format<T>) => (value == null ? '' : '/' + write(value)),
          /** A query parameter that is left out when there is no value. */
          given: <T>(key: string, value: T | null | undefined, write: Format<T>) =>
            value == null ? null : `${key}=${write(value)}`,
          /** A query parameter the page always carries, empty when there is no value. */
          always: <T>(key: string, value: T | null | undefined, write: Format<T>) =>
            `${key}=${value == null ? '' : write(value)}`,
        }

        // The app's path base, as the hosts read it: the directory of <base href>, or none.
        function base(): string {
          const element = document.querySelector<HTMLBaseElement>('base[href]')
          if (!element) return ''
          const path = new URL(element.href, location.href).pathname
          return path.slice(0, path.lastIndexOf('/'))
        }

        // After the caller's own code has finished, the way C# navigates after the handler returns —
        // which is what leaves `.Replacing()` time to be heard.
        function go(target: string, called: string): GoTo {
          let replace = false
          queueMicrotask(() => {
            const host = (globalThis as { __raskHost?: Host }).__raskHost
            if (typeof host?.navigate !== 'function') {
              console.error(`Rask islands: ${called} asked for "${target}" before the Rask runtime was ready, so nothing navigated.`)
              return
            }
            host.navigate(target, replace)
          })
          return { Replacing: () => { replace = true } }
        }

        function route(path: string, ...query: (string | null)[]): Route {
          const pairs = query.filter(pair => pair !== null)
          const target = base() + (path || '/') + (pairs.length ? '?' + pairs.join('&') : '')
          return { Url: target, Link: { href: target, 'data-rask-nav': '' }, Go: () => go(target, 'Go()') } as Route
        }

        // The current query, read the way the C# side reads it: keys match without regard to case, and a
        // repeated key keeps every value.
        function currentQuery(): Query {
          const decode = (part: string) => {
            try { return decodeURIComponent(part.replace(/\+/g, ' ')) } catch { return part }
          }
          const query: Query = []
          for (const pair of location.search.replace(/^\?/, '').split('&')) {
            if (!pair) continue
            const split = pair.indexOf('=')
            const key = decode(split < 0 ? pair : pair.slice(0, split))
            const value = split < 0 ? '' : decode(pair.slice(split + 1))
            const known = query.find(entry => same(entry[0], key))
            if (known) known[1].push(value)
            else query.push([key, [value]])
          }
          return query
        }

        const same = (left: string, right: string) => left.toUpperCase() === right.toUpperCase()

        // This page with its query changed: the path stays, and the change is a new history entry.
        function requery(query: Query, called: string): void {
          const pairs = query.flatMap(([key, values]) => values.map(value => `${escape(key)}=${escape(value)}`))
          go(location.pathname + (pairs.length ? '?' + pairs.join('&') : ''), called)
        }

        /** Where the user goes next. There is no path overload: a destination is always a `Routes.*` value. */
        export const Go = {
          /** Goes to a route: `Go.To(Routes.UserPage({ Id: 42 }))`, the same as `Routes.UserPage({ Id: 42 }).Go()`. */
          To: (route: Route): GoTo => route.Go(),
          /** Stays on this page with `key` set in its query; a `null` value removes it. */
          With(key: string, value: string | null): void {
            const query = currentQuery()
            const known = query.find(entry => same(entry[0], key))
            if (value === null) return requery(query.filter(entry => entry !== known), 'Go.With')
            if (known) known[1] = [value]
            else query.push([key, [value]])
            requery(query, 'Go.With')
          },
          /** Stays on this page without `key` in its query, or with no query at all. */
          Without(key?: string): void {
            requery(key === undefined ? [] : currentQuery().filter(entry => !same(entry[0], key)), 'Go.Without')
          },
        }

        """;
}
