using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Rask.Generators;

public sealed partial class RoutesGenerator
{
    private static void EmitRegistryInitializer(SourceProductionContext spc, IReadOnlyList<Candidate> candidates)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("internal static class __RaskRoutesRegistry");
        sb.AppendLine("{");
        AppendDynamicDependencies(sb, candidates);

        // Init() only bootstraps; RefreshAll() holds the whole body so the hot-reload coordinator
        // can re-invoke it after a metadata update ([ModuleInitializer] never runs twice). It must
        // stay idempotent and replace-semantics — see RaskHotReload.RefreshTargetTypeNames, which
        // lists this class by name.
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Init() => RefreshAll();");
        sb.AppendLine();
        sb.AppendLine("    internal static void RefreshAll()");
        sb.AppendLine("    {");
        // Replace, not Add: Add appends, and every assembly with routed pages calls this. Keying
        // the set on this class lets a refresh swap just this assembly's routes — picking up
        // added, edited and deleted [Route] templates — without duplicating them or dropping
        // another assembly's contribution.
        sb.AppendLine(
            "        global::Rask.Core.Routing.RouteRegistry.Replace(typeof(__RaskRoutesRegistry), new global::Rask.Core.Routing.RouteRegistration[]");
        sb.AppendLine("        {");
        AppendRegistrations(sb, candidates);

        sb.AppendLine("        });");

        AppendParsableRegistrations(sb, candidates);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("__RaskRoutesRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void AppendDynamicDependencies(StringBuilder sb, IReadOnlyList<Candidate> candidates)
    {
        // Per-page [DynamicDependency] tells the trimmer to keep public ctors and properties on
        // every routed page type. Pages are instantiated via ActivatorUtilities.CreateInstance
        // (needs ctors) and bound via reflection over [RouteParam]/[QueryParam] properties
        // (needs property accessors). Custom attributes on the type — [Route], [Authorize],
        // [AllowAnonymous] — are preserved by the trimmer whenever the type metadata is kept,
        // so the auth guard and template resolver work transparently.
        foreach (var c in candidates.OrderBy(x => x.FullyQualifiedName, StringComparer.Ordinal))
        {
            sb.Append("    [global::System.Diagnostics.CodeAnalysis.DynamicDependency(")
                .Append(
                    "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors | " +
                    "global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicProperties")
                .Append(", typeof(")
                .Append(c.FullyQualifiedName)
                .AppendLine("))]");
        }
    }

    private static void AppendRegistrations(StringBuilder sb, IReadOnlyList<Candidate> candidates)
    {
        foreach (var c in candidates.OrderBy(x => x.FullyQualifiedName, StringComparer.Ordinal))
        {
            // One RouteRegistration per [Route] attribute. RouteRegistry.BuildTree groups
            // by parent — duplicates of the same PageType under the same parent surface as
            // distinct Route nodes the router can match independently.
            foreach (var template in c.Templates)
            {
                sb.Append("            new(typeof(")
                    .Append(c.FullyQualifiedName)
                    .Append("), \"")
                    .Append(EscapeForCSharpStringLiteral(template))
                    .Append("\", ");
                if (c.ParentTypeFqn is null)
                {
                    sb.Append("null");
                }
                else
                {
                    sb.Append("typeof(").Append(c.ParentTypeFqn).Append(')');
                }

                sb.AppendLine("),");
            }
        }
    }

    private static void AppendParsableRegistrations(StringBuilder sb, IReadOnlyList<Candidate> candidates)
    {
        // Register every non-primitive IParsable<T> route/query param type with the reflection-free
        // parser registry so a full-AOT publish (no MakeGenericMethod) can still bind it. Compiler
        // primitives are always seeded by the framework, so they are skipped; deduped by FQN.
        var aotRegisteredTypes = candidates
            .SelectMany(c => c.Properties)
            .Where(p => (p.HasRouteParam || p.HasQueryParam) && p.NeedsAotRegistration)
            .Select(p => p.UnderlyingTypeFqn)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(fqn => fqn, StringComparer.Ordinal)
            .ToList();

        foreach (var fqn in aotRegisteredTypes)
        {
            sb.Append("        global::Rask.Core.Forms.RaskBinding.RegisterParsable<")
                .Append(fqn)
                .AppendLine(">();");
        }
    }
}
