using Rask.External.Generated;

namespace Rask.External.Tests;

// The typed boundary, which is the whole differentiator: every islands implementation can embed
// React, but this is the one where renaming a C# property stops the front end compiling.
//
// Asserted against the constants the generator actually emitted into THIS compilation, rather than
// against generator output captured as text. If the generator stopped emitting them, or emitted
// something that is not valid TypeScript for the declared props, these stop compiling or stop
// passing — there is no arrangement where they keep passing while the guarantee is gone.
public class GeneratedPropTypesTests
{
    [Fact]
    public void A_props_interface_is_named_after_the_component()
    {
        Assert.Contains("export interface ChartProps {", RaskExternalGeneratedTypeScript.Chart,
            StringComparison.Ordinal);
    }

    [Fact]
    public void A_required_prop_is_required_and_a_nullable_one_admits_null()
    {
        var ts = RaskExternalGeneratedTypeScript.Chart;

        // `required IReadOnlyList<Point> Series` — no `?`, because the chain cannot produce the
        // component without it.
        Assert.Contains("series: Point[];", ts, StringComparison.Ordinal);

        // `string? Heading` — nullable, but still PRESENT. The writer emits the key with a JSON null,
        // because "never set" and "set to nothing" are different facts, and `heading?: string` would
        // describe the wrong one.
        Assert.Contains("heading: string | null;", ts, StringComparison.Ordinal);
    }

    [Fact]
    public void A_record_prop_brings_its_own_interface_with_it()
    {
        // Point is declared in the same file that references it, so the .tsx needs one import rather
        // than a second one that has to be kept in step by hand.
        var ts = RaskExternalGeneratedTypeScript.Chart;

        Assert.Contains("export interface Point {", ts, StringComparison.Ordinal);
        Assert.Contains("label: string;", ts, StringComparison.Ordinal);
        Assert.Contains("value: number;", ts, StringComparison.Ordinal);
    }

    [Fact]
    public void A_callback_is_an_optional_function_returning_void()
    {
        // Optional because an unwired callback omits its key entirely, so the front end sees
        // `undefined` and React's optional-prop handling does the right thing.
        Assert.Contains("onPointClick?: (value: number) => void;", RaskExternalGeneratedTypeScript.Chart,
            StringComparison.Ordinal);

        // Action, with no argument at all.
        Assert.Contains("onTick?: () => void;", RaskExternalGeneratedTypeScript.Ticker,
            StringComparison.Ordinal);
    }

    [Fact]
    public void An_async_callback_is_still_void_on_the_front_end()
    {
        // Func<T, Task> is void here, and deliberately: the callback crosses as a handler reference
        // and the client hands back a plain function that ships the payload. There is no promise on
        // this side to await, so typing one would describe a value that does not exist.
        Assert.DoesNotContain("Promise", RaskExternalGeneratedTypeScript.Chart, StringComparison.Ordinal);
    }

    [Fact]
    public void A_route_parameter_is_an_ordinary_typed_prop()
    {
        // The nice consequence of a routed component being an ordinary component: /reports/41 reaches
        // the front end as a typed `id`, with nothing written to carry it there.
        Assert.Contains("id: number;", RaskExternalGeneratedTypeScript.Report, StringComparison.Ordinal);
    }

    [Fact]
    public void A_component_with_no_props_still_gets_an_interface()
    {
        // So the .tsx can import the same name whatever the component declares, and adding the first
        // prop is not also a change of import.
        Assert.Contains("export interface PanelProps {", RaskExternalGeneratedTypeScript.Panel,
            StringComparison.Ordinal);
    }

    [Fact]
    public void The_file_says_it_is_generated_and_where_the_truth_lives()
    {
        // These land where a developer will open them. The first line is the only thing standing
        // between someone and an edit the next build silently discards.
        Assert.StartsWith("// <auto-generated/>", RaskExternalGeneratedTypeScript.Gauge,
            StringComparison.Ordinal);
        Assert.Contains("the C# is the source of truth", RaskExternalGeneratedTypeScript.Gauge,
            StringComparison.Ordinal);
    }
}

/// <summary>
///     A propless island. It used to live in the slot tests; it stays because the "no props still gets
///     an interface" claim needs a component that genuinely declares none.
/// </summary>
public sealed partial class Panel : ReactComponent;
