using System.Text.Json;
using Rask.TestSupport;

namespace Rask.External.Tests;

#pragma warning disable RASK014 // the dispatch tests hand the very instance they render to the context

// A package island is rendered for real here: the class beside MuiButton.props.json, generated by the same
// two generators an app runs, set through the chain. This file compiling is itself the first assertion —
// every step used below exists only because the snapshot described it.
public partial class PackageIslandRenderTests : global::Rask.Core.RaskMarkup
{
    [Fact]
    public void An_enum_prop_is_sent_as_the_package_literal()
    {
        using var props = IslandHtml.Props(MuiButton.Variant(MuiButtonVariant.Contained).Size(MuiButtonSize.Small));

        Assert.Equal("contained", props.RootElement.GetProperty("variant").GetString());
        Assert.Equal("small", props.RootElement.GetProperty("size").GetString());
    }

    [Fact]
    public void An_unset_prop_is_omitted_so_the_package_keeps_its_own_default()
    {
        using var props = IslandHtml.Props(MuiButton.Disabled(false));

        Assert.False(props.RootElement.TryGetProperty("variant", out _));
        Assert.False(props.RootElement.TryGetProperty("elevation", out _));

        // `false` is a value the author set, not an absence — it has to arrive.
        Assert.False(props.RootElement.GetProperty("disabled").GetBoolean());
    }

    [Fact]
    public void A_prop_no_csharp_name_can_spell_keeps_the_package_spelling()
    {
        using var props = IslandHtml.Props(MuiButton.AriaLabel("Save"));

        Assert.Equal("Save", props.RootElement.GetProperty("aria-label").GetString());
    }

    [Fact]
    public void A_number_prop_takes_an_int_at_the_call_site()
    {
        using var props = IslandHtml.Props(MuiButton.Elevation(2));

        Assert.Equal(2d, props.RootElement.GetProperty("elevation").GetDouble());
    }

    [Fact]
    public void A_date_travels_tagged_so_the_client_revives_exactly_it()
    {
        using var props = IslandHtml.Props(MuiButton.StartedAt(new DateTimeOffset(2026, 9, 11, 8, 0, 0, TimeSpan.Zero)));

        var started = props.RootElement.GetProperty("startedAt");
        Assert.Equal(JsonValueKind.Object, started.ValueKind);
        Assert.Equal(
            new DateTimeOffset(2026, 9, 11, 8, 0, 0, TimeSpan.Zero),
            started.GetProperty("$d").GetDateTimeOffset());
    }

    [Fact]
    public void A_nested_object_omits_its_unset_members()
    {
        using var props = IslandHtml.Props(MuiButton.Classes(new MuiButtonButtonClasses { Root = "r" }));

        var classes = props.RootElement.GetProperty("classes");
        Assert.Equal("r", classes.GetProperty("root").GetString());
        Assert.False(classes.TryGetProperty("label", out _));
    }

    [Fact]
    public void Every_callback_says_which_arguments_cross_so_an_event_never_does()
    {
        using var props = IslandHtml.Props(MuiButton.OnClick(() => { }).OnChange(_ => { }));

        var onClick = props.RootElement.GetProperty("onClick");
        Assert.False(string.IsNullOrEmpty(onClick.GetProperty("$h").GetString()));
        Assert.Equal(0, onClick.GetProperty("$a").GetArrayLength());

        // onChange(event, value): the event stays in the browser, the number crosses.
        var forwarded = props.RootElement.GetProperty("onChange").GetProperty("$a");
        Assert.Equal(1, Assert.Single(forwarded.EnumerateArray()).GetInt32());
    }

    [Fact]
    public async Task A_forwarded_number_reaches_the_callback_as_a_double()
    {
        double? received = null;
        var root = new StubComponent(() => Div[MuiButton.OnChange(value => { received = value; })]);

        var id = HandlerId(IslandHtml.RenderLive(root), "onChange");

        Assert.True(await root.TryInvokeHandlerAsync(id, Frame("[3.5]")));
        Assert.Equal(3.5, received);
    }

    [Fact]
    public async Task An_argument_of_the_wrong_kind_is_not_delivered()
    {
        // A snapshot that no longer matches the package could send a string where a number was declared.
        // Handing the callback a default it never received would be worse than not calling it.
        var calls = 0;
        var root = new StubComponent(() => Div[MuiButton.OnChange(_ => { calls++; })]);

        var id = HandlerId(IslandHtml.RenderLive(root), "onChange");
        await root.TryInvokeHandlerAsync(id, Frame("[\"not a number\"]"));

        Assert.Equal(0, calls);
    }

    private static JsonElement Frame(string args) =>
        JsonDocument.Parse($$"""{"args":{{args}}}""").RootElement;

    private static string HandlerId(string html, string prop)
    {
        using var props = JsonDocument.Parse(IslandHtml.ReadProps(html));
        return props.RootElement.GetProperty(prop).GetProperty("$h").GetString()!;
    }
}
