<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rask.Core\Rask.Core.csproj"/>
    <ProjectReference Include="..\..\src\Rask.Html\Rask.Html.csproj"/>
    <ProjectReference Include="..\..\src\Rask.Server\Rask.Server.csproj"/>
    <ProjectReference Include="..\..\src\Rask.Generators\Rask.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

  <Target Name="EnsureEmptyWwwroot" BeforeTargets="BeforeBuild">
    <MakeDir Directories="wwwroot"/>
  </Target>

</Project>
