#!/usr/bin/env node
// Writes src/Rask.Ui/UiChartInter.Metrics.cs: Inter's advance widths and kerning pairs, in font units.
//
// Flux sizes a chart's gutters by measuring its tick labels in the browser. Ui.Chart is drawn in C#, where
// there is no browser to ask, so it carries the numbers the browser would answer with: every glyph's advance
// and every kerning pair of the face Flux's docs (and a Tailwind app's default `font-sans` stack with Inter
// loaded) are set in. Measured at 2048px, where a font unit is a pixel, on a page that has Inter loaded;
// a label's width at 12px is then ceil(units * 12 / 2048 * 64) / 64, which is what Chromium reports.
//
// Usage:  node scripts/flux/inter-metrics.mjs        (rarely: when Inter itself changes)

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { chromium, root } from './lib.mjs';

const CHARS = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).concat([...'€£¥°…–—’·×']);
const WEIGHTS = [400, 500];

const browser = await chromium().launch();
const page = await browser.newPage();
await page.goto('https://fluxui.dev/components/chart', { waitUntil: 'networkidle', timeout: 90000 });
await page.evaluate(() => document.fonts.ready);
const measured = await page.evaluate(({ CHARS, WEIGHTS }) => {
  const text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
  text.style.whiteSpace = 'pre';
  text.style.fontSize = '2048px';
  document.querySelector('ui-chart svg').appendChild(text);
  const width = s => { text.textContent = s; return text.getComputedTextLength(); };
  const out = {};
  for (const weight of WEIGHTS) {
    text.style.fontWeight = weight;
    // A lone space has no length of its own: it is measured between two letters, and so is a pair with one.
    const x = width('x');
    const single = CHARS.map(c => Math.round(c === ' ' ? width('x x') - 2 * x : width(c)));
    const pairs = [];
    CHARS.forEach((a, i) => CHARS.forEach((b, j) => {
      const kern = a === ' ' && b === ' ' ? 0
        : a === ' ' ? width('x' + a + b) - width('x ') - single[j]
        : b === ' ' ? width(a + b + 'x') - single[i] - width(' x')
        : width(a + b) - single[i] - single[j];
      if (Math.abs(kern) > 0.4) pairs.push((i << 17) | (j << 10) | (Math.round(kern) + 512));
    }));
    out[weight] = { single, pairs };
  }
  text.remove();
  return out;
}, { CHARS, WEIGHTS });
await browser.close();

const rows = (values, per) => {
  const lines = [];
  for (let i = 0; i < values.length; i += per) lines.push('        ' + values.slice(i, i + per).join(', ') + ',');
  return lines.join('\n');
};
const source = `// <auto-generated>scripts/flux/inter-metrics.mjs — do not edit by hand.</auto-generated>
namespace Rask;

internal static partial class UiChartInter
{
    // The glyphs measured, in the order of every table below.
    private const string Glyphs = "${CHARS.map(c => (c === '"' || c === '\\' ? '\\' + c : c)).join('')}";
${WEIGHTS.map(weight => `
    // Advance width of each glyph at weight ${weight}, in font units (2048 to the em).
    private static readonly short[] Advance${weight} =
    [
${rows(measured[weight].single, 20)}
    ];

    // Kerning pairs at weight ${weight}: (left << 17) | (right << 10) | (units + 512).
    private static readonly int[] Kerning${weight} =
    [
${rows(measured[weight].pairs, 12)}
    ];`).join('\n')}
}
`;
await writeFile(join(root, 'src', 'Rask.Ui', 'UiChartInter.Metrics.cs'), source);
console.log(`inter metrics: ${WEIGHTS.map(w => `${w}: ${measured[w].pairs.length} pairs`).join(', ')}`);
