using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Rask.Generators.Shared;

namespace Rask.Api.Generators;

/// <summary>
///     Writes the generated client source: one class per controller, plus the module initializer that
///     registers them.
/// </summary>
internal static class ClientEmitter
{
    public static string Emit(IReadOnlyList<ApiEndpoint> endpoints)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable disable");
        builder.AppendLine();

        var groups = endpoints
            .GroupBy(e => e.ClientNamespace + "|" + e.ClientName, StringComparer.Ordinal)
            .OrderBy(g => g.Key, StringComparer.Ordinal)
            .ToList();

        foreach (var group in groups)
        {
            EmitClient(builder, group.First().ClientNamespace, group.First().ClientName, [.. group]);
        }

        EmitRegistry(builder, groups.Select(g => (g.First().ClientNamespace, g.First().ClientName)).ToList());

        return builder.ToString();
    }

    private static void EmitClient(
        StringBuilder builder,
        string clientNamespace,
        string clientName,
        IReadOnlyList<ApiEndpoint> endpoints)
    {
        // One emitter per client, so a shape used by two methods of the same client is written once and
        // two clients never collide on a codec method name.
        var codecs = new WireCodecEmitter();
        var bodies = new StringBuilder();

        foreach (var endpoint in endpoints)
        {
            EmitMethod(bodies, codecs, endpoint);
        }

        builder.AppendLine($"namespace {clientNamespace}");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Calls this app's API. Generated from the endpoint declarations.</summary>");
        builder.AppendLine($"    public sealed class {clientName}");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::System.Net.Http.HttpClient _http;");
        builder.AppendLine("        private readonly global::Rask.Api.Client.ApiClientOptions _options;");
        builder.AppendLine();
        builder.AppendLine(
            $"        public {clientName}(global::System.Net.Http.HttpClient http, "
            + "global::Rask.Api.Client.ApiClientOptions options)");
        builder.AppendLine("        {");
        builder.AppendLine("            _http = http;");
        builder.AppendLine("            _options = options;");
        builder.AppendLine("        }");
        builder.Append(bodies);
        builder.AppendLine();

        // Results never carry files; the codec signatures take the list regardless, so one empty
        // instance is shared rather than allocated per call.
        builder.AppendLine(
            "        private static readonly global::System.Collections.Generic.List<global::Rask.Wire.RemoteFile> "
            + "__NoFiles = new global::System.Collections.Generic.List<global::Rask.Wire.RemoteFile>();");
        builder.AppendLine();
        builder.Append(Indent(codecs.Methods, "        "));
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private static void EmitMethod(StringBuilder builder, WireCodecEmitter codecs, ApiEndpoint endpoint)
    {
        var returns = endpoint.ResultFqn is null
            ? "global::System.Threading.Tasks.Task"
            : $"global::System.Threading.Tasks.Task<{endpoint.ResultFqn}>";

        var signature = new List<string>();

        // Optional parameters must come last in C# whatever order the action declared them in.
        foreach (var parameter in endpoint.Parameters.Where(p => !p.Optional))
        {
            signature.Add($"{parameter.Fqn} {parameter.Name}");
        }

        foreach (var parameter in endpoint.Parameters.Where(p => p.Optional))
        {
            signature.Add($"{parameter.Fqn} {parameter.Name} = {parameter.Default}");
        }

        signature.Add("global::System.Threading.CancellationToken cancellationToken = default");

        builder.AppendLine();
        builder.AppendLine(
            $"        /// <summary>Calls <c>{endpoint.Method} {endpoint.Route}</c> ({endpoint.DeclaredBy}).</summary>");
        builder.AppendLine(
            $"        public async {returns} {endpoint.MethodName}({string.Join(", ", signature)})");
        builder.AppendLine("        {");

        EmitPath(builder, endpoint);
        EmitBody(builder, codecs, endpoint);

        var body = endpoint.Parameters.Any(p => p.Binding == ApiBinding.Body) ? "__body" : "null";

        builder.AppendLine(
            "            var __bytes = await global::Rask.Api.Client.ApiCall.SendAsync(_http, _options, "
            + $"global::System.Net.Http.HttpMethod.{HttpMethodMember(endpoint.Method)}, __path, {body}, "
            + "cancellationToken).ConfigureAwait(false);");

        EmitHeaders(builder, endpoint);

        if (endpoint.ResultFqn is null || endpoint.ResultType is null)
        {
            builder.AppendLine("            _ = __bytes;");
        }
        else
        {
            var reader = codecs.Ensure(endpoint.ResultType);

            builder.AppendLine("            if (__bytes == null)");
            builder.AppendLine("            {");
            builder.AppendLine("                return default;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            var __reader = new global::System.Text.Json.Utf8JsonReader(__bytes);");
            builder.AppendLine("            __reader.Read();");
            builder.AppendLine(
                $"            return R{reader}(ref __reader, __NoFiles, \"$\");");
        }

        builder.AppendLine("        }");
    }

    private static void EmitPath(StringBuilder builder, ApiEndpoint endpoint)
    {
        var route = RouteTemplate.Bareize(endpoint.Route);
        var path = new StringBuilder();
        var literal = new StringBuilder();
        var parts = new List<string>();

        for (var i = 0; i < route.Length; i++)
        {
            if (route[i] != '{')
            {
                literal.Append(route[i]);
                continue;
            }

            var close = route.IndexOf('}', i);
            var token = route.Substring(i + 1, close - i - 1);
            i = close;

            var parameter = endpoint.Parameters.FirstOrDefault(p =>
                p.Binding == ApiBinding.Route &&
                string.Equals(p.WireName, token, StringComparison.OrdinalIgnoreCase));

            if (literal.Length > 0)
            {
                parts.Add(Quote(literal.ToString()));
                literal.Clear();
            }

            parts.Add($"global::Rask.Api.Client.ApiUri.Segment({parameter!.Name})");
        }

        if (literal.Length > 0)
        {
            parts.Add(Quote(literal.ToString()));
        }

        if (parts.Count == 0)
        {
            parts.Add(Quote("/"));
        }

        path.Append(string.Join(" + ", parts));

        var query = endpoint.Parameters.Where(p => p.Binding == ApiBinding.Query).ToList();

        if (query.Count > 0)
        {
            var pairs = query.Select(p => $"({Quote(p.WireName)}, (object){p.Name})");
            path.Append(" + global::Rask.Api.Client.ApiUri.Query(")
                .Append(string.Join(", ", pairs))
                .Append(')');
        }

        builder.AppendLine($"            var __path = {path};");
    }

    private static void EmitBody(StringBuilder builder, WireCodecEmitter codecs, ApiEndpoint endpoint)
    {
        var body = endpoint.Parameters.FirstOrDefault(p => p.Binding == ApiBinding.Body);

        if (body is null)
        {
            return;
        }

        var writer = codecs.Ensure(body.Type);

        builder.AppendLine("            byte[] __body;");
        builder.AppendLine("            {");
        builder.AppendLine(
            "                var __buffer = new global::System.Buffers.ArrayBufferWriter<byte>();");
        builder.AppendLine(
            "                using (var __writer = new global::System.Text.Json.Utf8JsonWriter(__buffer))");
        builder.AppendLine("                {");
        builder.AppendLine(
            $"                    W{writer}(__writer, {body.Name}, __NoFiles);");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                __body = __buffer.WrittenSpan.ToArray();");
        builder.AppendLine("            }");
    }

    private static void EmitHeaders(StringBuilder builder, ApiEndpoint endpoint)
    {
        // Header parameters are not yet routed through ApiCall's request builder; an endpoint declaring
        // one is refused before it reaches here, so this is only a guard against that changing silently.
        if (endpoint.Parameters.Any(p => p.Binding == ApiBinding.Header))
        {
            throw new InvalidOperationException("Header-bound parameters are not emitted.");
        }
    }

    private static void EmitRegistry(StringBuilder builder, IReadOnlyList<(string Namespace, string Name)> clients)
    {
        builder.AppendLine("namespace Rask.Api.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class __RaskApiClients");
        builder.AppendLine("    {");
        builder.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("        internal static void Initialize()");
        builder.AppendLine("        {");
        builder.AppendLine(
            "            global::Rask.Api.Client.ApiClientRegistry.Replace(typeof(__RaskApiClients), "
            + "new global::Rask.Api.Client.ApiClientRegistration[]");
        builder.AppendLine("            {");

        foreach (var (space, name) in clients)
        {
            builder.AppendLine(
                $"                new global::Rask.Api.Client.ApiClientRegistration(typeof(global::{space}.{name}), "
                + $"(http, options) => new global::{space}.{name}(http, options)),");
        }

        builder.AppendLine("            });");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static string HttpMethodMember(string verb) => verb switch
    {
        "GET" => "Get",
        "POST" => "Post",
        "PUT" => "Put",
        "PATCH" => "Patch",
        "DELETE" => "Delete",
        _ => "Get",
    };

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string Indent(string text, string indent)
    {
        var builder = new StringBuilder();

        foreach (var line in text.Split('\n'))
        {
            var trimmed = line.TrimEnd('\r');

            if (trimmed.Length == 0)
            {
                builder.AppendLine();
                continue;
            }

            builder.Append(indent).AppendLine(trimmed);
        }

        return builder.ToString();
    }
}
