using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Rask.Outbox.Generators;

/// <summary>
/// Discovers every <c>Rask.Outbox.IOutboxEvent</c> type in the compilation and emits a per-assembly
/// <c>[ModuleInitializer]</c> that registers each with <c>OutboxSerializerRegistry</c> (name → CLR type),
/// so the outbox processor rehydrates a stored message with no runtime <c>Type.GetType</c> / reflection.
/// </summary>
[Generator]
public sealed class OutboxRegistryGenerator : IIncrementalGenerator
{
    private const string MarkerInterface = "Rask.Outbox.IOutboxEvent";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var events = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax t && t.BaseList is { Types.Count: > 0 },
                static (ctx, _) => GetEventTypeName(ctx))
            .Where(static name => name is not null)
            .Select(static (name, _) => name!);

        context.RegisterSourceOutput(events.Collect(), static (spc, names) => Emit(spc, names));
    }

    // Returns the runtime full name (namespace.TypeName) of a type implementing IOutboxEvent, else null.
    private static string? GetEventTypeName(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not TypeDeclarationSyntax typeDecl ||
            ctx.SemanticModel.GetDeclaredSymbol(typeDecl) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        if (symbol.IsAbstract || symbol.IsGenericType)
        {
            return null;
        }

        var implementsMarker = symbol.AllInterfaces.Any(static i =>
            i.ToDisplayString() == MarkerInterface);

        return implementsMarker ? symbol.ToDisplayString() : null;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<string> names)
    {
        var distinct = names.Distinct().OrderBy(static n => n, System.StringComparer.Ordinal).ToArray();
        if (distinct.Length == 0)
        {
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Rask.Outbox.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class __RaskOutboxRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Init()");
        sb.AppendLine("        {");
        foreach (var name in distinct)
        {
            // The stored name is the runtime Type.FullName; register it against typeof(the type).
            sb.Append("            global::Rask.Outbox.OutboxSerializerRegistry.RegisterEvent(\"")
              .Append(name)
              .Append("\", typeof(global::")
              .Append(name)
              .AppendLine("));");
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("__RaskOutboxRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
