// The WAI-ARIA half of the MDN build step: the snapshot's `aria` section (read from the spec by scripts/mdn/aria.mjs)
// becomes AriaRole's constants, one typed Aria* property per aria-* attribute on Element, the keyword enums those
// properties take, and the slot table Component.AriaAttrs stores them by. Every name and type is derived from the
// spec's data; nothing here is written per attribute.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Rask.Generators.Json;
using static Rask.Core.Dom.Build.DomEmitter;

namespace Rask.Core.Dom.Build;

internal static class AriaEmitter
{
    private const string Header = "// <auto-generated/> from src/Rask.Core/Dom/mdn.snapshot.json by Rask.Dom.targets — do not edit.";

    // What marks every typed-ARIA member this step writes, for the chain generator: a keyword enum's values are keywords an
    // attribute takes, not styles a component reads as, so its members get no steps of their own (`.Polite` on every
    // element); and the Aria* properties share one pending bit, reset through Component.AriaAttrs, instead of one each.
    private const string Mark = "[global::System.CodeDom.Compiler.GeneratedCode(\"Rask.Dom.Aria\", \"1.0\")]";

    // The typed values are slots in one 64-bit set (Component.AriaAttrs).
    private const int MaxSlots = 64;

    public static void Emit(JsonNode root, List<KeyValuePair<string, string>> files)
    {
        var aria = Get(root, "aria");
        files.Add(new KeyValuePair<string, string>("AriaRole.g.cs", Roles(Get(aria, "roles").Items)));
        files.Add(new KeyValuePair<string, string>("Aria.g.cs", Attributes(Typed(root, aria))));
    }

    // One aria-* attribute as Element carries it.
    private sealed class AriaAttribute(JsonNode data, string name, string property, int slot)
    {
        public JsonNode Data { get; } = data;

        public string Name { get; } = name;

        public string Property { get; } = property;

        public int Slot { get; } = slot;

        // The keywords a keyword-valued attribute takes, less `undefined`: an unset property is the attribute absent.
        public List<string> Keywords { get; } = data["values"]?.Items.Select(v => v.AsString()!).Where(v => !string.Equals(v, "undefined", StringComparison.Ordinal)).ToList() ?? new List<string>();

        public string Value => Str(Data, "value")!;

        public bool IsEnum => Value is "tristate" or "token" or "token_list";

        public bool IsFlags => string.Equals(Value, "token_list", StringComparison.Ordinal);

        public string Enum => "global::Rask.Core." + Property;

        public string Type => Value switch
        {
            "true_false" or "true_false_undefined" => "bool?",
            "integer" => "int?",
            "number" => "double?",
            "tristate" or "token" or "token_list" => Enum + "?",
            _ => "string?",
        };
    }

    // Every attribute the spec has not deprecated, named after the IDL attribute on Element that reflects it.
    private static List<AriaAttribute> Typed(JsonNode root, JsonNode aria)
    {
        var idl = Get(Get(Get(root, "interfaces"), "Element"), "members").Items
            .Where(m => Str(m, "reflect") is not null)
            .GroupBy(m => Str(m, "reflect")!, StringComparer.Ordinal)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.Ordinal);
        var attributes = new List<AriaAttribute>();
        foreach (var a in Get(aria, "attributes").Items.Where(a => a["deprecated"]?.AsBoolean() != true))
        {
            var name = Str(a, "name")!;
            idl.TryGetValue(name, out var member);
            var property = PropertyName("Element", name, member is null ? null : Str(member, "name"), member is null ? null : Str(member, "type"));
            attributes.Add(new AriaAttribute(a, name, property, attributes.Count));
        }

        if (attributes.Count > MaxSlots)
        {
            throw new DomEmitException($"the snapshot has {attributes.Count} ARIA attributes; Component.AriaAttrs holds {MaxSlots}");
        }

        var clash = attributes.GroupBy(a => a.Property, StringComparer.Ordinal).FirstOrDefault(g => g.Count() > 1);
        if (clash is not null)
        {
            throw new DomEmitException($"two ARIA attributes map to '{clash.Key}': {string.Join(", ", clash.Select(a => a.Name))}");
        }

        return attributes;
    }

    private static string Roles(List<JsonNode> roles)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Rask.Core;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///     The WAI-ARIA roles an element may take, spelled as the <c>role</c> attribute spells them:");
        sb.AppendLine("///     <c>Div.Role(AriaRole.Tablist)</c>. The spec's abstract roles are left out — they exist for the");
        sb.AppendLine("///     taxonomy, and an author never writes one.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks><see href=\"https://w3c.github.io/aria/#role_definitions\">Spec</see></remarks>");
        sb.AppendLine("public static class AriaRole");
        sb.AppendLine("{");
        var names = new HashSet<string>(StringComparer.Ordinal);
        foreach (var role in roles.Where(r => r["abstract"]?.AsBoolean() != true && r["deprecated"]?.AsBoolean() != true))
        {
            var token = Str(role, "name")!;
            var name = Identifier(token);
            if (!names.Add(name))
            {
                throw new DomEmitException($"two ARIA roles map to AriaRole.{name}");
            }

            sb.Append("    /// <summary>The <c>").Append(token).AppendLine("</c> role.</summary>");
            sb.Append("    /// <remarks>").Append(RoleRemarks(role)).AppendLine("</remarks>");
            sb.Append("    public const string ").Append(name).Append(" = ").Append(Literal(token)).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string RoleRemarks(JsonNode role)
    {
        var remarks = new List<string>();
        var superclass = role["superclass"]?.Items.Select(r => $"<c>{r.AsString()}</c>").ToList() ?? new List<string>();
        if (superclass.Count > 0)
        {
            remarks.Add("A kind of " + string.Join(" and ", superclass) + ".");
        }

        var required = role["required"]?.Items.Select(r => $"<c>{r.AsString()}</c>").ToList() ?? new List<string>();
        if (required.Count > 0)
        {
            remarks.Add("Requires " + string.Join(", ", required) + ".");
        }

        if (role["nameProhibited"]?.AsBoolean() == true)
        {
            remarks.Add("Takes no accessible name.");
        }

        remarks.Add($"<see href=\"{Str(role, "spec")}\">Spec</see>");
        return string.Join(" ", remarks);
    }

    private static string Attributes(List<AriaAttribute> attributes)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header);
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Rask.Core;");
        sb.AppendLine();
        foreach (var a in attributes.Where(a => a.IsEnum))
        {
            KeywordEnum(sb, a);
        }

        sb.AppendLine("public abstract partial class Element");
        sb.AppendLine("{");
        foreach (var a in attributes)
        {
            TypedProperty(sb, a);
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public abstract partial class Component");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed partial class AriaAttrs");
        sb.AppendLine("    {");
        sb.AppendLine("        // Each slot's attribute name, in slot order: the order they render in.");
        sb.Append("        private static readonly string[] Names = [")
            .Append(string.Join(", ", attributes.Select(a => Literal(a.Name)))).AppendLine("];");
        sb.AppendLine();
        sb.AppendLine("        // The slot an Aria bag key names, or -1.");
        sb.AppendLine("        private static int SlotOf(string key) => key switch");
        sb.AppendLine("        {");
        foreach (var a in attributes)
        {
            sb.Append("            ").Append(Literal(a.Name.Substring("aria-".Length))).Append(" => ").Append(a.Slot).AppendLine(",");
        }

        sb.AppendLine("            _ => -1,");
        sb.AppendLine("        };");
        foreach (var a in attributes.Where(a => a.IsEnum))
        {
            sb.AppendLine();
            if (a.IsFlags)
            {
                FlagsConversions(sb, a);
            }
            else
            {
                KeywordConversions(sb, a);
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void TypedProperty(StringBuilder sb, AriaAttribute a)
    {
        sb.Append("    /// <summary>The <c>").Append(a.Name).Append("</c> ").Append(Str(a.Data, "kind")).Append(": ")
            .Append(ValuePhrase(a)).Append('.');
        if (Str(a.Data, "default") is { } dflt && !string.Equals(dflt, "undefined", StringComparison.Ordinal))
        {
            sb.Append(" Default <c>").Append(dflt).Append("</c>.");
        }

        sb.AppendLine("</summary>");
        sb.Append("    /// <remarks><see href=\"https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/")
            .Append(a.Name).Append("\">MDN</see> <see href=\"").Append(Str(a.Data, "spec")).AppendLine("\">Spec</see></remarks>");
        sb.Append("    ").AppendLine(Mark);
        sb.Append("    public ").Append(a.Type).Append(' ').AppendLine(a.Property);
        sb.AppendLine("    {");
        var read = $"AriaAttrsInternal?.Get({a.Slot})";
        var (get, set) = a.Type switch
        {
            "bool?" => ($"AriaAttrs.Boolean({read})", $"Set({a.Slot}, AriaAttrs.Boolean(value))"),
            "int?" => ($"AriaAttrs.Integer({read})", $"SetInteger({a.Slot}, value)"),
            "double?" => ($"AriaAttrs.Number({read})", $"SetNumber({a.Slot}, value)"),
            "string?" => (read, $"Set({a.Slot}, value)"),
            _ => ($"AriaAttrs.Parse{a.Property}({read})", $"Set({a.Slot}, AriaAttrs.Keyword(value))"),
        };
        sb.Append("        get => ").Append(get).AppendLine(";");
        sb.Append("        set => AriaAttrsForWrite(value is not null)?.").Append(set).AppendLine(";");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string ValuePhrase(AriaAttribute a) => a.Value switch
    {
        "true_false" => "<c>true</c> or <c>false</c>",
        "true_false_undefined" => "<c>true</c> or <c>false</c>; <see langword=\"null\" /> leaves it undefined",
        "tristate" or "token" => $"one of <see cref=\"{a.Enum}\" />'s keywords",
        "token_list" => $"any of <see cref=\"{a.Enum}\" />'s keywords, combined",
        "idref" => "the id of the element it refers to",
        "idref_list" => "the ids of the elements it refers to, space-separated",
        "integer" => "an integer",
        "number" => "a number",
        _ => "text",
    };

    private static void KeywordEnum(StringBuilder sb, AriaAttribute a)
    {
        sb.Append("/// <summary>The keywords <c>").Append(a.Name).Append("</c> takes, for <see cref=\"Element.")
            .Append(a.Property).AppendLine("\" />.</summary>");
        sb.Append("/// <remarks><see href=\"").Append(Str(a.Data, "spec")).AppendLine("\">Spec</see></remarks>");
        if (a.IsFlags)
        {
            sb.AppendLine("[global::System.Flags]");
        }

        sb.AppendLine(Mark);
        sb.Append("public enum ").AppendLine(a.Property);
        sb.AppendLine("{");
        var members = new HashSet<string>(StringComparer.Ordinal);
        var values = new HashSet<int>();
        for (var i = 0; i < a.Keywords.Count; i++)
        {
            var keyword = a.Keywords[i];
            var member = Identifier(keyword);
            // A flag is a bit, so a combination still reads back; a keyword is its hash (Fnv1a), so a refresh that adds
            // or reorders one moves no other member's value.
            var value = a.IsFlags ? 1 << i : Fnv1a.Hash(keyword);
            if (!members.Add(member) || !values.Add(value))
            {
                throw new DomEmitException($"{a.Name}'s keyword `{keyword}` collides with another as {a.Property}.{member} = {value}");
            }

            sb.Append("    /// <summary>The keyword <c>").Append(keyword).AppendLine("</c>.</summary>");
            sb.Append("    ").Append(member).Append(" = ").Append(value).AppendLine(",");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // A keyword's text is the interned literal it renders as, so setting and writing one allocates nothing.
    private static void KeywordConversions(StringBuilder sb, AriaAttribute a)
    {
        sb.Append("        public static string? Keyword(").Append(a.Type).AppendLine(" value) => value switch");
        sb.AppendLine("        {");
        foreach (var k in a.Keywords)
        {
            sb.Append("            ").Append(a.Enum).Append('.').Append(Identifier(k)).Append(" => ").Append(Literal(k)).AppendLine(",");
        }

        sb.AppendLine("            _ => null,");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.Append("        public static ").Append(a.Type).Append(" Parse").Append(a.Property).AppendLine("(string? text) => text switch");
        sb.AppendLine("        {");
        foreach (var k in a.Keywords)
        {
            sb.Append("            ").Append(Literal(k)).Append(" => ").Append(a.Enum).Append('.').Append(Identifier(k)).AppendLine(",");
        }

        sb.AppendLine("            _ => null,");
        sb.AppendLine("        };");
    }

    // A single keyword is its literal; a combination is the keywords in the spec's order, space-separated.
    private static void FlagsConversions(StringBuilder sb, AriaAttribute a)
    {
        sb.Append("        public static string? Keyword(").Append(a.Type).AppendLine(" value)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (value)");
        sb.AppendLine("            {");
        sb.AppendLine("                case null or 0:");
        sb.AppendLine("                    return null;");
        foreach (var k in a.Keywords)
        {
            sb.Append("                case ").Append(a.Enum).Append('.').Append(Identifier(k)).Append(": return ").Append(Literal(k)).AppendLine(";");
        }

        sb.AppendLine("            }");
        sb.AppendLine();
        sb.Append("            var words = new global::System.Collections.Generic.List<string>(").Append(a.Keywords.Count).AppendLine(");");
        foreach (var k in a.Keywords)
        {
            sb.Append("            if ((value.Value & ").Append(a.Enum).Append('.').Append(Identifier(k)).Append(") != 0) words.Add(")
                .Append(Literal(k)).AppendLine(");");
        }

        sb.AppendLine("            return words.Count == 0 ? null : string.Join(\" \", words);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.Append("        public static ").Append(a.Type).Append(" Parse").Append(a.Property).AppendLine("(string? text)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (text is null)");
        sb.AppendLine("            {");
        sb.AppendLine("                return null;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.Append("            var value = default(").Append(a.Enum).AppendLine(");");
        sb.AppendLine("            foreach (var word in text.Split(' '))");
        sb.AppendLine("            {");
        sb.AppendLine("                value |= word switch");
        sb.AppendLine("                {");
        foreach (var k in a.Keywords)
        {
            sb.Append("                    ").Append(Literal(k)).Append(" => ").Append(a.Enum).Append('.').Append(Identifier(k)).AppendLine(",");
        }

        sb.Append("                    _ => default(").Append(a.Enum).AppendLine("),");
        sb.AppendLine("                };");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return value;");
        sb.AppendLine("        }");
    }

    // A keyword or role as a C# name, mechanically: its words PascalCased (`alertdialog` → Alertdialog, `doc-note` →
    // DocNote). No word list: a name reads as the token the spec spells.
    private static string Identifier(string token)
    {
        var name = string.Concat(token.Split('-', '_', ' ').Where(w => w.Length > 0).Select(Pascal));
        if (name.Length == 0 || !name.All(char.IsLetterOrDigit) || char.IsDigit(name[0]))
        {
            throw new DomEmitException($"the ARIA token `{token}` makes no C# name");
        }

        return name;
    }
}
