// The CSS half of the build step: one step per property on Css, from the snapshot's `css` — every property two
// engines ship, with the keywords and value types that are a whole value alone (scripts/mdn/css.mjs).
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Rask.Generators.Json;

namespace Rask.Core.Dom.Build;

internal static class CssEmitter
{
    // A value type CSS names -> the C# type a step takes it as, and how that is written as CSS. What is not here
    // (a colour, an identifier, an angle) is written as text.
    private static readonly Dictionary<string, (string Type, string Text, string What)> Values = new(StringComparer.Ordinal)
    {
        ["length"] = ("global::Rask.Length", "value.ToString()", "a length"),
        ["percentage"] = ("global::Rask.Percentage", "value.ToString()", "a percentage"),
        ["number"] = ("double", "value.ToString(global::System.Globalization.CultureInfo.InvariantCulture)", "a number"),
        ["integer"] = ("int", "value.ToString(global::System.Globalization.CultureInfo.InvariantCulture)", "a whole number"),
        ["time"] = ("global::System.TimeSpan", "value.TotalMilliseconds.ToString(global::System.Globalization.CultureInfo.InvariantCulture) + \"ms\"", "a duration"),
    };

    public static IEnumerable<KeyValuePair<string, string>> Emit(string snapshotJson)
    {
        var root = DomEmitter.Parse(snapshotJson);
        var properties = root["css"]?["properties"] ?? throw new DomEmitException("the snapshot has no `css`: run scripts/mdn/refresh.sh");
        var entries = new StringBuilder();
        var steps = new StringBuilder();
        var taken = new HashSet<string>(StringComparer.Ordinal);
        foreach (var property in properties.Items)
        {
            var name = DomEmitter.Str(property, "name") ?? throw new DomEmitException("a `css` property has no name");
            var method = Identifier(name, "CSS property");
            if (!taken.Add(method))
            {
                throw new DomEmitException($"two CSS properties are both `{method}` in C#; the second is `{name}`");
            }

            Property(entries, steps, property, name, method);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> from src/Rask.Core/Dom/mdn.snapshot.json by Rask.Dom.targets — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Rask.Core;");
        sb.AppendLine();
        sb.AppendLine("public readonly partial record struct Css");
        sb.AppendLine("{");
        sb.Append(entries);
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>The same steps on a style already begun: <c>Css.Height(40.Px).Width(110.Px)</c>.</summary>");
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("public static partial class CssSteps");
        sb.AppendLine("{");
        sb.Append(steps);
        sb.AppendLine("}");
        yield return new KeyValuePair<string, string>("Css.g.cs", sb.ToString());
    }

    private static void Property(StringBuilder entries, StringBuilder steps, JsonNode property, string name, string method)
    {
        var literal = DomEmitter.Literal(name);

        Step(entries, steps, property, method, "string? value", $"With({literal}, value)",
            $"The <c>{name}</c> property, as any text CSS allows. <see langword=\"null\" /> declares nothing.");
        foreach (var accepted in property["accepts"]?.Items.Select(a => a.AsString()!) ?? [])
        {
            if (Values.TryGetValue(accepted, out var value))
            {
                Step(entries, steps, property, method, value.Type + " value", $"With({literal}, {value.Text})", $"The <c>{name}</c> property, as {value.What}.");
            }
        }

        var keywords = property["keywords"]?.Items.Select(k => k.AsString()!).ToList() ?? [];
        if (keywords.Count == 0)
        {
            return;
        }

        var type = method + "Keywords";
        var summary = $"The <c>{name}</c> property, as one of its keywords: <c>Css.{method}().{Identifier(keywords[0], "CSS keyword")}</c>.";
        DomEmitter.Member(entries, "    ", summary, property);
        entries.Append("    public static ").Append(type).Append(' ').Append(method).AppendLine("() => new(default);").AppendLine();
        DomEmitter.Member(steps, "    ", summary, property);
        steps.Append("    public static global::Rask.Core.Css.").Append(type).Append(' ').Append(method).AppendLine("(this global::Rask.Core.Css css) => new(css);").AppendLine();

        entries.Append("    /// <summary>The keywords <c>").Append(name).AppendLine("</c> takes as a whole value.</summary>");
        entries.AppendLine("    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        entries.Append("    public readonly struct ").AppendLine(type);
        entries.AppendLine("    {");
        entries.AppendLine("        private readonly Css _css;");
        entries.AppendLine();
        entries.Append("        internal ").Append(type).AppendLine("(Css css) => _css = css;");
        var members = new HashSet<string>(StringComparer.Ordinal);
        foreach (var keyword in keywords)
        {
            var member = Identifier(keyword, "CSS keyword");
            if (!members.Add(member))
            {
                throw new DomEmitException($"two keywords of `{name}` are both `{member}` in C#; the second is `{keyword}`");
            }

            entries.AppendLine();
            entries.Append("        /// <summary><c>").Append(name).Append(": ").Append(keyword).AppendLine("</c>.</summary>");
            entries.Append("        public Css ").Append(member).Append(" => _css.With(").Append(literal).Append(", ").Append(DomEmitter.Literal(keyword)).AppendLine(");");
        }

        entries.AppendLine("    }").AppendLine();
    }

    // One value form of a property, twice: the entry on Css that begins a style, and the step that continues one.
    private static void Step(StringBuilder entries, StringBuilder steps, JsonNode property, string method, string parameter, string with, string summary)
    {
        DomEmitter.Member(entries, "    ", summary, property);
        entries.Append("    public static Css ").Append(method).Append('(').Append(parameter).Append(") => default(Css).").Append(with).AppendLine(";").AppendLine();
        DomEmitter.Member(steps, "    ", summary, property);
        steps.Append("    public static global::Rask.Core.Css ").Append(method).Append("(this global::Rask.Core.Css css, ").Append(parameter).Append(") => css.").Append(with).AppendLine(";").AppendLine();
    }

    // `min-content` -> MinContent, `sRGB` -> SRGB. Mechanical, with no word list: a name CSS spells otherwise fails the build.
    private static string Identifier(string css, string kind)
    {
        var name = string.Concat(css.Split('-').Select(DomEmitter.Pascal));
        if (name.Length == 0 || !char.IsLetter(name[0]) || !name.All(char.IsLetterOrDigit) || name.Any(c => c > 127))
        {
            throw new DomEmitException(string.Format(CultureInfo.InvariantCulture, "the {0} `{1}` is not a C# name", kind, css));
        }

        return name;
    }
}
