// The KEYBOARD half of the build step: KeyboardEvent.key's named values (Keys) and KeyboardEvent.code's values (Codes),
// one string constant each, from the snapshot's `keys` and `codes` — UI Events' own tables, read by scripts/mdn/refresh.mjs.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Rask.Generators.Json;

namespace Rask.Core.Dom.Build;

internal static class KeyboardValueEmitter
{
    public static IEnumerable<KeyValuePair<string, string>> Emit(string snapshotJson)
    {
        var root = DomEmitter.Parse(snapshotJson);
        var sources = root["sources"];
        yield return Constants(root, "keys", "Keys", "key", "The named values of <see cref=\"KeyboardEvent.Key\" />, what a key that types no character reports",
            "A key that types a character reports that character instead (<c>\"q\"</c>, <c>\"Q\"</c>, <c>\" \"</c>), which no constant names. "
            + "Each is a constant, so it is a pattern too: <c>e.Key is Keys.Escape</c>.",
            sources?["w3c/uievents-key"]?.AsString());
        yield return Constants(root, "codes", "Codes", "code", "The values of <see cref=\"KeyboardEvent.Code\" />, the physical key pressed whatever the layout types with it",
            "Each is named after the key's place on a US keyboard: <c>KeyQ</c> is the same key on an AZERTY layout, where it types <c>a</c>.",
            sources?["w3c/uievents-code"]?.AsString());
    }

    private static KeyValuePair<string, string> Constants(JsonNode root, string section, string type, string kind, string what, string note, string? commit)
    {
        var values = root[section] ?? throw new DomEmitException($"the snapshot has no `{section}`: run scripts/mdn/refresh.sh");
        var spec = $"https://w3c.github.io/uievents-{kind}/";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> from src/Rask.Core/Dom/mdn.snapshot.json by Rask.Dom.targets — do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Rask.Core;");
        sb.AppendLine();
        sb.Append("/// <summary>").Append(what).AppendLine(", as UI Events lists them.</summary>");
        sb.Append("/// <remarks>").Append(note).Append(" <see href=\"").Append(spec).Append("\">Spec</see>")
            .Append(commit is null ? "" : $" (w3c/uievents-{kind} {commit.Substring(0, Math.Min(7, commit.Length))})").AppendLine("</remarks>");
        sb.Append("public static partial class ").AppendLine(type);
        sb.AppendLine("{");
        var first = true;
        foreach (var value in values.Items)
        {
            var name = value["name"]?.AsString() ?? throw new DomEmitException($"a `{section}` entry has no name");
            if (!IsIdentifier(name))
            {
                throw new DomEmitException($"the {kind} value `{name}` is not a C# name");
            }

            if (!first)
            {
                sb.AppendLine();
            }

            first = false;
            sb.Append("    /// <summary><c>\"").Append(name).Append("\"</c>, from the spec's <c>").Append(value["group"]?.AsString())
                .AppendLine("</c> table.</summary>");
            var optional = value["optional"]?.AsBoolean() == true ? "Optional: a conforming browser need not report it. " : "";
            sb.Append("    /// <remarks>").Append(optional).Append("<see href=\"").Append(value["spec"]?.AsString() ?? spec).AppendLine("\">Spec</see></remarks>");
            sb.Append("    public const string ").Append(name).Append(" = \"").Append(name).AppendLine("\";");
        }

        sb.AppendLine("}");
        return new KeyValuePair<string, string>(type + ".g.cs", sb.ToString());
    }

    private static bool IsIdentifier(string name) => name.Length > 0 && char.IsLetter(name[0]) && name.All(char.IsLetterOrDigit);
}
