// <auto-generated> by Rask. Regenerated on every build; edits are lost. </auto-generated>

import { message, registerShapes } from './client';
import { shapes } from './contracts';
import type { GetGreeting, Greeting, RecordVisit } from './contracts';

// Handed to the client here rather than imported by it, so client.ts stays independent of
// the generated files: a scaffolded app type-checks before its first build has produced
// any. Importing this module is what arms date revival, which is why every call site
// reaches the server through a factory from here.
registerShapes(shapes);

export const getGreeting = message<GetGreeting, Greeting, 'query'>({
  name: 'Rask.Example.Meta.SolidStart.Features.Hello.GetGreeting',
  kind: 'query',
  result: ['Greeting', 0],
});

export const recordVisit = message<RecordVisit, number, 'command'>({
  name: 'Rask.Example.Meta.SolidStart.Features.Hello.RecordVisit',
  kind: 'command',
});

