using System.Collections.Immutable;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Rask.Generators.Analyzers;

namespace Rask.Generators.Tests;

public class ComponentConstructionAnalyzerTests
{
    [Fact]
    public async Task NewBuiltInTag_ReportsRask014()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var x = new Div(null); }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
        Assert.Contains("Div", d.GetMessage());
    }

    [Fact]
    public async Task NewUserComponent_ReportsRask014()
    {
        var src = """
                  using Rask.Core;
                  namespace Demo;
                  public sealed class Counter : Component
                  {
                      public override Component Render() => this;
                  }
                  class Caller { void M() { var x = new Counter(); } }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
    }

    [Fact]
    public async Task TargetTypedNewComponent_ReportsRask014()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      Div M() { Div d = new(null); return d; }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
    }

    [Fact]
    public async Task NewPropsRecord_NoDiagnostic()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var p = new Div.Props("i", null, null, null); }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task ComponentSubclassDeclaration_NoDiagnostic()
    {
        var src = """
                  using Rask.Core;
                  namespace Demo;
                  public sealed class Counter : Component
                  {
                      public override Component Render() => this;
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task BaseConstructorCallInUserComponent_NoDiagnostic()
    {
        var src = """
                  using System.Collections.Generic;
                  using Rask.Core;
                  using Rask.Core.Components;
                  namespace Demo;
                  public sealed class MyDiv : Div
                  {
                      public MyDiv(Div.Props? props, IEnumerable<Child>? children) : base(props, children) { }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task NewInsideAutoGeneratedFile_NoDiagnostic()
    {
        var src = """
                  // <auto-generated/>
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var x = new Div(null); }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task NewInRaskCoreAssembly_NoDiagnostic()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var x = new Div(null); }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src, "Rask.Core");

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task NewInsideUserRenderOverride_ReportsRask014()
    {
        var src = """
                  using Rask.Core;
                  using Rask.Core.Components;
                  namespace Demo;
                  public sealed class Page : Component
                  {
                      protected override Component Render() => new Div(null);
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
    }

    [Fact]
    public async Task NewInsideArrayInitializer_ReportsRask014ForEachElement()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var arr = new[] { new Div(null), new Span(null) }; }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        // The implicit `new[]` is not a Component (array creation), so only the
        // two inner Component constructors should be flagged.
        Assert.Equal(2, diagnostics.Length);
        Assert.All(diagnostics, d => Assert.Equal("RASK014", d.Id));
    }

    [Fact]
    public async Task NewInternalUserComponent_ReportsRask014()
    {
        var src = """
                  using Rask.Core;
                  namespace Demo;
                  internal sealed class Hidden : Component
                  {
                      public override Component Render() => this;
                  }
                  class Caller { void M() { var x = new Hidden(); } }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
    }

    private static async Task<ImmutableArray<Diagnostic>> GetDiagnosticsAsync(string source,
        string assemblyName = "TestAssembly")
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest));
        var references = BuildReferences();
        var compilation = CSharpCompilation.Create(
            assemblyName,
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));

        var analyzers = ImmutableArray.Create<DiagnosticAnalyzer>(new ComponentConstructionAnalyzer());
        var withAnalyzers = compilation.WithAnalyzers(analyzers);
        var all = await withAnalyzers.GetAnalyzerDiagnosticsAsync();
        return all.Where(d => d.Id == "RASK014").ToImmutableArray();
    }

    private static ImmutableArray<MetadataReference> BuildReferences()
    {
        var trustedAssemblies = ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ?? string.Empty)
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries);
        var refs = trustedAssemblies
            .Select(path => MetadataReference.CreateFromFile(path))
            .Cast<MetadataReference>()
            .ToList();

        var raskCore = Assembly.Load("Rask.Core");
        refs.Add(MetadataReference.CreateFromFile(raskCore.Location));
        return refs.ToImmutableArray();
    }
}
