<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
    <Using Include="Rask.Core.Components"/>
    <Using Include="Rask.Core.Components.Generated" Static="true"/>
    <Using Include="Rask.Validation.DataAnnotations"/>
    <Using Include="Rask.Validation.DataAnnotations.Generated" Static="true"/>
    <Using Include="Rask.TestSupport"/>
    <Using Include="Rask.Validation.DataAnnotations.Tests.ValidationTestSupport" Static="true"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rask.Core\Rask.Core.csproj"/>
    <ProjectReference Include="..\..\src\Rask.Validation.DataAnnotations\Rask.Validation.DataAnnotations.csproj"/>
    <ProjectReference Include="..\Rask.TestSupport\Rask.TestSupport.csproj"/>
    <ProjectReference Include="..\..\src\Rask.Generators\Rask.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

</Project>
