// <auto-generated> by Rask. Regenerated on every build; edits are lost. </auto-generated>

/** A GUID, as its canonical string form. */
export type Guid = string;
/** A calendar date, `YYYY-MM-DD`. Deliberately not a Date: `new Date("2026-08-25")` is UTC
 *  midnight, so anyone west of UTC would render it as the 24th. */
export type DateOnly = string;
/** A time of day, `HH:mm:ss.fffffff`. Seven fractional digits, which `Date` cannot parse. */
export type TimeOnly = string;
/** A length of time, `[-][d.]hh:mm:ss[.fffffff]`. Not an ISO-8601 duration. */
export type Duration = string;
/** Bytes, base64-encoded. */
export type Base64 = string;

export interface GetGreeting {
  name: string;
}

export interface Greeting {
  message: string;
  seenAt: Date;
  visits: number;
}

export interface RecordVisit {
  name: string;
}

/**
 * Which properties of each shape carry an instant, and which lead to another shape.
 *
 * The client revives exactly these into `Date` objects. It does not sniff strings: a regex
 * reviver converts a product code or an ETag that merely looks like a timestamp, silently.
 * Nothing here is guessed — the C# type said so.
 *
 * The number beside a nested shape is how many arrays or dictionaries stand between the
 * property and it. Both arrive as plain objects in JSON, so without the count the runtime
 * would revive a dictionary's keys as if they were the shape's own properties.
 */
export const shapes = {
  Greeting: { instants: ['seenAt'], nested: {} },
} as const;
