using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Rask.Core;
using Rask.Core.Components;
using Rask.Core.Live;

namespace Rask.Blazor;

/// <summary>
///     A Rask component whose markup is produced by a real Blazor component.
/// </summary>
/// <typeparam name="TComponent">
///     The hosted component — your Razor Class Library's type, or one from a package such as
///     MudBlazor. It is named as a type argument rather than inferred from a sibling file because
///     that is the one place it cannot drift from what actually renders, and because the common case
///     has no file in your project at all: the type comes from a reference.
/// </typeparam>
/// <remarks>
///     <para>
///         The Razor SDK compiles <c>.razor</c> exactly as it always has — this package neither
///         replaces nor configures it. What it does is render the resulting component server-side and
///         place its HTML in the page, with parameters passed as live C# objects rather than
///         serialized, so any type the hosted parameter accepts crosses intact.
///     </para>
///     <para>
///         The hosted component must live in a REFERENCED project or package for its parameters to be
///         checked at compile time. A <c>.razor</c> in the same project as the island is generated by
///         the Razor source generator, and one source generator cannot see another's output, so
///         Rask's generator cannot resolve its parameters — that still works, but unverified, and
///         says so through RASK066.
///     </para>
///     <para>
///         Because the hosted type is a type argument, a component that already extends something
///         else cannot host one. That is deliberate and matches the islands feature: chrome in Rask
///         comes from the chain, not from inheritance, so the answer is to compose —
///         <c>BsCard[ Chart.Series(points) ]</c> — rather than to inherit both.
///     </para>
/// </remarks>
public abstract partial class BlazorComponent<TComponent> : Component
    where TComponent : IComponent, new()
{
    private BlazorIslandRenderer? _renderer;
    private TComponent? _instance;
    private int _componentId = -1;
    private string? _html;

    // (Blazor handler id, DOM event) per placeholder the writer left in _html, in index order.
    private readonly List<(ulong BlazorHandlerId, string EventName)> _handlers = [];

    // Whether there is a live session to dispatch through, captured on the render thread. The HTML is
    // rewritten from the renderer's dispatcher, where the ambient context is not visible.
    private bool _live;

    // Refilled rather than reallocated per render. Not the render hot path — this runs from an async
    // lifecycle hook, not the serialize walk — but the habit is the repo's.
    private readonly Dictionary<string, object?> _parameters = new(StringComparer.Ordinal);

    /// <summary>How much of the hosted component's own behaviour reaches the browser.</summary>
    /// <remarks>
    ///     Nullable rather than a property with an initializer, and that is not a style choice. A
    ///     member initializer compiles into the constructor and leaves no trace in metadata, so across
    ///     an assembly boundary <c>Interactivity { get; set; } = Static</c> is indistinguishable from
    ///     <c>Interactivity { get; set; }</c> — the chain would read it as a REQUIRED step and force
    ///     every call site to spell out a value that has an obvious default. Nullability survives
    ///     metadata, and says the more precise thing: null is "not specified".
    /// </remarks>
    public BlazorInteractivity? Interactivity { get; set; }

    /// <summary>The name this island is identified by. Its own simple type name.</summary>
    protected virtual string ComponentName => GetType().Name;

    /// <summary>
    ///     Never replayed from the render cache.
    /// </summary>
    /// <remarks>
    ///     A handler id belongs to the render that minted it, and this component mints one per event
    ///     the hosted component wired. A cached replay skips <see cref="Render" />, so nothing
    ///     re-registers them — and the replayed markup then points at handler ids the dispatcher can
    ///     no longer find. The failure is the worst shape available: the island looks right, and the
    ///     first click does nothing.
    /// </remarks>
    protected sealed override bool BypassRenderCache => true;

    /// <summary>
    ///     Fills <paramref name="into" /> with the hosted component's parameters. Generated.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Reflection-free by construction: every name and every read is decided at compile time,
    ///         and <see cref="ParameterView.FromDictionary" /> takes exactly this shape.
    ///     </para>
    ///     <para>
    ///         A nullable property that is null OMITS its key rather than writing null — the opposite
    ///         of what the islands feature does, and deliberately so. There, JSON <c>null</c> and an
    ///         absent key are different facts to TypeScript. Here <see cref="ParameterView" /> is
    ///         authoritative: any key it carries OVERWRITES the hosted component's own default, so
    ///         writing <c>Width = null</c> would clobber a default the component meant to keep.
    ///     </para>
    /// </remarks>
    protected abstract void WriteParameters(Dictionary<string, object?> into);

    /// <summary>Creates the hosted component. Never reflective — the type argument is known.</summary>
    protected virtual TComponent Create() => new();

    /// <summary>
    ///     Mounts the hosted component and re-renders it whenever a Rask prop changes.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Everything lives here rather than being split with <c>OnMountAsync</c>, because Rask
    ///         fires this hook when <c>firstRender || propsChanged</c> — mount and update are already
    ///         one code path, so splitting them would only add a first-render special case to get
    ///         wrong.
    ///     </para>
    ///     <para>
    ///         Being async is what puts the island in the FIRST response: the returned task is
    ///         registered in the ambient quiescence scope, so Rask renders, waits for this, and
    ///         renders again — and the response carries the second wave. A hosted component that
    ///         awaits in <c>OnInitializedAsync</c> is therefore complete in the delivered HTML rather
    ///         than appearing a frame later.
    ///     </para>
    /// </remarks>
    protected override async Task OnPropsChangedAsync()
    {
        var renderer = _renderer ??= CreateRenderer();

        // Children are consumed as the hosted component's ChildContent, so they are read here —
        // before the serialize walk — and never emitted by Rask itself.
        var childMarkup = CaptureChildren();

        // Captured on THIS thread. The render below hops to the renderer's dispatcher, and the
        // ambient context is thread-static, so it would be gone by the time handlers are registered.
        var context = LiveRenderContext.Current ?? LiveRenderContext.CurrentSync;

        await renderer.Dispatcher.InvokeAsync(async () =>
        {
            if (_componentId < 0)
            {
                _instance = Create();
                _componentId = renderer.Attach(_instance);
            }

            await renderer.RenderAsync(_componentId, BuildParameterView(childMarkup));

            // Handlers are NOT registered here. A handler id belongs to the render that minted it, and
            // this hook runs outside the render walk — on the renderer's own dispatcher, no less — so
            // anything registered now is discarded by the next walk and the id in the markup resolves
            // to nothing. The writer leaves a placeholder per handler instead, and Render() (which IS
            // the walk) registers them and substitutes the real ids.
            _live = context is not null;
            RewriteHtml();
        });
    }

    /// <summary>
    ///     Registers one of the hosted component's event handlers as an ordinary Rask handler.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         This is what makes a hosted component's own <c>@onclick</c> work with no Blazor
    ///         circuit. Blazor assigns the handler an id during the static render; we hand that id a
    ///         Rask handler id, the browser's existing delegated listener sends it over the socket
    ///         that is already open, and it comes back here to be dispatched into Blazor. The same
    ///         contract the React and Lit islands use, over the same channel.
    ///     </para>
    ///     <para>
    ///         Returns null when there is no live session, so no attribute is written at all — an
    ///         inert island is better than markup advertising a handler that cannot be delivered.
    ///     </para>
    /// </remarks>
    /// <summary>The stand-in a handler id occupies until BindHandlers mints the real one.</summary>
    /// <remarks>
    ///     Delimited by U+0001 because it is substituted into rendered HTML, where an undelimited
    ///     token like <c>rb0</c> could occur in the hosted component's own content and be rewritten
    ///     into a handler id. A control character cannot appear in the markup Blazor produces.
    /// </remarks>
    private static string Placeholder(int index) => "\u0001rb" + index + "\u0001";

    /// <summary>Re-reads the hosted component's markup from its current render tree.</summary>
    /// <remarks>
    ///     Called both after a Rask prop change and when the hosted component re-renders ITSELF. The
    ///     second is easy to miss, and was missed: a self-render called StateHasChanged without
    ///     re-reading the markup, so Rask faithfully re-rendered the previous string and the
    ///     component's own update - a timer, an injected service's event, the write-back half of
    ///     <c>@bind</c> - never reached the page. The island looked alive and showed stale content.
    ///
    ///     Runs on the renderer's dispatcher, which is where both callers already are.
    /// </remarks>
    private void RewriteHtml()
    {
        if (_renderer is null || _componentId < 0)
        {
            return;
        }

        _handlers.Clear();
        _html = BlazorFrameWriter.Write(
            _renderer,
            _componentId,
            (blazorId, eventName) =>
            {
                // No live session to dispatch through, so no attribute at all: markup advertising a
                // handler that cannot be delivered is worse than inert markup.
                if (!_live)
                {
                    return null;
                }

                _handlers.Add((blazorId, eventName));
                return Placeholder(_handlers.Count - 1);
            });
    }

    /// <summary>
    ///     Registers this render's handlers and puts their ids into the markup.
    /// </summary>
    /// <remarks>
    ///     Runs from <see cref="Render" />, inside the render walk, because that is where a handler id
    ///     is valid: it belongs to the render that minted it. Registering from the async hook instead
    ///     produced ids the very next walk discarded, and the markup pointed at handlers the
    ///     dispatcher could not find.
    /// </remarks>
    private string? BindHandlers()
    {
        if (_html is null || _handlers.Count == 0)
        {
            return _html;
        }

        var context = LiveRenderContext.CurrentSync ?? LiveRenderContext.Current;
        var renderer = _renderer;
        if (context is null || renderer is null)
        {
            return _html;
        }

        var sb = new System.Text.StringBuilder(_html);
        for (var i = 0; i < _handlers.Count; i++)
        {
            var (blazorHandlerId, eventName) = _handlers[i];

            // A value-carrying event needs a delegate that TAKES the value: Rask routes an inbound
            // frame to a handler by the delegate's shape, and only Action<string>/Func<string, Task>
            // is fed the string payload. This is what carries @bind — Blazor's binding compiles to
            // `value=` plus an onchange handler reading ChangeEventArgs.Value, and that value can
            // only arrive here.
            Delegate handler = eventName is "change" or "input"
                ? (Func<string, Task>)(value => renderer.Dispatcher.InvokeAsync(
                    () => renderer.DispatchAsync(blazorHandlerId, new ChangeEventArgs { Value = value })))
                : (Func<Task>)(() => renderer.Dispatcher.InvokeAsync(
                    () => renderer.DispatchAsync(blazorHandlerId, EventArgsFor(renderer, blazorHandlerId))));

            // RegisterHandlerFor, never owner.RegisterHandler: that overload treats its receiver as
            // the render ROOT and restarts the id sequence at zero, so the handler would collide with
            // the page's own and silently never fire.
            sb.Replace(Placeholder(i), context.RegisterHandlerFor(this, handler));
        }

        return sb.ToString();
    }

    private static EventArgs EventArgsFor(BlazorIslandRenderer renderer, ulong handlerId)
    {
        // Blazor knows what each handler expects. A component reading e.ClientX would otherwise get a
        // bare EventArgs and cast-fail at the worst moment.
        try
        {
            var type = renderer.ArgsTypeFor(handlerId);
            return type == typeof(EventArgs)
                ? EventArgs.Empty
                : (EventArgs)Activator.CreateInstance(type)!;
        }
        catch (Exception)
        {
            return EventArgs.Empty;
        }
    }

    /// <summary>Releases the hosted component and its renderer.</summary>
    /// <remarks>
    ///     Asynchronous on purpose: a <see cref="IDisposable.Dispose" /> while a render is in flight
    ///     on the renderer's dispatcher is a hang, not a leak.
    /// </remarks>
    protected override async Task OnUnmountAsync()
    {
        if (_renderer is null)
        {
            return;
        }

        if (_componentId >= 0)
        {
            await _renderer.Dispatcher.InvokeAsync(() => _renderer.Detach(_componentId));
            _componentId = -1;
        }

        await _renderer.DisposeAsync();
        _renderer = null;
        _instance = default;
    }

    /// <inheritdoc />
    protected sealed override Component? Render() =>
        BlazorHost
            .Opaque(Interactivity == BlazorInteractivity.Circuit)
            .Data(new Dictionary<string, string?> { ["rask-blazor"] = ComponentName })
            .Attributes(new Dictionary<string, string?>
            {
                [BlazorDefaults.NameAttribute] = ComponentName,
                [BlazorDefaults.ComponentAttribute] = typeof(TComponent).FullName,
            })[
            BindHandlers() is { } markup ? Raw.Value(markup) : null
        ];

    private BlazorIslandRenderer CreateRenderer()
    {
        var services = LiveRenderContext.Current?.Services
                       ?? LiveRenderContext.CurrentSync?.Services
                       ?? throw new InvalidOperationException(
                           $"'{GetType().Name}' hosts the Blazor component '{typeof(TComponent).Name}', which needs the "
                           + "application's services to render. Rask could not find them for this render. Call "
                           + "'services.AddRaskBlazor()' in Program.cs.");

        var logs = services.GetService<ILoggerFactory>() ?? NullLoggerFactory.Instance;

        // A render the hosted component asked for itself (a timer, an injected service's event) has
        // nowhere to go without a live session, so say so as well as repainting.
        return new BlazorIslandRenderer(services, logs, () =>
        {
            // Re-read BEFORE telling Rask to repaint, or the repaint ships the previous markup.
            RewriteHtml();
            StateHasChanged();
        });
    }

    private ParameterView BuildParameterView(RenderFragment? childContent)
    {
        _parameters.Clear();
        WriteParameters(_parameters);

        if (childContent is not null)
        {
            _parameters["ChildContent"] = childContent;
        }

        return ParameterView.FromDictionary(_parameters);
    }

    /// <summary>
    ///     Renders this island's Rask children to markup the hosted component can place.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         The children stay Rask's: their handlers are ordinary Rask handlers, delegated from
    ///         <c>document</c> on <c>data-rask-on-*</c>, so they keep working inside a statically
    ///         rendered island. That is strictly better than the islands feature, whose slot content
    ///         is placed once at mount and then goes dead — here the island re-serializes on every
    ///         change, so handler ids stay stable and live.
    ///     </para>
    ///     <para>
    ///         <c>ToHtml()</c> is re-entrant against an in-progress render by design; it is already
    ///         how every head-asset contribution is produced during the walk, and it saves and
    ///         restores the head sentinel for exactly that reason (#627).
    ///     </para>
    /// </remarks>
    private RenderFragment? CaptureChildren()
    {
        if (Children is null)
        {
            return null;
        }

        var html = new System.Text.StringBuilder();
        foreach (var child in Children)
        {
            if (child is not null)
            {
                html.Append(child.ToHtml());
            }
        }

        if (html.Length == 0)
        {
            return null;
        }

        var markup = html.ToString();
        return builder => builder.AddMarkupContent(0, markup);
    }
}
