using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using Rask.Core;
using Rask.Core.Components;
using Rask.Core.Live;

namespace Rask.Blazor;

/// <summary>
///     A Rask component whose markup is produced by a real Blazor component.
/// </summary>
/// <typeparam name="TComponent">
///     The hosted component — your Razor Class Library's type, or one from a package such as
///     MudBlazor. It is named as a type argument rather than inferred from a sibling file because
///     that is the one place it cannot drift from what actually renders, and because the common case
///     has no file in your project at all: the type comes from a reference.
/// </typeparam>
/// <remarks>
///     <para>
///         The Razor SDK compiles <c>.razor</c> exactly as it always has — this package neither
///         replaces nor configures it. What it does is render the resulting component server-side and
///         place its HTML in the page, with parameters passed as live C# objects rather than
///         serialized, so any type the hosted parameter accepts crosses intact.
///     </para>
///     <para>
///         The hosted component must live in a REFERENCED project or package for its parameters to be
///         checked at compile time. A <c>.razor</c> in the same project as the island is generated by
///         the Razor source generator, and one source generator cannot see another's output, so
///         Rask's generator cannot resolve its parameters — that still works, but unverified, and
///         says so through RASK066.
///     </para>
///     <para>
///         Because the hosted type is a type argument, a component that already extends something
///         else cannot host one. That is deliberate and matches the islands feature: chrome in Rask
///         comes from the chain, not from inheritance, so the answer is to compose —
///         <c>BsCard[ Chart.Series(points) ]</c> — rather than to inherit both.
///     </para>
/// </remarks>
public abstract partial class BlazorComponent<TComponent> : Component
    where TComponent : IComponent, new()
{
    private BlazorIslandRenderer? _renderer;
    private TComponent? _instance;
    private int _componentId = -1;
    private string? _html;

    // Refilled rather than reallocated per render. Not the render hot path — this runs from an async
    // lifecycle hook, not the serialize walk — but the habit is the repo's.
    private readonly Dictionary<string, object?> _parameters = new(StringComparer.Ordinal);

    /// <summary>How much of the hosted component's own behaviour reaches the browser.</summary>
    /// <remarks>
    ///     Nullable rather than a property with an initializer, and that is not a style choice. A
    ///     member initializer compiles into the constructor and leaves no trace in metadata, so across
    ///     an assembly boundary <c>Interactivity { get; set; } = Static</c> is indistinguishable from
    ///     <c>Interactivity { get; set; }</c> — the chain would read it as a REQUIRED step and force
    ///     every call site to spell out a value that has an obvious default. Nullability survives
    ///     metadata, and says the more precise thing: null is "not specified".
    /// </remarks>
    public BlazorInteractivity? Interactivity { get; set; }

    /// <summary>The name this island is identified by. Its own simple type name.</summary>
    protected virtual string ComponentName => GetType().Name;

    /// <summary>
    ///     Fills <paramref name="into" /> with the hosted component's parameters. Generated.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Reflection-free by construction: every name and every read is decided at compile time,
    ///         and <see cref="ParameterView.FromDictionary" /> takes exactly this shape.
    ///     </para>
    ///     <para>
    ///         A nullable property that is null OMITS its key rather than writing null — the opposite
    ///         of what the islands feature does, and deliberately so. There, JSON <c>null</c> and an
    ///         absent key are different facts to TypeScript. Here <see cref="ParameterView" /> is
    ///         authoritative: any key it carries OVERWRITES the hosted component's own default, so
    ///         writing <c>Width = null</c> would clobber a default the component meant to keep.
    ///     </para>
    /// </remarks>
    protected abstract void WriteParameters(Dictionary<string, object?> into);

    /// <summary>Creates the hosted component. Never reflective — the type argument is known.</summary>
    protected virtual TComponent Create() => new();

    /// <summary>
    ///     Mounts the hosted component and re-renders it whenever a Rask prop changes.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Everything lives here rather than being split with <c>OnMountAsync</c>, because Rask
    ///         fires this hook when <c>firstRender || propsChanged</c> — mount and update are already
    ///         one code path, so splitting them would only add a first-render special case to get
    ///         wrong.
    ///     </para>
    ///     <para>
    ///         Being async is what puts the island in the FIRST response: the returned task is
    ///         registered in the ambient quiescence scope, so Rask renders, waits for this, and
    ///         renders again — and the response carries the second wave. A hosted component that
    ///         awaits in <c>OnInitializedAsync</c> is therefore complete in the delivered HTML rather
    ///         than appearing a frame later.
    ///     </para>
    /// </remarks>
    protected override async Task OnPropsChangedAsync()
    {
        var renderer = _renderer ??= CreateRenderer();

        // Children are consumed as the hosted component's ChildContent, so they are read here —
        // before the serialize walk — and never emitted by Rask itself.
        var childMarkup = CaptureChildren();

        // Captured on THIS thread. The render below hops to the renderer's dispatcher, and the
        // ambient context is thread-static, so it would be gone by the time handlers are registered.
        var context = LiveRenderContext.Current ?? LiveRenderContext.CurrentSync;

        await renderer.Dispatcher.InvokeAsync(async () =>
        {
            if (_componentId < 0)
            {
                _instance = Create();
                _componentId = renderer.Attach(_instance);
            }

            await renderer.RenderAsync(_componentId, BuildParameterView(childMarkup));
            _html = BlazorFrameWriter.Write(renderer, _componentId, (blazorId, _) => Bridge(context, renderer, blazorId));
        });
    }

    /// <summary>
    ///     Registers one of the hosted component's event handlers as an ordinary Rask handler.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         This is what makes a hosted component's own <c>@onclick</c> work with no Blazor
    ///         circuit. Blazor assigns the handler an id during the static render; we hand that id a
    ///         Rask handler id, the browser's existing delegated listener sends it over the socket
    ///         that is already open, and it comes back here to be dispatched into Blazor. The same
    ///         contract the React and Lit islands use, over the same channel.
    ///     </para>
    ///     <para>
    ///         Returns null when there is no live session, so no attribute is written at all — an
    ///         inert island is better than markup advertising a handler that cannot be delivered.
    ///     </para>
    /// </remarks>
    private string? Bridge(LiveRenderContext? context, BlazorIslandRenderer renderer, ulong blazorHandlerId)
    {
        if (context is null)
        {
            return null;
        }

        Func<Task> handler = () => renderer.Dispatcher.InvokeAsync(
            () => renderer.DispatchAsync(blazorHandlerId, EventArgsFor(renderer, blazorHandlerId)));

        // RegisterHandlerFor, never owner.RegisterHandler: that overload treats its receiver as the
        // render ROOT and restarts the id sequence at zero, so the handler would collide with the
        // page's own and silently never fire.
        return context.RegisterHandlerFor(this, handler);
    }

    private static EventArgs EventArgsFor(BlazorIslandRenderer renderer, ulong handlerId)
    {
        // Blazor knows what each handler expects. A component reading e.ClientX would otherwise get a
        // bare EventArgs and cast-fail at the worst moment.
        try
        {
            var type = renderer.ArgsTypeFor(handlerId);
            return type == typeof(EventArgs)
                ? EventArgs.Empty
                : (EventArgs)Activator.CreateInstance(type)!;
        }
        catch (Exception)
        {
            return EventArgs.Empty;
        }
    }

    /// <summary>Releases the hosted component and its renderer.</summary>
    /// <remarks>
    ///     Asynchronous on purpose: a <see cref="IDisposable.Dispose" /> while a render is in flight
    ///     on the renderer's dispatcher is a hang, not a leak.
    /// </remarks>
    protected override async Task OnUnmountAsync()
    {
        if (_renderer is null)
        {
            return;
        }

        if (_componentId >= 0)
        {
            await _renderer.Dispatcher.InvokeAsync(() => _renderer.Detach(_componentId));
            _componentId = -1;
        }

        await _renderer.DisposeAsync();
        _renderer = null;
        _instance = default;
    }

    /// <inheritdoc />
    protected sealed override Component? Render() =>
        BlazorHost
            .Opaque(Interactivity == BlazorInteractivity.Circuit)
            .Data(new Dictionary<string, string?> { ["rask-blazor"] = ComponentName })
            .Attributes(new Dictionary<string, string?>
            {
                [BlazorDefaults.NameAttribute] = ComponentName,
                [BlazorDefaults.ComponentAttribute] = typeof(TComponent).FullName,
            })[
            _html is null ? null : Raw.Value(_html)
        ];

    private BlazorIslandRenderer CreateRenderer()
    {
        var services = LiveRenderContext.Current?.Services
                       ?? LiveRenderContext.CurrentSync?.Services
                       ?? throw new InvalidOperationException(
                           $"'{GetType().Name}' hosts the Blazor component '{typeof(TComponent).Name}', which needs the "
                           + "application's services to render. Rask could not find them for this render. Call "
                           + "'services.AddRaskBlazor()' in Program.cs.");

        var logs = services.GetService<ILoggerFactory>() ?? NullLoggerFactory.Instance;

        // A render the hosted component asked for itself (a timer, an injected service's event) has
        // nowhere to go without a live session, so say so as well as repainting.
        return new BlazorIslandRenderer(services, logs, () =>
        {
            LiveRenderContext.Current?.MarkRequiresLiveSession(InteractivityReason.Declared);
            StateHasChanged();
        });
    }

    private ParameterView BuildParameterView(RenderFragment? childContent)
    {
        _parameters.Clear();
        WriteParameters(_parameters);

        if (childContent is not null)
        {
            _parameters["ChildContent"] = childContent;
        }

        return ParameterView.FromDictionary(_parameters);
    }

    /// <summary>
    ///     Renders this island's Rask children to markup the hosted component can place.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         The children stay Rask's: their handlers are ordinary Rask handlers, delegated from
    ///         <c>document</c> on <c>data-rask-on-*</c>, so they keep working inside a statically
    ///         rendered island. That is strictly better than the islands feature, whose slot content
    ///         is placed once at mount and then goes dead — here the island re-serializes on every
    ///         change, so handler ids stay stable and live.
    ///     </para>
    ///     <para>
    ///         <c>ToHtml()</c> is re-entrant against an in-progress render by design; it is already
    ///         how every head-asset contribution is produced during the walk, and it saves and
    ///         restores the head sentinel for exactly that reason (#627).
    ///     </para>
    /// </remarks>
    private RenderFragment? CaptureChildren()
    {
        if (Children is null)
        {
            return null;
        }

        var html = new System.Text.StringBuilder();
        foreach (var child in Children)
        {
            if (child is not null)
            {
                html.Append(child.ToHtml());
            }
        }

        if (html.Length == 0)
        {
            return null;
        }

        var markup = html.ToString();
        return builder => builder.AddMarkupContent(0, markup);
    }
}
