<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Rask.Core\Rask.Core.csproj"/>
    <ProjectReference Include="..\..\src\Rask.Server\Rask.Server.csproj"/>
    <ProjectReference Include="..\..\src\Rask.Generators\Rask.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

  <!-- The ASP.NET Web SDK requires a wwwroot to exist even when there are no static files. -->
  <Target Name="EnsureEmptyWwwroot" BeforeTargets="BeforeBuild">
    <MakeDir Directories="wwwroot"/>
  </Target>

</Project>
