using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Rask.Generators.Analyzers;

namespace Rask.Generators.Tests;

public class ComponentConstructionAnalyzerTests
{
    [Fact]
    public async Task NewBuiltInTag_ReportsRask014()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var x = new Div(); }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
        Assert.Contains("Div", d.GetMessage());
    }

    [Fact]
    public async Task NewUserComponent_ReportsRask014()
    {
        var src = """
                  using Rask.Core;
                  namespace Demo;
                  public sealed class Counter : Component
                  {
                      public override RenderResult Render() => this;
                  }
                  class Caller { void M() { var x = new Counter(); } }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
    }

    [Fact]
    public async Task TargetTypedNewComponent_ReportsRask014()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      Div M() { Div d = new(); return d; }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
    }

    [Fact]
    public async Task ComponentSubclassDeclaration_NoDiagnostic()
    {
        var src = """
                  using Rask.Core;
                  namespace Demo;
                  public sealed class Counter : Component
                  {
                      public override RenderResult Render() => this;
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task NewInsideAutoGeneratedFile_NoDiagnostic()
    {
        var src = """
                  // <auto-generated/>
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var x = new Div(); }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task NewInRaskCoreAssembly_NoDiagnostic()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var x = new Div(); }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src, "Rask.Core");

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task NewInsideUserRenderOverride_ReportsRask014()
    {
        var src = """
                  using Rask.Core;
                  using Rask.Core.Components;
                  namespace Demo;
                  public sealed class Page : Component
                  {
                      protected override RenderResult Render() => new Div();
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
    }

    [Fact]
    public async Task NewInsideArrayInitializer_ReportsRask014ForEachElement()
    {
        var src = """
                  using Rask.Core.Components;
                  class C
                  {
                      void M() { var arr = new[] { new Div(), new Span() }; }
                  }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        // The implicit `new[]` is not a Component (array creation), so only the
        // two inner Component constructors should be flagged.
        Assert.Equal(2, diagnostics.Length);
        Assert.All(diagnostics, d => Assert.Equal("RASK014", d.Id));
    }

    [Fact]
    public async Task NewInternalUserComponent_ReportsRask014()
    {
        var src = """
                  using Rask.Core;
                  namespace Demo;
                  internal sealed class Hidden : Component
                  {
                      public override RenderResult Render() => this;
                  }
                  class Caller { void M() { var x = new Hidden(); } }
                  """;

        var diagnostics = await GetDiagnosticsAsync(src);

        var d = Assert.Single(diagnostics);
        Assert.Equal("RASK014", d.Id);
    }

    private static async Task<ImmutableArray<Diagnostic>> GetDiagnosticsAsync(string source,
        string assemblyName = "TestAssembly")
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source, new CSharpParseOptions(LanguageVersion.Latest));
        var references = GeneratorDriverFixture.BuildReferences();
        var compilation = CSharpCompilation.Create(
            assemblyName,
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));

        var analyzers = ImmutableArray.Create<DiagnosticAnalyzer>(new ComponentConstructionAnalyzer());
        var withAnalyzers = compilation.WithAnalyzers(analyzers);
        var all = await withAnalyzers.GetAnalyzerDiagnosticsAsync();
        return all.Where(d => d.Id == "RASK014").ToImmutableArray();
    }
}
