using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Rask.Generators.External;
using Rask.Generators.Validation;

namespace Rask.Generators.Tests;

/// <summary>
/// The generators in this assembly meeting a Rask.Data entity's generated <c>{Entity}Model</c>, which they
/// cannot see.
/// </summary>
/// <remarks>
/// <para>
/// In the compilation that declares <c>Product</c>, <c>ProductModel</c> is generated by the model generator
/// and is an unresolved error type to every other generator. An error type displays as the bare name its
/// author wrote, which does not bind from generated code in another namespace, and has no members.
/// </para>
/// <para>
/// Rask.Data, FluentValidation and the Rask integration are STUBBED by name here rather than referenced:
/// both generators match them by metadata name, and pulling EF Core into every compilation this suite
/// creates would cost every test for the sake of two. The model generator lives in the batteries
/// assembly, so the combined compile of its output with a consumer's is covered there
/// (<c>GeneratedModelAcrossGeneratorsTests</c>); these assert the emitted names.
/// </para>
/// </remarks>
public class GeneratedModelReferenceTests
{
    private const string Stubs = """
        namespace Rask.Data
        {
            public abstract class Model { }
            public abstract class Model<TId> : Model { public TId Id { get; protected set; } = default!; }
        }
        namespace FluentValidation
        {
            public abstract class AbstractValidator<T> { }
        }
        namespace Rask.Validation.FluentValidation
        {
            public static class RaskValidators { }
        }
        namespace Shop
        {
            public sealed class Product : Rask.Data.Model<System.Guid>
            {
                private Product() { }
                public string Name { get; private set; } = "";
            }
        }
        """;

    [Fact]
    public void A_validator_of_a_generated_model_registers_it_under_its_full_name()
    {
        var run = GeneratorDriverFixture.Run(
            [
                ("/proj/Stubs.cs", Stubs),
                ("/proj/ProductValidator.cs", """
                    namespace Shop.Validation
                    {
                        public sealed class ProductValidator : FluentValidation.AbstractValidator<ProductModel> { }
                    }
                    """),
            ],
            [new ValidatorRegistryGenerator()]);

        var registry = run.GeneratedSource("__RaskValidatorRegistry");
        Assert.Contains(
            "(typeof(global::Shop.ProductModel), static __sp => new global::Shop.Validation.ProductValidator()),",
            registry,
            StringComparison.Ordinal);
        Assert.DoesNotContain("typeof(ProductModel)", registry, StringComparison.Ordinal);
    }

    [Fact]
    public void Two_validators_naming_the_generated_model_two_ways_are_RASKVAL001()
    {
        // Keyed by the bare display name, `ProductModel` and `Shop.ProductModel` were two different models,
        // and both validators were registered for the one type — the RASKVAL001 case, silently.
        var run = GeneratorDriverFixture.Run(
            [
                ("/proj/Stubs.cs", Stubs),
                ("/proj/Validators.cs", """
                    namespace Shop
                    {
                        public sealed class ProductValidator : FluentValidation.AbstractValidator<ProductModel> { }
                    }
                    namespace Other
                    {
                        public sealed class StricterProductValidator : FluentValidation.AbstractValidator<Shop.ProductModel> { }
                    }
                    """),
            ],
            [new ValidatorRegistryGenerator()]);

        Assert.Contains(run.Diagnostics, d => d.Id == "RASKVAL001");
    }

    [Fact]
    public void A_component_prop_typed_as_a_generated_model_is_declared_by_its_full_name()
    {
        // The bare name binds in the author's file (it has the using) and not in the generated setters (they
        // do not). The combined compile with the model generator's real output lives in the batteries suite.
        var run = BuilderGeneratorHarness.Run("""
            using Rask.Core;
            namespace Rask.Data
            {
                public abstract class Model { }
                public abstract class Model<TId> : Model { public TId Id { get; protected set; } = default!; }
            }
            namespace Shop.Catalog
            {
                public sealed class Product : Rask.Data.Model<int>
                {
                    private Product() { }
                    public string Name { get; private set; } = "";
                }
            }
            namespace Shop.Pages
            {
                using Shop.Catalog;
                public partial class Layout : Component { }
                public partial class EditProduct : Component
                {
                    public ProductModel Edited { get; set; } = null!;
                    public ProductModel? Draft { get; set; }
                    public System.Collections.Generic.List<ProductModel>? Related { get; set; }
                    public Callback<ProductModel> OnSave { get; set; }
                }
            }
            """);

        var setters = run.Source("RaskBuilderSetters");
        Assert.Contains("global::Shop.Catalog.ProductModel? value)", setters, StringComparison.Ordinal);
        Assert.Contains(
            "global::System.Collections.Generic.List<global::Shop.Catalog.ProductModel>? value)",
            setters,
            StringComparison.Ordinal);
        Assert.Contains("global::System.Action<global::Shop.Catalog.ProductModel>? value)", setters, StringComparison.Ordinal);
        Assert.DoesNotContain("<ProductModel", setters, StringComparison.Ordinal);
        Assert.DoesNotContain(" ProductModel", setters, StringComparison.Ordinal);
        Assert.DoesNotContain(" ProductModel", run.Source("RaskBuilderEntryHost"), StringComparison.Ordinal);
    }

    [Fact]
    public void An_island_prop_typed_as_a_generated_model_is_encoded_from_the_entity()
    {
        var run = GeneratorDriverFixture.Run(
            [
                ("/proj/Stubs.cs", Stubs),
                ("/proj/ProductCard.cs", """
                    namespace Shop.Islands
                    {
                        public sealed partial class ProductCard : Rask.External.ReactComponent
                        {
                            public ProductModel? Product { get; set; }
                        }
                    }
                    """),
            ],
            [new ExternalGenerator()]);

        Assert.DoesNotContain(run.Diagnostics, d => d.Id == "RASK057");

        var island = run.GeneratedSource("ProductCard.External");
        Assert.Contains("writer, global::Shop.ProductModel value)", island, StringComparison.Ordinal);
        // The generated model carries no key, so neither does what is sent of it.
        Assert.DoesNotContain("writer.WritePropertyName(\"id\");", island, StringComparison.Ordinal);
        Assert.Contains("writer.WritePropertyName(\"name\");", island, StringComparison.Ordinal);

        var typeScript = run.GeneratedSource("RaskExternalGeneratedTypeScript");
        Assert.Contains("export interface ProductModel {", typeScript, StringComparison.Ordinal);
        Assert.Contains("product: ProductModel | null;", typeScript, StringComparison.Ordinal);

        // The writer has to BIND, which text cannot show: `ProductModel?` is Nullable<ProductModel> to a
        // generator, and was once emitted as `ProductModel?<global::Shop.ProductModel>`. The model generator is
        // not in this assembly, so a stand-in with the generated model's members plays its part.
        var standIn = CSharpSyntaxTree.ParseText(
            """
            namespace Shop
            {
                public sealed partial class ProductModel
                {
                    public string Name { get; set; } = "";
                }
            }
            """,
            new CSharpParseOptions(LanguageVersion.Latest),
            "/proj/ProductModel.g.cs");
        var generated = run.RunResult.Results
            .SelectMany(r => r.GeneratedSources)
            .Select(s => CSharpSyntaxTree.ParseText(s.SourceText, new CSharpParseOptions(LanguageVersion.Latest), s.HintName));

        Assert.Empty(run.Compilation
            .AddSyntaxTrees(generated.Append(standIn))
            .GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error));
    }
}
