<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentValidation" Version="12.1.1"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1"/>
    <PackageReference Include="xunit" Version="2.9.3"/>
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
    <Using Include="Rask.Core.Components"/>
    <Using Include="Rask.Core.Components.Generated" Static="true"/>
    <Using Include="Rask.Validation.FluentValidation"/>
    <Using Include="Rask.Validation.FluentValidation.Generated" Static="true"/>
    <Using Include="Rask.TestSupport"/>
    <Using Include="Rask.Validation.FluentValidation.Tests.ValidationTestSupport" Static="true"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rask.Core\Rask.Core.csproj"/>
    <ProjectReference Include="..\Rask.Validation.FluentValidation\Rask.Validation.FluentValidation.csproj"/>
    <ProjectReference Include="..\Rask.TestSupport\Rask.TestSupport.csproj"/>
    <ProjectReference Include="..\Rask.Generators\Rask.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

</Project>
