// <auto-generated />
// Generated by scripts/flux/icons.mjs from heroicons 2.2.0 (https://registry.npmjs.org/heroicons/-/heroicons-2.2.0.tgz).
// Heroicons is MIT-licensed, Copyright (c) Tailwind Labs, Inc. — https://github.com/tailwindlabs/heroicons
// Do not edit: change the script and run it again.
#nullable enable

namespace Rask;

public static partial class Ui
{
    /// <summary>
    ///     Every icon <see cref="UiIcon" /> draws: the whole of <see href="https://heroicons.com">Heroicons</see> 2.2.0
    ///     under Heroicons' own names (<c>arrow-down-tray</c> is <see cref="ArrowDownTray" />), plus Flux's
    ///     <see cref="Loading" /> spinner. Each comes in the four <see cref="IconVariant" />s.
    /// </summary>
    public enum IconName
    {
        /// <summary>Heroicons' <c>academic-cap</c>.</summary>
        AcademicCap,

        /// <summary>Heroicons' <c>adjustments-horizontal</c>.</summary>
        AdjustmentsHorizontal,

        /// <summary>Heroicons' <c>adjustments-vertical</c>.</summary>
        AdjustmentsVertical,

        /// <summary>Heroicons' <c>archive-box</c>.</summary>
        ArchiveBox,

        /// <summary>Heroicons' <c>archive-box-arrow-down</c>.</summary>
        ArchiveBoxArrowDown,

        /// <summary>Heroicons' <c>archive-box-x-mark</c>.</summary>
        ArchiveBoxXMark,

        /// <summary>Heroicons' <c>arrow-down</c>.</summary>
        ArrowDown,

        /// <summary>Heroicons' <c>arrow-down-circle</c>.</summary>
        ArrowDownCircle,

        /// <summary>Heroicons' <c>arrow-down-left</c>.</summary>
        ArrowDownLeft,

        /// <summary>Heroicons' <c>arrow-down-on-square</c>.</summary>
        ArrowDownOnSquare,

        /// <summary>Heroicons' <c>arrow-down-on-square-stack</c>.</summary>
        ArrowDownOnSquareStack,

        /// <summary>Heroicons' <c>arrow-down-right</c>.</summary>
        ArrowDownRight,

        /// <summary>Heroicons' <c>arrow-down-tray</c>.</summary>
        ArrowDownTray,

        /// <summary>Heroicons' <c>arrow-left</c>.</summary>
        ArrowLeft,

        /// <summary>Heroicons' <c>arrow-left-circle</c>.</summary>
        ArrowLeftCircle,

        /// <summary>Heroicons' <c>arrow-left-end-on-rectangle</c>.</summary>
        ArrowLeftEndOnRectangle,

        /// <summary>Heroicons' <c>arrow-left-start-on-rectangle</c>.</summary>
        ArrowLeftStartOnRectangle,

        /// <summary>Heroicons' <c>arrow-long-down</c>.</summary>
        ArrowLongDown,

        /// <summary>Heroicons' <c>arrow-long-left</c>.</summary>
        ArrowLongLeft,

        /// <summary>Heroicons' <c>arrow-long-right</c>.</summary>
        ArrowLongRight,

        /// <summary>Heroicons' <c>arrow-long-up</c>.</summary>
        ArrowLongUp,

        /// <summary>Heroicons' <c>arrow-path</c>.</summary>
        ArrowPath,

        /// <summary>Heroicons' <c>arrow-path-rounded-square</c>.</summary>
        ArrowPathRoundedSquare,

        /// <summary>Heroicons' <c>arrow-right</c>.</summary>
        ArrowRight,

        /// <summary>Heroicons' <c>arrow-right-circle</c>.</summary>
        ArrowRightCircle,

        /// <summary>Heroicons' <c>arrow-right-end-on-rectangle</c>.</summary>
        ArrowRightEndOnRectangle,

        /// <summary>Heroicons' <c>arrow-right-start-on-rectangle</c>.</summary>
        ArrowRightStartOnRectangle,

        /// <summary>Heroicons' <c>arrow-top-right-on-square</c>.</summary>
        ArrowTopRightOnSquare,

        /// <summary>Heroicons' <c>arrow-trending-down</c>.</summary>
        ArrowTrendingDown,

        /// <summary>Heroicons' <c>arrow-trending-up</c>.</summary>
        ArrowTrendingUp,

        /// <summary>Heroicons' <c>arrow-turn-down-left</c>.</summary>
        ArrowTurnDownLeft,

        /// <summary>Heroicons' <c>arrow-turn-down-right</c>.</summary>
        ArrowTurnDownRight,

        /// <summary>Heroicons' <c>arrow-turn-left-down</c>.</summary>
        ArrowTurnLeftDown,

        /// <summary>Heroicons' <c>arrow-turn-left-up</c>.</summary>
        ArrowTurnLeftUp,

        /// <summary>Heroicons' <c>arrow-turn-right-down</c>.</summary>
        ArrowTurnRightDown,

        /// <summary>Heroicons' <c>arrow-turn-right-up</c>.</summary>
        ArrowTurnRightUp,

        /// <summary>Heroicons' <c>arrow-turn-up-left</c>.</summary>
        ArrowTurnUpLeft,

        /// <summary>Heroicons' <c>arrow-turn-up-right</c>.</summary>
        ArrowTurnUpRight,

        /// <summary>Heroicons' <c>arrow-up</c>.</summary>
        ArrowUp,

        /// <summary>Heroicons' <c>arrow-up-circle</c>.</summary>
        ArrowUpCircle,

        /// <summary>Heroicons' <c>arrow-up-left</c>.</summary>
        ArrowUpLeft,

        /// <summary>Heroicons' <c>arrow-up-on-square</c>.</summary>
        ArrowUpOnSquare,

        /// <summary>Heroicons' <c>arrow-up-on-square-stack</c>.</summary>
        ArrowUpOnSquareStack,

        /// <summary>Heroicons' <c>arrow-up-right</c>.</summary>
        ArrowUpRight,

        /// <summary>Heroicons' <c>arrow-up-tray</c>.</summary>
        ArrowUpTray,

        /// <summary>Heroicons' <c>arrow-uturn-down</c>.</summary>
        ArrowUturnDown,

        /// <summary>Heroicons' <c>arrow-uturn-left</c>.</summary>
        ArrowUturnLeft,

        /// <summary>Heroicons' <c>arrow-uturn-right</c>.</summary>
        ArrowUturnRight,

        /// <summary>Heroicons' <c>arrow-uturn-up</c>.</summary>
        ArrowUturnUp,

        /// <summary>Heroicons' <c>arrows-pointing-in</c>.</summary>
        ArrowsPointingIn,

        /// <summary>Heroicons' <c>arrows-pointing-out</c>.</summary>
        ArrowsPointingOut,

        /// <summary>Heroicons' <c>arrows-right-left</c>.</summary>
        ArrowsRightLeft,

        /// <summary>Heroicons' <c>arrows-up-down</c>.</summary>
        ArrowsUpDown,

        /// <summary>Heroicons' <c>at-symbol</c>.</summary>
        AtSymbol,

        /// <summary>Heroicons' <c>backspace</c>.</summary>
        Backspace,

        /// <summary>Heroicons' <c>backward</c>.</summary>
        Backward,

        /// <summary>Heroicons' <c>banknotes</c>.</summary>
        Banknotes,

        /// <summary>Heroicons' <c>bars-2</c>.</summary>
        Bars2,

        /// <summary>Heroicons' <c>bars-3</c>.</summary>
        Bars3,

        /// <summary>Heroicons' <c>bars-3-bottom-left</c>.</summary>
        Bars3BottomLeft,

        /// <summary>Heroicons' <c>bars-3-bottom-right</c>.</summary>
        Bars3BottomRight,

        /// <summary>Heroicons' <c>bars-3-center-left</c>.</summary>
        Bars3CenterLeft,

        /// <summary>Heroicons' <c>bars-4</c>.</summary>
        Bars4,

        /// <summary>Heroicons' <c>bars-arrow-down</c>.</summary>
        BarsArrowDown,

        /// <summary>Heroicons' <c>bars-arrow-up</c>.</summary>
        BarsArrowUp,

        /// <summary>Heroicons' <c>battery-0</c>.</summary>
        Battery0,

        /// <summary>Heroicons' <c>battery-100</c>.</summary>
        Battery100,

        /// <summary>Heroicons' <c>battery-50</c>.</summary>
        Battery50,

        /// <summary>Heroicons' <c>beaker</c>.</summary>
        Beaker,

        /// <summary>Heroicons' <c>bell</c>.</summary>
        Bell,

        /// <summary>Heroicons' <c>bell-alert</c>.</summary>
        BellAlert,

        /// <summary>Heroicons' <c>bell-slash</c>.</summary>
        BellSlash,

        /// <summary>Heroicons' <c>bell-snooze</c>.</summary>
        BellSnooze,

        /// <summary>Heroicons' <c>bold</c>.</summary>
        Bold,

        /// <summary>Heroicons' <c>bolt</c>.</summary>
        Bolt,

        /// <summary>Heroicons' <c>bolt-slash</c>.</summary>
        BoltSlash,

        /// <summary>Heroicons' <c>book-open</c>.</summary>
        BookOpen,

        /// <summary>Heroicons' <c>bookmark</c>.</summary>
        Bookmark,

        /// <summary>Heroicons' <c>bookmark-slash</c>.</summary>
        BookmarkSlash,

        /// <summary>Heroicons' <c>bookmark-square</c>.</summary>
        BookmarkSquare,

        /// <summary>Heroicons' <c>briefcase</c>.</summary>
        Briefcase,

        /// <summary>Heroicons' <c>bug-ant</c>.</summary>
        BugAnt,

        /// <summary>Heroicons' <c>building-library</c>.</summary>
        BuildingLibrary,

        /// <summary>Heroicons' <c>building-office</c>.</summary>
        BuildingOffice,

        /// <summary>Heroicons' <c>building-office-2</c>.</summary>
        BuildingOffice2,

        /// <summary>Heroicons' <c>building-storefront</c>.</summary>
        BuildingStorefront,

        /// <summary>Heroicons' <c>cake</c>.</summary>
        Cake,

        /// <summary>Heroicons' <c>calculator</c>.</summary>
        Calculator,

        /// <summary>Heroicons' <c>calendar</c>.</summary>
        Calendar,

        /// <summary>Heroicons' <c>calendar-date-range</c>.</summary>
        CalendarDateRange,

        /// <summary>Heroicons' <c>calendar-days</c>.</summary>
        CalendarDays,

        /// <summary>Heroicons' <c>camera</c>.</summary>
        Camera,

        /// <summary>Heroicons' <c>chart-bar</c>.</summary>
        ChartBar,

        /// <summary>Heroicons' <c>chart-bar-square</c>.</summary>
        ChartBarSquare,

        /// <summary>Heroicons' <c>chart-pie</c>.</summary>
        ChartPie,

        /// <summary>Heroicons' <c>chat-bubble-bottom-center</c>.</summary>
        ChatBubbleBottomCenter,

        /// <summary>Heroicons' <c>chat-bubble-bottom-center-text</c>.</summary>
        ChatBubbleBottomCenterText,

        /// <summary>Heroicons' <c>chat-bubble-left</c>.</summary>
        ChatBubbleLeft,

        /// <summary>Heroicons' <c>chat-bubble-left-ellipsis</c>.</summary>
        ChatBubbleLeftEllipsis,

        /// <summary>Heroicons' <c>chat-bubble-left-right</c>.</summary>
        ChatBubbleLeftRight,

        /// <summary>Heroicons' <c>chat-bubble-oval-left</c>.</summary>
        ChatBubbleOvalLeft,

        /// <summary>Heroicons' <c>chat-bubble-oval-left-ellipsis</c>.</summary>
        ChatBubbleOvalLeftEllipsis,

        /// <summary>Heroicons' <c>check</c>.</summary>
        Check,

        /// <summary>Heroicons' <c>check-badge</c>.</summary>
        CheckBadge,

        /// <summary>Heroicons' <c>check-circle</c>.</summary>
        CheckCircle,

        /// <summary>Heroicons' <c>chevron-double-down</c>.</summary>
        ChevronDoubleDown,

        /// <summary>Heroicons' <c>chevron-double-left</c>.</summary>
        ChevronDoubleLeft,

        /// <summary>Heroicons' <c>chevron-double-right</c>.</summary>
        ChevronDoubleRight,

        /// <summary>Heroicons' <c>chevron-double-up</c>.</summary>
        ChevronDoubleUp,

        /// <summary>Heroicons' <c>chevron-down</c>.</summary>
        ChevronDown,

        /// <summary>Heroicons' <c>chevron-left</c>.</summary>
        ChevronLeft,

        /// <summary>Heroicons' <c>chevron-right</c>.</summary>
        ChevronRight,

        /// <summary>Heroicons' <c>chevron-up</c>.</summary>
        ChevronUp,

        /// <summary>Heroicons' <c>chevron-up-down</c>.</summary>
        ChevronUpDown,

        /// <summary>Heroicons' <c>circle-stack</c>.</summary>
        CircleStack,

        /// <summary>Heroicons' <c>clipboard</c>.</summary>
        Clipboard,

        /// <summary>Heroicons' <c>clipboard-document</c>.</summary>
        ClipboardDocument,

        /// <summary>Heroicons' <c>clipboard-document-check</c>.</summary>
        ClipboardDocumentCheck,

        /// <summary>Heroicons' <c>clipboard-document-list</c>.</summary>
        ClipboardDocumentList,

        /// <summary>Heroicons' <c>clock</c>.</summary>
        Clock,

        /// <summary>Heroicons' <c>cloud</c>.</summary>
        Cloud,

        /// <summary>Heroicons' <c>cloud-arrow-down</c>.</summary>
        CloudArrowDown,

        /// <summary>Heroicons' <c>cloud-arrow-up</c>.</summary>
        CloudArrowUp,

        /// <summary>Heroicons' <c>code-bracket</c>.</summary>
        CodeBracket,

        /// <summary>Heroicons' <c>code-bracket-square</c>.</summary>
        CodeBracketSquare,

        /// <summary>Heroicons' <c>cog</c>.</summary>
        Cog,

        /// <summary>Heroicons' <c>cog-6-tooth</c>.</summary>
        Cog6Tooth,

        /// <summary>Heroicons' <c>cog-8-tooth</c>.</summary>
        Cog8Tooth,

        /// <summary>Heroicons' <c>command-line</c>.</summary>
        CommandLine,

        /// <summary>Heroicons' <c>computer-desktop</c>.</summary>
        ComputerDesktop,

        /// <summary>Heroicons' <c>cpu-chip</c>.</summary>
        CpuChip,

        /// <summary>Heroicons' <c>credit-card</c>.</summary>
        CreditCard,

        /// <summary>Heroicons' <c>cube</c>.</summary>
        Cube,

        /// <summary>Heroicons' <c>cube-transparent</c>.</summary>
        CubeTransparent,

        /// <summary>Heroicons' <c>currency-bangladeshi</c>.</summary>
        CurrencyBangladeshi,

        /// <summary>Heroicons' <c>currency-dollar</c>.</summary>
        CurrencyDollar,

        /// <summary>Heroicons' <c>currency-euro</c>.</summary>
        CurrencyEuro,

        /// <summary>Heroicons' <c>currency-pound</c>.</summary>
        CurrencyPound,

        /// <summary>Heroicons' <c>currency-rupee</c>.</summary>
        CurrencyRupee,

        /// <summary>Heroicons' <c>currency-yen</c>.</summary>
        CurrencyYen,

        /// <summary>Heroicons' <c>cursor-arrow-rays</c>.</summary>
        CursorArrowRays,

        /// <summary>Heroicons' <c>cursor-arrow-ripple</c>.</summary>
        CursorArrowRipple,

        /// <summary>Heroicons' <c>device-phone-mobile</c>.</summary>
        DevicePhoneMobile,

        /// <summary>Heroicons' <c>device-tablet</c>.</summary>
        DeviceTablet,

        /// <summary>Heroicons' <c>divide</c>.</summary>
        Divide,

        /// <summary>Heroicons' <c>document</c>.</summary>
        Document,

        /// <summary>Heroicons' <c>document-arrow-down</c>.</summary>
        DocumentArrowDown,

        /// <summary>Heroicons' <c>document-arrow-up</c>.</summary>
        DocumentArrowUp,

        /// <summary>Heroicons' <c>document-chart-bar</c>.</summary>
        DocumentChartBar,

        /// <summary>Heroicons' <c>document-check</c>.</summary>
        DocumentCheck,

        /// <summary>Heroicons' <c>document-currency-bangladeshi</c>.</summary>
        DocumentCurrencyBangladeshi,

        /// <summary>Heroicons' <c>document-currency-dollar</c>.</summary>
        DocumentCurrencyDollar,

        /// <summary>Heroicons' <c>document-currency-euro</c>.</summary>
        DocumentCurrencyEuro,

        /// <summary>Heroicons' <c>document-currency-pound</c>.</summary>
        DocumentCurrencyPound,

        /// <summary>Heroicons' <c>document-currency-rupee</c>.</summary>
        DocumentCurrencyRupee,

        /// <summary>Heroicons' <c>document-currency-yen</c>.</summary>
        DocumentCurrencyYen,

        /// <summary>Heroicons' <c>document-duplicate</c>.</summary>
        DocumentDuplicate,

        /// <summary>Heroicons' <c>document-magnifying-glass</c>.</summary>
        DocumentMagnifyingGlass,

        /// <summary>Heroicons' <c>document-minus</c>.</summary>
        DocumentMinus,

        /// <summary>Heroicons' <c>document-plus</c>.</summary>
        DocumentPlus,

        /// <summary>Heroicons' <c>document-text</c>.</summary>
        DocumentText,

        /// <summary>Heroicons' <c>ellipsis-horizontal</c>.</summary>
        EllipsisHorizontal,

        /// <summary>Heroicons' <c>ellipsis-horizontal-circle</c>.</summary>
        EllipsisHorizontalCircle,

        /// <summary>Heroicons' <c>ellipsis-vertical</c>.</summary>
        EllipsisVertical,

        /// <summary>Heroicons' <c>envelope</c>.</summary>
        Envelope,

        /// <summary>Heroicons' <c>envelope-open</c>.</summary>
        EnvelopeOpen,

        /// <summary>Heroicons' <c>equals</c>.</summary>
        Equals,

        /// <summary>Heroicons' <c>exclamation-circle</c>.</summary>
        ExclamationCircle,

        /// <summary>Heroicons' <c>exclamation-triangle</c>.</summary>
        ExclamationTriangle,

        /// <summary>Heroicons' <c>eye</c>.</summary>
        Eye,

        /// <summary>Heroicons' <c>eye-dropper</c>.</summary>
        EyeDropper,

        /// <summary>Heroicons' <c>eye-slash</c>.</summary>
        EyeSlash,

        /// <summary>Heroicons' <c>face-frown</c>.</summary>
        FaceFrown,

        /// <summary>Heroicons' <c>face-smile</c>.</summary>
        FaceSmile,

        /// <summary>Heroicons' <c>film</c>.</summary>
        Film,

        /// <summary>Heroicons' <c>finger-print</c>.</summary>
        FingerPrint,

        /// <summary>Heroicons' <c>fire</c>.</summary>
        Fire,

        /// <summary>Heroicons' <c>flag</c>.</summary>
        Flag,

        /// <summary>Heroicons' <c>folder</c>.</summary>
        Folder,

        /// <summary>Heroicons' <c>folder-arrow-down</c>.</summary>
        FolderArrowDown,

        /// <summary>Heroicons' <c>folder-minus</c>.</summary>
        FolderMinus,

        /// <summary>Heroicons' <c>folder-open</c>.</summary>
        FolderOpen,

        /// <summary>Heroicons' <c>folder-plus</c>.</summary>
        FolderPlus,

        /// <summary>Heroicons' <c>forward</c>.</summary>
        Forward,

        /// <summary>Heroicons' <c>funnel</c>.</summary>
        Funnel,

        /// <summary>Heroicons' <c>gif</c>.</summary>
        Gif,

        /// <summary>Heroicons' <c>gift</c>.</summary>
        Gift,

        /// <summary>Heroicons' <c>gift-top</c>.</summary>
        GiftTop,

        /// <summary>Heroicons' <c>globe-alt</c>.</summary>
        GlobeAlt,

        /// <summary>Heroicons' <c>globe-americas</c>.</summary>
        GlobeAmericas,

        /// <summary>Heroicons' <c>globe-asia-australia</c>.</summary>
        GlobeAsiaAustralia,

        /// <summary>Heroicons' <c>globe-europe-africa</c>.</summary>
        GlobeEuropeAfrica,

        /// <summary>Heroicons' <c>h1</c>.</summary>
        H1,

        /// <summary>Heroicons' <c>h2</c>.</summary>
        H2,

        /// <summary>Heroicons' <c>h3</c>.</summary>
        H3,

        /// <summary>Heroicons' <c>hand-raised</c>.</summary>
        HandRaised,

        /// <summary>Heroicons' <c>hand-thumb-down</c>.</summary>
        HandThumbDown,

        /// <summary>Heroicons' <c>hand-thumb-up</c>.</summary>
        HandThumbUp,

        /// <summary>Heroicons' <c>hashtag</c>.</summary>
        Hashtag,

        /// <summary>Heroicons' <c>heart</c>.</summary>
        Heart,

        /// <summary>Heroicons' <c>home</c>.</summary>
        Home,

        /// <summary>Heroicons' <c>home-modern</c>.</summary>
        HomeModern,

        /// <summary>Heroicons' <c>identification</c>.</summary>
        Identification,

        /// <summary>Heroicons' <c>inbox</c>.</summary>
        Inbox,

        /// <summary>Heroicons' <c>inbox-arrow-down</c>.</summary>
        InboxArrowDown,

        /// <summary>Heroicons' <c>inbox-stack</c>.</summary>
        InboxStack,

        /// <summary>Heroicons' <c>information-circle</c>.</summary>
        InformationCircle,

        /// <summary>Heroicons' <c>italic</c>.</summary>
        Italic,

        /// <summary>Heroicons' <c>key</c>.</summary>
        Key,

        /// <summary>Heroicons' <c>language</c>.</summary>
        Language,

        /// <summary>Heroicons' <c>lifebuoy</c>.</summary>
        Lifebuoy,

        /// <summary>Heroicons' <c>light-bulb</c>.</summary>
        LightBulb,

        /// <summary>Heroicons' <c>link</c>.</summary>
        Link,

        /// <summary>Heroicons' <c>link-slash</c>.</summary>
        LinkSlash,

        /// <summary>Heroicons' <c>list-bullet</c>.</summary>
        ListBullet,

        /// <summary>Heroicons' <c>lock-closed</c>.</summary>
        LockClosed,

        /// <summary>Heroicons' <c>lock-open</c>.</summary>
        LockOpen,

        /// <summary>Heroicons' <c>magnifying-glass</c>.</summary>
        MagnifyingGlass,

        /// <summary>Heroicons' <c>magnifying-glass-circle</c>.</summary>
        MagnifyingGlassCircle,

        /// <summary>Heroicons' <c>magnifying-glass-minus</c>.</summary>
        MagnifyingGlassMinus,

        /// <summary>Heroicons' <c>magnifying-glass-plus</c>.</summary>
        MagnifyingGlassPlus,

        /// <summary>Heroicons' <c>map</c>.</summary>
        Map,

        /// <summary>Heroicons' <c>map-pin</c>.</summary>
        MapPin,

        /// <summary>Heroicons' <c>megaphone</c>.</summary>
        Megaphone,

        /// <summary>Heroicons' <c>microphone</c>.</summary>
        Microphone,

        /// <summary>Heroicons' <c>minus</c>.</summary>
        Minus,

        /// <summary>Heroicons' <c>minus-circle</c>.</summary>
        MinusCircle,

        /// <summary>Heroicons' <c>moon</c>.</summary>
        Moon,

        /// <summary>Heroicons' <c>musical-note</c>.</summary>
        MusicalNote,

        /// <summary>Heroicons' <c>newspaper</c>.</summary>
        Newspaper,

        /// <summary>Heroicons' <c>no-symbol</c>.</summary>
        NoSymbol,

        /// <summary>Heroicons' <c>numbered-list</c>.</summary>
        NumberedList,

        /// <summary>Heroicons' <c>paint-brush</c>.</summary>
        PaintBrush,

        /// <summary>Heroicons' <c>paper-airplane</c>.</summary>
        PaperAirplane,

        /// <summary>Heroicons' <c>paper-clip</c>.</summary>
        PaperClip,

        /// <summary>Heroicons' <c>pause</c>.</summary>
        Pause,

        /// <summary>Heroicons' <c>pause-circle</c>.</summary>
        PauseCircle,

        /// <summary>Heroicons' <c>pencil</c>.</summary>
        Pencil,

        /// <summary>Heroicons' <c>pencil-square</c>.</summary>
        PencilSquare,

        /// <summary>Heroicons' <c>percent-badge</c>.</summary>
        PercentBadge,

        /// <summary>Heroicons' <c>phone</c>.</summary>
        Phone,

        /// <summary>Heroicons' <c>phone-arrow-down-left</c>.</summary>
        PhoneArrowDownLeft,

        /// <summary>Heroicons' <c>phone-arrow-up-right</c>.</summary>
        PhoneArrowUpRight,

        /// <summary>Heroicons' <c>phone-x-mark</c>.</summary>
        PhoneXMark,

        /// <summary>Heroicons' <c>photo</c>.</summary>
        Photo,

        /// <summary>Heroicons' <c>play</c>.</summary>
        Play,

        /// <summary>Heroicons' <c>play-circle</c>.</summary>
        PlayCircle,

        /// <summary>Heroicons' <c>play-pause</c>.</summary>
        PlayPause,

        /// <summary>Heroicons' <c>plus</c>.</summary>
        Plus,

        /// <summary>Heroicons' <c>plus-circle</c>.</summary>
        PlusCircle,

        /// <summary>Heroicons' <c>power</c>.</summary>
        Power,

        /// <summary>Heroicons' <c>presentation-chart-bar</c>.</summary>
        PresentationChartBar,

        /// <summary>Heroicons' <c>presentation-chart-line</c>.</summary>
        PresentationChartLine,

        /// <summary>Heroicons' <c>printer</c>.</summary>
        Printer,

        /// <summary>Heroicons' <c>puzzle-piece</c>.</summary>
        PuzzlePiece,

        /// <summary>Heroicons' <c>qr-code</c>.</summary>
        QrCode,

        /// <summary>Heroicons' <c>question-mark-circle</c>.</summary>
        QuestionMarkCircle,

        /// <summary>Heroicons' <c>queue-list</c>.</summary>
        QueueList,

        /// <summary>Heroicons' <c>radio</c>.</summary>
        Radio,

        /// <summary>Heroicons' <c>receipt-percent</c>.</summary>
        ReceiptPercent,

        /// <summary>Heroicons' <c>receipt-refund</c>.</summary>
        ReceiptRefund,

        /// <summary>Heroicons' <c>rectangle-group</c>.</summary>
        RectangleGroup,

        /// <summary>Heroicons' <c>rectangle-stack</c>.</summary>
        RectangleStack,

        /// <summary>Heroicons' <c>rocket-launch</c>.</summary>
        RocketLaunch,

        /// <summary>Heroicons' <c>rss</c>.</summary>
        Rss,

        /// <summary>Heroicons' <c>scale</c>.</summary>
        Scale,

        /// <summary>Heroicons' <c>scissors</c>.</summary>
        Scissors,

        /// <summary>Heroicons' <c>server</c>.</summary>
        Server,

        /// <summary>Heroicons' <c>server-stack</c>.</summary>
        ServerStack,

        /// <summary>Heroicons' <c>share</c>.</summary>
        Share,

        /// <summary>Heroicons' <c>shield-check</c>.</summary>
        ShieldCheck,

        /// <summary>Heroicons' <c>shield-exclamation</c>.</summary>
        ShieldExclamation,

        /// <summary>Heroicons' <c>shopping-bag</c>.</summary>
        ShoppingBag,

        /// <summary>Heroicons' <c>shopping-cart</c>.</summary>
        ShoppingCart,

        /// <summary>Heroicons' <c>signal</c>.</summary>
        Signal,

        /// <summary>Heroicons' <c>signal-slash</c>.</summary>
        SignalSlash,

        /// <summary>Heroicons' <c>slash</c>.</summary>
        Slash,

        /// <summary>Heroicons' <c>sparkles</c>.</summary>
        Sparkles,

        /// <summary>Heroicons' <c>speaker-wave</c>.</summary>
        SpeakerWave,

        /// <summary>Heroicons' <c>speaker-x-mark</c>.</summary>
        SpeakerXMark,

        /// <summary>Heroicons' <c>square-2-stack</c>.</summary>
        Square2Stack,

        /// <summary>Heroicons' <c>square-3-stack-3d</c>.</summary>
        Square3Stack3d,

        /// <summary>Heroicons' <c>squares-2x2</c>.</summary>
        Squares2x2,

        /// <summary>Heroicons' <c>squares-plus</c>.</summary>
        SquaresPlus,

        /// <summary>Heroicons' <c>star</c>.</summary>
        Star,

        /// <summary>Heroicons' <c>stop</c>.</summary>
        Stop,

        /// <summary>Heroicons' <c>stop-circle</c>.</summary>
        StopCircle,

        /// <summary>Heroicons' <c>strikethrough</c>.</summary>
        Strikethrough,

        /// <summary>Heroicons' <c>sun</c>.</summary>
        Sun,

        /// <summary>Heroicons' <c>swatch</c>.</summary>
        Swatch,

        /// <summary>Heroicons' <c>table-cells</c>.</summary>
        TableCells,

        /// <summary>Heroicons' <c>tag</c>.</summary>
        Tag,

        /// <summary>Heroicons' <c>ticket</c>.</summary>
        Ticket,

        /// <summary>Heroicons' <c>trash</c>.</summary>
        Trash,

        /// <summary>Heroicons' <c>trophy</c>.</summary>
        Trophy,

        /// <summary>Heroicons' <c>truck</c>.</summary>
        Truck,

        /// <summary>Heroicons' <c>tv</c>.</summary>
        Tv,

        /// <summary>Heroicons' <c>underline</c>.</summary>
        Underline,

        /// <summary>Heroicons' <c>user</c>.</summary>
        User,

        /// <summary>Heroicons' <c>user-circle</c>.</summary>
        UserCircle,

        /// <summary>Heroicons' <c>user-group</c>.</summary>
        UserGroup,

        /// <summary>Heroicons' <c>user-minus</c>.</summary>
        UserMinus,

        /// <summary>Heroicons' <c>user-plus</c>.</summary>
        UserPlus,

        /// <summary>Heroicons' <c>users</c>.</summary>
        Users,

        /// <summary>Heroicons' <c>variable</c>.</summary>
        Variable,

        /// <summary>Heroicons' <c>video-camera</c>.</summary>
        VideoCamera,

        /// <summary>Heroicons' <c>video-camera-slash</c>.</summary>
        VideoCameraSlash,

        /// <summary>Heroicons' <c>view-columns</c>.</summary>
        ViewColumns,

        /// <summary>Heroicons' <c>viewfinder-circle</c>.</summary>
        ViewfinderCircle,

        /// <summary>Heroicons' <c>wallet</c>.</summary>
        Wallet,

        /// <summary>Heroicons' <c>wifi</c>.</summary>
        Wifi,

        /// <summary>Heroicons' <c>window</c>.</summary>
        Window,

        /// <summary>Heroicons' <c>wrench</c>.</summary>
        Wrench,

        /// <summary>Heroicons' <c>wrench-screwdriver</c>.</summary>
        WrenchScrewdriver,

        /// <summary>Heroicons' <c>x-circle</c>.</summary>
        XCircle,

        /// <summary>Heroicons' <c>x-mark</c>.</summary>
        XMark,

        /// <summary>Flux's loading spinner (<c>flux:icon.loading</c>): not a Heroicon, and it spins.</summary>
        Loading,
    }
}
