using System.Text;

namespace Rask.Cli.Scaffolding;

// The native template: a WebView-hybrid iOS + Android app.
internal static partial class ProjectGenerator
{
    /// <summary>
    /// Generates the <c>native</c> template into <paramref name="targetDirectory"/>. <paramref name="host"/>
    /// names which of Rask's app models supplies the UI: <c>"native"</c> (the Rask component code runs
    /// in-process on the device — offline, store-distributable), or <c>"server"</c> / <c>"wasm-hosted"</c>,
    /// a thin native shell over a Rask app you host, named for which kind it points at.
    /// </summary>
    public static ScaffoldResult GenerateNative(
        string targetDirectory, string name, string host, string version, bool ios = true, bool android = true)
    {
        // Neither platform is a project with nothing in it, so an empty selection is read as "both" rather
        // than scaffolded literally. The command line rejects it before this; this is the belt.
        if (!ios && !android)
        {
            (ios, android) = (true, true);
        }

        // "native" is the on-device model: the whole app runs in-process. Anything else is a thin shell over
        // a Rask app you host. The two remote models ("server", "wasm-hosted") scaffold the same heads —
        // RaskServerWebView is handed a trusted origin and never asks what serves it — and differ only in the
        // guidance baked into the file.
        var isLocal = NativeModels.For(host).RunsInProcess;

        // The csproj, plus each selected platform's manifest and entry point. An unselected platform
        // contributes no TFM and no files at all — a Platforms/iOS folder in an Android-only app is code
        // that never compiles and never runs, which is the kind of thing people keep around for years.
        var files = new List<(string Path, string Content)>
        {
            ($"{NameToken}.csproj", NativeCsproj(version, ios, android)),
        };

        if (android)
        {
            // The Android manifest carries an inline IsLocal conditional (the notification permission the
            // native backends need) resolved per host — see NativeAndroidManifest.
            files.Add(("Platforms/Android/AndroidManifest.xml", NativeAndroidManifest(isLocal)));
        }

        if (ios)
        {
            files.Add(("Platforms/iOS/Info.plist", NativeInfoPlist(isLocal)));
            files.Add(("Platforms/iOS/Main.cs", NativeMainCs));
        }

        if (isLocal)
        {
            // Native + Local: the component tree (App shell in Features/Shared, welcome screen in Features/Home)
            // plus the in-process platform heads, each of which boots a NativeAppHost + RunLocalAsync<App>.
            files.Add(("Features/Shared/App.cs", NativeAppShell));
            files.Add(("Features/Home/HomePage.cs", NativeHomePage));

            if (ios)
            {
                files.Add(("Platforms/iOS/AppDelegate.cs", NativeIosAppDelegate));
            }

            if (android)
            {
                files.Add(("Platforms/Android/MainActivity.cs", NativeAndroidMainActivity));
            }
        }
        else
        {
            // Native + remote: a thin shell — just the platform heads that point RaskServerWebView at a
            // Rask app you host. No shared component code runs on the device.
            if (ios)
            {
                files.Add(("Platforms/iOS/ServerAppDelegate.cs", NativeIosServerAppDelegate(host)));
            }

            if (android)
            {
                files.Add(("Platforms/Android/ServerActivity.cs", NativeAndroidServerActivity(host)));
            }
        }

        if (!isLocal)
        {
            // A remote model scaffolds BOTH halves — the app the shell points at, and the heads — as one
            // solution. A shell with nothing behind it is not a runnable app, and "runnable from the first
            // command" is the DX the four models are supposed to share.
            return GenerateNativeWithApp(targetDirectory, name, host, version, files, ios, android);
        }

        files.AddRange(ProjectHygiene($"{NameToken}.csproj"));

        var scaffoldFiles = Materialize(targetDirectory, name, files);

        return new ScaffoldResult(scaffoldFiles, NativeNextSteps(name, host, ios, android))
        {
            Packages = ["Rask.Native"],
        };
    }

    /// <summary>
    /// The remote models (<c>server</c>, <c>wasm-hosted</c>) as one solution: the Rask app you host, plus a
    /// <c>{name}.Mobile</c> project carrying the platform heads that point at it.
    /// </summary>
    /// <remarks>
    /// The app half is generated by the SAME generator the standalone template uses, into its own
    /// subdirectory and under its own name — <c>Materialize</c> substitutes the placeholder in paths and
    /// namespaces alike, so passing <c>{name}.Server</c> yields <c>{name}.Server/{name}.Server.csproj</c> with
    /// <c>{name}.Server.Features.*</c> namespaces, with no duplicated template content and nothing to drift.
    /// Its per-solution hygiene is dropped and re-emitted once at the root, over every project.
    /// </remarks>
    private static ScaffoldResult GenerateNativeWithApp(
        string targetDirectory,
        string name,
        string host,
        string version,
        List<(string Path, string Content)> mobileFiles,
        bool ios,
        bool android)
    {
        var wasmHosted = string.Equals(host, "wasm-hosted", StringComparison.Ordinal);

        // wasm-hosted is already a multi-project solution, so its three projects sit at the root beside the
        // mobile head; server is a single project and gets a `.Server` directory of its own, which also gives
        // the two models the same project name for the same role.
        var app = wasmHosted
            ? GenerateWasmHosted(targetDirectory, name, new ServerBatteries(), version)
            : GenerateServer(
                System.IO.Path.Combine(targetDirectory, $"{name}.Server"), $"{name}.Server",
                new ServerBatteries(), version);

        var appProjects = wasmHosted
            ? new[]
            {
                $"{name}.Client/{name}.Client.csproj",
                $"{name}.Server/{name}.Server.csproj",
                $"{name}.Shared/{name}.Shared.csproj",
            }
            : [$"{name}.Server/{name}.Server.csproj"];

        var mobile = Materialize(
            System.IO.Path.Combine(targetDirectory, $"{name}.Mobile"), $"{name}.Mobile", mobileFiles);

        // One .gitignore / .editorconfig / .slnx for the whole solution, not one per half.
        var hygiene = Materialize(targetDirectory, name,
            ProjectHygiene([.. appProjects, $"{name}.Mobile/{name}.Mobile.csproj"]));

        List<ScaffoldFile> files = [.. app.Files.Where(IsNotHygiene), .. mobile, .. hygiene];

        return new ScaffoldResult(files, NativeNextSteps(name, host, ios, android))
        {
            Packages = ["Rask.Native", .. app.Packages],
            // No root csproj — restore (and the overwrite guard) target the solution, which pulls them all.
            RestoreTarget = $"{name}.slnx",
        };

        // The app generator emits its own solution-level files; this solution owns those.
        static bool IsNotHygiene(ScaffoldFile file) =>
            System.IO.Path.GetFileName(file.Path) is not (".gitignore" or ".editorconfig")
            && !file.Path.EndsWith(".slnx", StringComparison.Ordinal);
    }

    private static string NativeCsproj(string version, bool ios, bool android)
    {
        var targets = string.Join(';', NativeTargetFrameworks(ios, android));
        var platforms = ios && android ? "iOS + Android" : ios ? "iOS" : "Android";
        var workloads = string.Join(' ', NativeWorkloads(ios, android));
        var runCommands = string.Join('\n', NativeRunLines(ios, android).Select(line => "        " + line));

        // The per-platform blocks are assembled rather than interpolated inline: each is optional, and a
        // placeholder that is sometimes empty either leaves a blank line behind or has to carry its own,
        // which is how a generated file ends up with two blank lines in the middle of it.
        var sections = string.Concat(
            NativeIosProjectGroups(ios),
            NativeAndroidProjectGroups(android));

        var headGuards = NativeHeadGuards(ios, android);

        return $"""
        <Project Sdk="Microsoft.NET.Sdk">

          <!--
            A native {platforms} app that hosts a Rask app in-process inside a platform WebView (the WebView
            hybrid — C# runs natively, the view is a WebView). The shared component code (App.cs) compiles for
            every target below, and each platform head under Platforms/ provides the INativeWebView
            implementation for its WebView control.

            Requires the SDK workload(s):
                dotnet workload install {workloads}
            Run on a simulator/emulator:
        {runCommands}
          -->
          <PropertyGroup>
            <TargetFrameworks>{targets}</TargetFrameworks>
            <OutputType>Exe</OutputType>
            <Nullable>enable</Nullable>
            <ImplicitUsings>enable</ImplicitUsings>
            <RootNamespace>Company.RaskServer</RootNamespace>
            <ApplicationTitle>Rask App</ApplicationTitle>
            <ApplicationId>com.example.raskapp</ApplicationId>
            <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
            <ApplicationVersion>1</ApplicationVersion>
          </PropertyGroup>

        {sections}  <ItemGroup>
            <PackageReference Include="Rask.Native" Version="{version}"/>
          </ItemGroup>
        {headGuards}
        </Project>

        """;
    }

    /// <summary>
    /// The iOS-only project configuration, omitted entirely when iOS is not a target. Each block ends with
    /// the blank line that separates it from what follows, so an omitted block leaves nothing behind.
    /// </summary>
    private static string NativeIosProjectGroups(bool ios) => ios
        ? """
          <PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
            <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
          </PropertyGroup>

          <!-- Wire Platforms/iOS/Info.plist as THE app manifest (a None item whose Link filename is "Info.plist"
               is how .NET iOS finds it). Its UILaunchScreen makes the app render full-screen at the device's native
               resolution — without a launch screen iOS runs it letterboxed (black bars + everything scaled up). -->
          <ItemGroup Condition="$(TargetFramework.Contains('-ios'))">
            <None Remove="Platforms/iOS/Info.plist"/>
            <None Include="Platforms/iOS/Info.plist" Link="Info.plist"/>
          </ItemGroup>


        """
        : "";

    private static string NativeAndroidProjectGroups(bool android) => android
        ? """
          <PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
            <SupportedOSPlatformVersion>24.0</SupportedOSPlatformVersion>
            <AndroidManifest>Platforms/Android/AndroidManifest.xml</AndroidManifest>
          </PropertyGroup>


        """
        : "";

    /// <summary>
    /// The per-TFM compile guards, emitted only for a multi-targeted project. With one target there is
    /// nothing to keep apart, and a guard naming a platform the project doesn't build reads as a promise
    /// that it could.
    /// </summary>
    private static string NativeHeadGuards(bool ios, bool android) => ios && android
        ? """

          <!-- Each platform head compiles only for its own TFM. -->
          <ItemGroup Condition="!$(TargetFramework.Contains('-ios'))">
            <Compile Remove="Platforms/iOS/**/*.cs"/>
          </ItemGroup>
          <ItemGroup Condition="!$(TargetFramework.Contains('-android'))">
            <Compile Remove="Platforms/Android/**/*.cs"/>
          </ItemGroup>

        """
        : "";

    /// <summary>The target frameworks for the selected platforms, iOS first (the order the SDK lists them).</summary>
    private static IEnumerable<string> NativeTargetFrameworks(bool ios, bool android)
    {
        if (ios)
        {
            yield return "net10.0-ios";
        }

        if (android)
        {
            yield return "net10.0-android";
        }
    }

    /// <summary>The SDK workloads the selected platforms need, for the `dotnet workload install` line.</summary>
    private static IEnumerable<string> NativeWorkloads(bool ios, bool android)
    {
        if (ios)
        {
            yield return "ios";
        }

        if (android)
        {
            yield return "android";
        }
    }

    /// <summary>The on-device run commands for the selected platforms.</summary>
    private static IEnumerable<string> NativeRunLines(bool ios, bool android)
    {
        if (android)
        {
            yield return $"{Commands.NativeRunCommands.Android}     # Android emulator";
        }

        if (ios)
        {
            yield return $"{Commands.NativeRunCommands.IOS}         # iOS simulator (macOS + Xcode)";
        }
    }

    private static string NativeInfoPlist(bool isLocal) =>
        isLocal ? NativeInfoPlistBody : NativeInfoPlistBody.Replace(
            "\t<key>UILaunchScreen</key>",
            // A remote head points at this solution's app half over http on the dev machine. ATS blocks that;
            // NSAllowsLocalNetworking is the narrow switch that permits it for localhost and .local without
            // opening the app to arbitrary cleartext. Drop it once the origin is https.
            "\t<key>NSAppTransportSecurity</key>\n"
            + "\t<dict>\n"
            + "\t\t<key>NSAllowsLocalNetworking</key>\n"
            + "\t\t<true/>\n"
            + "\t</dict>\n"
            + "\t<key>UILaunchScreen</key>",
            StringComparison.Ordinal);

    private const string NativeInfoPlistBody =
        """
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
        	<key>CFBundleDisplayName</key>
        	<string>Rask App</string>
        	<key>CFBundleIdentifier</key>
        	<string>com.example.raskapp</string>
        	<key>CFBundleShortVersionString</key>
        	<string>1.0</string>
        	<key>CFBundleVersion</key>
        	<string>1</string>
        	<key>LSRequiresIPhoneOS</key>
        	<true/>
        	<key>MinimumOSVersion</key>
        	<string>15.0</string>
        	<key>UIDeviceFamily</key>
        	<array>
        		<integer>1</integer>
        		<integer>2</integer>
        	</array>
        	<!-- A launch screen is REQUIRED for iOS to render at the device's native resolution; without one the
        	     app runs letterboxed at a legacy size (black bars + everything scaled up). An empty UILaunchScreen
        	     dict opts into full-screen with a blank system launch screen (no storyboard file needed). -->
        	<key>UILaunchScreen</key>
        	<dict/>

        	<key>UISupportedInterfaceOrientations</key>
        	<array>
        		<string>UIInterfaceOrientationPortrait</string>
        		<string>UIInterfaceOrientationLandscapeLeft</string>
        		<string>UIInterfaceOrientationLandscapeRight</string>
        	</array>
        </dict>
        </plist>

        """;

    // AndroidManifest.xml carries an inline `<!--#if (IsLocal) -->` block (the POST_NOTIFICATIONS permission
    // the native backends need). Resolved per host, markers stripped.
    private static string NativeAndroidManifest(bool isLocal)
    {
        var permissionsBlock = isLocal
            ? "\n\t<!-- Required by NativeNotifications (the INotifications backend) on API 33+. Remove if unused. -->"
              + "\n\t<uses-permission android:name=\"android.permission.POST_NOTIFICATIONS\"/>"
            : "";

        // A remote head points at this solution's app half over http on the dev machine, and Android blocks
        // cleartext by default — without this the WebView loads nothing and says nothing useful. Drop it once
        // the origin is https, which is also when it stops being true that only localhost is reached.
        var cleartext = isLocal
            ? ""
            : "\n\t\t android:usesCleartextTraffic=\"true\"";

        return $"""
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android">
        	<uses-permission android:name="android.permission.INTERNET"/>{permissionsBlock}
        	<application android:label="Rask App" android:allowBackup="true" android:supportsRtl="true"{cleartext}/>
        </manifest>

        """;
    }

    private static string NativeNextSteps(string name, string host, bool ios, bool android)
    {
        var platforms = ios && android ? "iOS + Android" : ios ? "iOS" : "Android";

        var model = NativeModels.For(host);
        var isLocal = model.RunsInProcess;

        var steps = new StringBuilder();
        steps.Append("Created ").Append(name).Append(" (Rask native ").Append(platforms)
            .Append(" app, UI from ").Append(model.Summary).Append(").\n");
        // The three things that genuinely differ between the models, stated once here rather than left to
        // be discovered — waiting on a reload that was never coming is the failure this prevents.
        steps.Append("  ").Append(model.TradeOff).Append("\n\nNext steps:\n");
        steps.Append("  cd ").Append(name).Append('\n');
        steps.Append("  dotnet workload install ").Append(string.Join(' ', NativeWorkloads(ios, android)))
            .Append("   # once, if not already installed\n");

        // A remote model scaffolded BOTH halves, so the steps have to start the app the heads point at and
        // then run a head from its own project — "cd, build, run" would build the wrong thing and the shell
        // would open on a connection refused.
        if (!isLocal)
        {
            steps.Append('\n');
            steps.Append("  dotnet run --project ").Append(name).Append(".Server")
                .Append("   # 1. the app the shell points at (http://localhost:5000)\n");
            steps.Append('\n');
            steps.Append("  cd ").Append(name).Append(".Mobile").Append("   # 2. then, in another terminal:\n");
        }

        // The same command strings the `rask dev` native refusal points at (Commands.NativeRunCommands),
        // so the two cannot drift and start telling people different things — filtered to what this
        // project actually targets, because a run command for a platform it doesn't build is a dead end.
        foreach (var line in NativeRunLines(ios, android))
        {
            steps.Append("  ").Append(line).Append('\n');
        }

        return steps.ToString();
    }

    // ---- native-only template files ----

    // The root shell, in the Features/Shared bucket. A native page is a small COMPOSED tree: the native bars
    // (NativeHeaderBar / NativeTabBar) as siblings of a NativeWebView, which hosts the ordinary page shell
    // (Doctype/Html/Head/Body, RASK021). The native host projects the bars to REAL platform chrome — a
    // UINavigationBar + UITabBar on iOS, a top bar + bottom tab bar on Android — and serializes the
    // NativeWebView's HTML into the WebView between them.
    private const string NativeAppShell =
        """
        using Rask.Core.Routing;
        using Rask.Native.Components;

        // NativeHeaderBar / NativeScreen are chain entries the generator emits into this markup host
        // (hence `partial`) for any project referencing Rask.Native — no import needed here.

        namespace Company.RaskServer.Features.Shared;

        public sealed partial class App : Component
        {
            protected override Component? Render() =>
            [
                // A real UINavigationBar / Android top bar. The head registers itself as the INativeChrome
                // backend — see Platforms/iOS/AppDelegate.cs and Platforms/Android/MainActivity.cs.
                NativeHeaderBar.Title("Rask App"),

                // The pure-native content surface: everything inside paints as real platform views, with no
                // WebView and no HTML anywhere. Router works here exactly as it does on the web, so [Route]
                // pages, route parameters and type-safe navigation are unchanged.
                NativeScreen[Router]

                // Add a real native bottom tab bar here once you have somewhere to navigate:
                //   NativeTabBar.Tabs([NativeTab.Title("Home").Icon(NativeIcon.Home).To(Routes.HomePage())])
                // Tapping a tab routes to its type-safe To; the framework highlights the matching route.
            ];
        }

        // Want a web page on one route instead? Compose a NativeWebView on it and the host swaps surfaces as
        // you navigate, keeping both alive:
        //
        //     OnDocs ? NativeWebView[Router] : NativeScreen[Router]
        //
        // Putting HTML inside a NativeScreen is a compile error (RASK048), as is putting a native component
        // inside the HTML tree (RASK032) — the two families do not mix within one surface.

        """;

    // The welcome screen, its own Features/Home slice — a new native project already models the CLI's
    // "screens are feature slices" convention. Pure-native: every element here is a real UILabel /
    // TextView, not HTML in a WebView.
    private const string NativeHomePage =
        """
        using Rask.Core.Routing;
        using Rask.Native.Components;

        namespace Company.RaskServer.Features.Home;

        [Route("/")]
        public sealed partial class HomePage : Component
        {
            // NativeStack always states its Orientation. Left unset the two platforms disagree — iOS stacks
            // vertically, Android horizontally — so a screen that looks right on one is a single squashed row
            // on the other.
            protected override Component? Render() =>
                NativeScreen[
                    NativeStack.Orientation(NativeOrientation.Vertical).Spacing(12).Padding(20)[
                        NativeLabel.FontSize(28).FontWeight(NativeFontWeight.Bold)["Hello, Rask! 👋"],
                        NativeLabel[
                            "Your native app is ready. Every control on this screen is a real platform view."],
                        NativeDivider,
                        NativeLabel.FontSize(14)[
                            "Edit this page in HomePage.cs. Add a route with [Route(\"/next\")] and the tab bar "
                            + "or a NativeButton can navigate to it."]
                    ]
                ];
        }

        """;

    private const string NativeMainCs =
        """
        using UIKit;

        namespace Company.RaskServer;

        // iOS entry point. Hands control to UIKit with our AppDelegate.
        public static class Program
        {
            private static void Main(string[] args) => UIApplication.Main(args, null, typeof(AppDelegate));
        }

        """;

    private const string NativeIosAppDelegate =
        """
        using Company.RaskServer.Features.Shared;
        using Foundation;
        using Microsoft.Extensions.DependencyInjection;
        using Rask.Native;
        using UIKit;

        namespace Company.RaskServer;

        [Register("AppDelegate")]
        public class AppDelegate : UIApplicationDelegate
        {
            public override UIWindow? Window { get; set; }
            private NativeApp? _app;

            public override bool FinishedLaunching(UIApplication application, NSDictionary? launchOptions)
            {
                Window = new UIWindow(UIScreen.MainScreen.Bounds);

                var webView = new RaskWkWebView();
                // Host ChromeView (the container that lays the native header/footer bars around the content) rather
                // than the bare view, so the App's composed NativeHeaderBar/NativeTabBar become a real
                // UINavigationBar/UITabBar. The INativeChrome backend is registered below; without it the bars render
                // nothing, so a native app that navigates via the tab bar should keep that registration.
                Window.RootViewController = new UIViewController { View = webView.ChromeView };
                Window.MakeKeyAndVisible();

                _ = StartAsync(webView);
                return true;
            }

            private async Task StartAsync(RaskWkWebView webView)
            {
                var host = NativeAppHost.CreateDefault();
                // All fifteen native device backends in one line — share, geolocation, clipboard, vibration,
                // wake lock, network info, battery, speech, screen info, orientation/motion, notifications,
                // badge and permissions. The framework resolves each native-first over the WebView's JS
                // default. Call UsePlatform before running the app. See docs/native.md.
                host.UsePlatform(new ApplePlatform(() => Window?.RootViewController));
                host.Services.AddSingleton<INativeChrome>(webView);                                         // native header/footer bars
                // host.Services.AddSingleton<IMyService, MyService>();   // register app services here

                // RunNativeAsync, not RunLocalAsync: the app paints real platform views through the surface
                // backend, so there is no HTML, no boot shell to load, and no `ready` handshake to wait for —
                // the host renders the first frame itself and returns with the app already on screen.
                _app = await host.RunNativeAsync<App>(webView);
            }

            public override void WillTerminate(UIApplication application) => _ = _app?.DisposeAsync();
        }

        """;

    /// <summary>
    /// The remote-mode heads, worded for what <paramref name="host"/> points at. The code is identical
    /// either way — only the comment above the origin differs, and it is the line someone reads when they
    /// come to replace the placeholder URL.
    /// </summary>
    private static string NativeIosServerAppDelegate(string host) =>
        NativeIosServerAppDelegateTemplate
            .Replace("{{target}}", RemoteTargetName(host), StringComparison.Ordinal)
            .Replace("{{origin}}", IosDevOrigin, StringComparison.Ordinal)
            .Replace("{{origin-note}}", RemoteOriginNote(host), StringComparison.Ordinal);

    private static string NativeAndroidServerActivity(string host) =>
        NativeAndroidServerActivityTemplate
            .Replace("{{target}}", RemoteTargetName(host), StringComparison.Ordinal)
            .Replace("{{origin}}", AndroidDevOrigin, StringComparison.Ordinal)
            .Replace("{{origin-note}}", RemoteOriginNote(host), StringComparison.Ordinal);

    // The scaffolded app's own dev URL, so a fresh solution connects with nothing to edit. The two platforms
    // reach the dev machine differently: the iOS simulator shares the host's loopback, while the Android
    // emulator is a separate VM whose 10.0.2.2 is an alias for the host. Port 5000 is what the app half's
    // launchSettings.json serves http on.
    private const string IosDevOrigin = "http://localhost:5000/";
    private const string AndroidDevOrigin = "http://10.0.2.2:5000/";

    /// <summary>How each model is described to the person who just scaffolded it.</summary>
    private static string NativeHostSummary(string host) => NativeModels.For(host).Summary;

    /// <summary>How the thing the shell points at is named in the generated comments.</summary>
    private static string RemoteTargetName(string host) =>
        string.Equals(host, "wasm-hosted", StringComparison.Ordinal) ? "wasm-hosted Rask app" : "Rask Server";

    /// <summary>
    /// What is worth knowing about the origin, per mode. A live server renders over a WebSocket, so the
    /// device needs to reach it continuously; a wasm-hosted bundle is static once loaded, which is the
    /// difference that decides whether a flaky connection is a blank screen or a working app.
    /// </summary>
    private static string RemoteOriginNote(string host) =>
        string.Equals(host, "wasm-hosted", StringComparison.Ordinal)
            ? "Points at this solution's app half, running locally. The published bundle runs in the WebView, "
              + "so the app keeps working once it has loaded. Swap in your deployed https:// URL to ship."
            : "Points at this solution's app half, running locally. The server renders over a WebSocket, so the "
              + "device needs to reach it while the app is open. Swap in your deployed https:// URL to ship.";

    private const string NativeIosServerAppDelegateTemplate =
        """
        using Foundation;
        using Rask.Native;
        using UIKit;

        namespace Company.RaskServer;

        // Native + remote mode (iOS): a thin native shell over a {{target}} you host. The WebView machinery — the
        // native capability bridge (so the remote page's Shareable / IShare reach the device's native backends),
        // the trusted-origin gating, and the off-origin-to-Safari diversion — lives in Rask.Native's
        // RaskServerViewController. This head just points it at your app and supplies the native share backend.
        [Register("AppDelegate")]
        public class AppDelegate : UIApplicationDelegate
        {
            // Your {{target}} (a real deployment is https).
            // {{origin-note}}
            private static readonly Uri ServerOrigin = new("{{origin}}");

            public override UIWindow? Window { get; set; }

            public override bool FinishedLaunching(UIApplication application, NSDictionary? launchOptions)
            {
                var shell = NativeAppHost.ConnectToServer(ServerOrigin);
                Window = new UIWindow(UIScreen.MainScreen.Bounds)
                {
                    RootViewController = new RaskServerViewController(
                        shell.ServerBaseUrl, new NativeShare(() => Window?.RootViewController))
                };
                Window.MakeKeyAndVisible();
                return true;
            }
        }

        """;

    private const string NativeAndroidMainActivity =
        """
        using Android.App;
        using Android.Content.PM;
        using Android.OS;
        using Company.RaskServer.Features.Shared;
        using Microsoft.Extensions.DependencyInjection;
        using Rask.Native;

        namespace Company.RaskServer;

        [Activity(Label = "Rask App", MainLauncher = true, Exported = true,
            Theme = "@android:style/Theme.Material.Light.NoActionBar")]
        public class MainActivity : Activity
        {
            private NativeApp? _app;
            private RaskAndroidWebView? _webView;

            protected override void OnCreate(Bundle? savedInstanceState)
            {
                base.OnCreate(savedInstanceState);

                // NativeNotifications (registered below) needs the POST_NOTIFICATIONS runtime grant on API 33+ —
                // request it up front so a later ShowAsync posts (declare POST_NOTIFICATIONS in AndroidManifest.xml).
                if (OperatingSystem.IsAndroidVersionAtLeast(33) &&
                    CheckSelfPermission(Android.Manifest.Permission.PostNotifications) != Permission.Granted)
                {
                    RequestPermissions([Android.Manifest.Permission.PostNotifications], 101);
                }

                _webView = new RaskAndroidWebView(this);
                // Host ChromeView (the container that lays the native header/footer bars around the content) rather
                // than the bare view, so the App's composed NativeHeaderBar/NativeTabBar become real top/bottom bars.
                // The INativeChrome backend is registered below; without it the bars render nothing, so a native app
                // that navigates via the tab bar should keep that registration.
                SetContentView(_webView.ChromeView);

                _ = StartAsync(_webView);
                RegisterBackHandler();
            }

            private async Task StartAsync(RaskAndroidWebView webView)
            {
                var host = NativeAppHost.CreateDefault();
                // All fifteen native device backends in one line — share, geolocation, clipboard, vibration,
                // wake lock, network info, battery, speech, screen info, orientation/motion, notifications,
                // badge and permissions. The framework resolves each native-first over the WebView's JS
                // default. Call UsePlatform before running the app. See docs/native.md.
                host.UsePlatform(new AndroidPlatform(this));
                host.Services.AddSingleton<INativeChrome>(webView);                              // native header/footer bars
                // host.Services.AddSingleton<IMyService, MyService>();   // register app services here

                // RunNativeAsync, not RunLocalAsync: the app paints real platform views through the surface
                // backend, so there is no HTML, no boot shell to load, and no `ready` handshake to wait for —
                // the host renders the first frame itself and returns with the app already on screen.
                _app = await host.RunNativeAsync<App>(webView);
            }

            // Route the hardware Back button through the app's own history instead of the activity stack, so
            // Back means "the previous page" the way it does in any other Android app.
            //
            // This uses OnBackInvokedDispatcher, NOT the OnBackPressed override. For an app targeting API 35+
            // predictive back is on by default and OnBackPressed is NEVER CALLED — wiring only that override
            // compiles, looks right, and silently closes the app mid-navigation. The override is kept below
            // for API 32 and earlier, where the dispatcher does not exist.
            private BackInvokedCallback? _backCallback;

            private void RegisterBackHandler()
            {
                if (!OperatingSystem.IsAndroidVersionAtLeast(33) || OnBackInvokedDispatcher is not { } dispatcher)
                {
                    return;
                }

                _backCallback = new BackInvokedCallback(this);
                // PRIORITY_DEFAULT. Registering a callback takes over the gesture entirely, so this handler
                // owns closing the app too — see HandleBack.
                dispatcher.RegisterOnBackInvokedCallback(0, _backCallback);
            }

            // Nothing to go back to means the press should close the app, which is what a user expects at
            // the root of a task. The system no longer does that for us once a callback is registered, so
            // Finish() is ours to call — without it Back would be dead on the first page.
            private void HandleBack()
            {
                if (_app is { CanGoBack: true } app)
                {
                    _ = app.GoBackAsync();
                    return;
                }

                Finish();
            }

            private sealed class BackInvokedCallback(MainActivity owner)
                : Java.Lang.Object, Android.Window.IOnBackInvokedCallback
            {
                public void OnBackInvoked() => owner.HandleBack();
            }

            // API 32 and earlier: no dispatcher, and this override is still delivered.
            public override void OnBackPressed()
            {
                if (_app is { CanGoBack: true } app)
                {
                    _ = app.GoBackAsync();
                    return;
                }

                base.OnBackPressed();
            }

            // Forward runtime-permission results so NativeNotifications' RequestPermissionAsync can await the grant.
            public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
            {
                NativePermissions.OnResult(requestCode, grantResults);
                base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            }

            protected override void OnDestroy()
            {
                if (_backCallback is { } cb && OperatingSystem.IsAndroidVersionAtLeast(33))
                {
                    OnBackInvokedDispatcher?.UnregisterOnBackInvokedCallback(cb);
                    _backCallback = null;
                }

                _ = _app?.DisposeAsync();
                base.OnDestroy();
            }
        }

        """;

    private const string NativeAndroidServerActivityTemplate =
        """
        using Android.App;
        using Android.OS;
        using Rask.Native;

        namespace Company.RaskServer;

        // Native + remote mode: a thin native shell over a {{target}} you host. The WebView machinery — the native
        // capability bridge (so the remote page's Shareable / IShare reach the device's native backends), the
        // trusted-origin gating, and the off-origin-to-system-browser diversion — lives in Rask.Native's
        // RaskServerWebView. This head just points it at your app and supplies the native share backend.
        [Activity(Label = "Rask App", MainLauncher = true, Exported = true,
            Theme = "@android:style/Theme.Material.Light.NoActionBar")]
        public class ServerActivity : Activity
        {
            // Your {{target}}. (Android emulator → host machine is http://10.0.2.2:<port>; a real
            // deployment is https. For http during development, allow cleartext in AndroidManifest.xml.)
            // {{origin-note}}
            private static readonly Uri ServerOrigin = new("{{origin}}");

            protected override void OnCreate(Bundle? savedInstanceState)
            {
                base.OnCreate(savedInstanceState);
                SetContentView(RaskServerWebView.Create(this, ServerOrigin, new NativeShare(this)));
            }
        }

        """;
}
