using System.Text;
using Rask.WebPush;

namespace Rask.Cli.Scaffolding;

/// <summary>
///     Writes the scaffold's DEVELOPMENT Web Push key pair, so a <c>--push</c> app can send a push the
///     minute it starts instead of after a detour through the docs.
/// </summary>
/// <remarks>
///     <para>
///         Web Push will not send without a VAPID pair (RFC 8292), and a pair cannot be committed to a
///         template: the private key signs, so a pair shared by every scaffolded app on earth is not a
///         key at all. It has to be minted per scaffold, which means minting it here — the one moment
///         that already runs code and already writes the app's files.
///     </para>
///     <para>
///         It lands in <c>appsettings.Development.json</c>, which the scaffold's own <c>.gitignore</c>
///         already lists ("Local configuration and secrets … keep the templates tracked instead") while
///         no template shipped a file for it to ignore. Deliberately gitignored, and the one place the
///         scaffolder writes what it also ignores — see <c>ScaffoldIgnoreOverlapTests</c>, which knows
///         this file by name and holds everything else to the rule. The rule's reason is that a fresh
///         clone silently loses the file; that is the right trade only because losing THIS one costs a
///         teammate a regenerated dev key rather than a broken build. Both the template's Program.cs and
///         <c>RaskBatteryWiring</c> wire the sender only once keys are present, so an app with no keys
///         starts and runs — push is simply off.
///     </para>
///     <para>
///         Keyed off the rendered <c>appsettings.json</c> actually carrying a <c>WebPush</c> section
///         rather than off a second list of template names. A list would be a third place to remember
///         when a template gains Web Push — the meta templates (Next.js, Nuxt, SvelteKit …) accept
///         <c>--push</c> today but wire none of it — and the one that got forgotten would scaffold keys
///         nothing reads, or read keys nothing scaffolds.
///     </para>
/// </remarks>
internal static class WebPushAssembly
{
    /// <summary>The generated file's name, relative to the app root.</summary>
    internal const string DevelopmentSettingsFile = "appsettings.Development.json";

    /// <summary>The settings file whose rendered content decides whether this app uses Web Push.</summary>
    private const string SettingsFile = "appsettings.json";

    /// <summary>The section that has to be present for a generated pair to be read by anything.</summary>
    private const string Marker = "\"WebPush\"";

    /// <summary>
    ///     <paramref name="existing" /> plus <c>appsettings.Development.json</c> holding a freshly minted
    ///     pair, when this scaffold renders a <c>WebPush</c> section. Otherwise <paramref name="existing" />
    ///     unchanged.
    /// </summary>
    public static IReadOnlyList<ScaffoldFile> Apply(string targetDirectory, IReadOnlyList<ScaffoldFile> existing)
    {
        ArgumentException.ThrowIfNullOrEmpty(targetDirectory);
        ArgumentNullException.ThrowIfNull(existing);

        var settings = existing.FirstOrDefault(f =>
            string.Equals(Path.GetFileName(f.Path), SettingsFile, StringComparison.Ordinal));

        if (settings?.Content.Contains(Marker, StringComparison.Ordinal) != true)
        {
            return existing;
        }

        // Beside the appsettings.json it overrides, wherever that is — the host root for the server
        // template, and the same root for a SPA template whose front end lives under client/.
        var directory = Path.GetDirectoryName(settings.Path) ?? targetDirectory;
        var path = Path.Combine(directory, DevelopmentSettingsFile);

        // Secret: PrivateKey signs every push this app sends (#1124).
        return [.. existing, new ScaffoldFile(path, DevelopmentSettings()) { Secret = true }];
    }

    /// <summary>The generated file, pair and all.</summary>
    private static string DevelopmentSettings()
    {
        (var publicKey, var privateKey) = VapidKeyMaterial.Generate();

        // JSONC: the configuration reader accepts comments and trailing commas, which is what lets every
        // appsettings file in a Rask scaffold explain itself. The comments matter more here than usual —
        // this is the one file in the app that holds a secret, and it is the one file a reader cannot
        // diff against a template to see what it is for.
        var json = new StringBuilder();
        json.Append(
            """
            {
              // Generated by `rask new`: this app's DEVELOPMENT Web Push key pair (VAPID, RFC 8292),
              // minted for this scaffold alone and shared with no other app.
              //
              // Gitignored on purpose. PrivateKey SIGNS every push this app sends, so it is a secret in
              // the way a database password is — never committed, and never served to a browser.
              // PublicKey is the other half and is not secret at all: it is exactly the
              // `applicationServerKey` the browser passes to pushManager.subscribe, which is why the
              // same string is what you hand to IWebPush.SubscribeAsync.
              //
              // Production does NOT read this file — it is Development-only. Deployed, both keys come
              // from the environment, which is what `rask deploy --env` sets:
              //   Rask__WebPush__VapidKeys__PublicKey
              //   Rask__WebPush__VapidKeys__PrivateKey
              // Mint a SEPARATE pair for it. Replacing a pair silently unsubscribes everyone already
              // subscribed to the old one, so treat a change as a migration, not routine rotation.
              //
              // Lost this file — a fresh clone, a new machine? Nothing breaks: with no keys configured
              // the app still starts and simply does not wire the sender. Mint a replacement with
              // VapidKeys.Generate() and paste it back here.
              "Rask": {
                "WebPush": {
                  "VapidKeys": {

            """);

        json.Append("        \"PublicKey\": \"").Append(publicKey).Append("\",\n");
        json.Append("        \"PrivateKey\": \"").Append(privateKey).Append('"').Append('\n');

        json.Append(
            """
                  }
                }
              }
            }

            """);

        return json.ToString();
    }
}
