using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Rask.Generators.Shared;

namespace Rask.Auth.Generators;

/// <summary>
/// Finds the application's account type — the one class deriving from ASP.NET Core Identity's
/// <c>IdentityUser</c> — and emits a <c>[ModuleInitializer]</c> naming it to <c>Rask.Auth.AuthUser</c>,
/// so <c>AddRaskAuth()</c> and <c>modelBuilder.AddRaskAuth()</c> need no type argument.
/// </summary>
/// <remarks>
/// Rask ships no user class of its own, so without this every call would have to name the app's. The
/// binding closes over the type at compile time — generated, never reflected — which is what keeps the
/// account tables through a trimmed publish.
/// </remarks>
[Generator]
public sealed class AuthUserGenerator : IIncrementalGenerator
{
    private const string IdentityUserBase = "IdentityUser";
    private const string IdentityNamespace = "Microsoft.AspNetCore.Identity";

    private static readonly DiagnosticDescriptor Rask074 = new(
        "RASK074",
        "More than one account type",
        "'{0}' and '{1}' both derive from IdentityUser, so Rask cannot tell which one is this app's "
        + "account; auth is left unwired. Keep one user type — the other is an entity like any other, "
        + "and does not need to derive from IdentityUser to be mapped.",
        DiagnosticHelp.Category,
        DiagnosticSeverity.Warning,
        true,
        description: "The account type is found rather than named, which needs there to be one. With two, "
                     + "picking either would map one set of account tables and silently strand the other, "
                     + "and the app would look wired until the first sign-in.",
        helpLinkUri: DiagnosticHelp.Link("RASK074"));

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
                static (ctx, _) => GetCandidate(ctx))
            .Where(static c => c is not null)
            .Select(static (c, _) => c!.Value);

        context.RegisterSourceOutput(candidates.Collect(), static (spc, all) => Emit(spc, all));
    }

    private static Candidate? GetCandidate(GeneratorSyntaxContext ctx)
    {
        if (ctx.Node is not ClassDeclarationSyntax declaration ||
            ctx.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol symbol)
        {
            return null;
        }

        // Abstract or generic cannot be closed over; a user type also needs the parameterless
        // constructor Identity's stores use to materialise one.
        if (symbol.IsAbstract || symbol.IsStatic || symbol.IsGenericType || !DerivesFromIdentityUser(symbol))
        {
            return null;
        }

        if (!symbol.InstanceConstructors.Any(static c =>
                c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public))
        {
            return null;
        }

        return new Candidate(
            symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            SymbolLocation.From(symbol));
    }

    private static bool DerivesFromIdentityUser(INamedTypeSymbol symbol)
    {
        for (var current = symbol.BaseType; current is not null; current = current.BaseType)
        {
            if (current.Name == IdentityUserBase &&
                current.ContainingNamespace?.ToDisplayString() == IdentityNamespace)
            {
                return true;
            }
        }

        return false;
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Candidate> candidates)
    {
        if (candidates.IsDefaultOrEmpty)
        {
            return;
        }

        var users = candidates
            .Distinct()
            .OrderBy(static c => c.FullyQualifiedName, StringComparer.Ordinal)
            .ToList();

        if (users.Count > 1)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                Rask074,
                users[1].Location?.ToLocation(),
                users[0].FullyQualifiedName,
                users[1].FullyQualifiedName));
            return;
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.AppendLine("namespace Rask.Auth.Generated;");
        source.AppendLine();
        source.AppendLine("/// <summary>Names this assembly's account type to Rask.Auth.</summary>");
        source.AppendLine("internal static class __RaskAuthUser");
        source.AppendLine("{");
        source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        source.Append("    internal static void Initialize() => global::Rask.Auth.AuthUser.Use<")
            .Append(users[0].FullyQualifiedName).AppendLine(">();");
        source.AppendLine("}");

        context.AddSource("__RaskAuthUser.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private readonly record struct Candidate(string FullyQualifiedName, SymbolLocation? Location);
}
