using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Rask.Generators.Shared;

namespace Rask.Batteries.Generators;

public sealed partial class ModelInputGenerator
{
    private static string Render(Entity entity)
    {
        // What `public const ModelWrites Writes` narrows. It reaches the FORM surface only: the behaviour
        // writes below take no model, and the read face is generated elsewhere and not negotiable.
        var formCreate = (entity.Writes & CreateWrite) != 0;
        var formUpdate = (entity.Writes & UpdateWrite) != 0;
        var formModel = entity.Writes != NoWrites;

        // A child is created, changed and removed as part of the aggregate that holds it — never off its own
        // type — so it gets the model and the plumbing, and none of the writes.
        var idLessCreate = !entity.IsChild && IdLessCreate(entity);
        var createWithId = !entity.IsChild && CreateWithId(entity);

        var s = new StringBuilder();
        s.AppendLine("// <auto-generated/>");
        s.AppendLine("#nullable enable");
        s.AppendLine();

        if (entity.Namespace.Length > 0)
        {
            s.Append("namespace ").Append(entity.Namespace).AppendLine(";");
            s.AppendLine();
        }

        var modelMark = s.Length;
        AppendModel(s, entity, idLessCreate, createWithId);
        Keep(s, formModel, modelMark);

        AppendWrites(s, entity, idLessCreate, createWithId, formCreate, formUpdate, formModel);

        var toModelMark = s.Length;
        AppendToModel(s, entity);
        Keep(s, formModel, toModelMark);

        var plumbingMark = s.Length;
        AppendValidate(s, entity);
        AppendApply(s, entity);
        AppendFill(s, entity);
        AppendToModelByName(s, entity);

        // Everything above reads or writes a MODEL, so it goes with one. Everything below is still needed:
        // a behaviour create constructs the entity through __New and stamps its key, neither of which is a
        // form write.
        Keep(s, formModel, plumbingMark);

        AppendEntityPlumbing(s, entity);

        var accessorMark = s.Length;
        AppendModelAccessors(s, entity);
        Keep(s, formModel, accessorMark);

        s.AppendLine("}");

        var rulesMark = s.Length;
        AppendFieldRules(s, entity);
        Keep(s, formModel, rulesMark);

        return s.ToString();
    }

    private static string FormModelType(Entity entity) =>
        (entity.Namespace.Length == 0 ? "global::" : "global::" + entity.Namespace + ".") + entity.Name + ModelSuffix;

    // A section is written and then dropped rather than guarded line by line, so there is ONE piece of
    // code deciding what a form write looks like instead of two that have to agree about it.
    private static void Keep(StringBuilder s, bool wanted, int from)
    {
        if (!wanted)
        {
            s.Length = from;
        }
    }

    private static void AppendModel(StringBuilder s, Entity entity, bool idLessCreate, bool createWithId)
    {
        var modelName = entity.Name + ModelSuffix;
        AppendModelSummary(s, entity, idLessCreate, createWithId);
        s.Append(entity.Accessibility).Append(" sealed partial class ").AppendLine(modelName);
        s.AppendLine("{");
        AppendModelConstructors(s, entity);
        AppendSelfKey(s, entity);
        AppendModelLists(s, entity);
        AppendModelMembers(s, entity);

        s.AppendLine("}");
        s.AppendLine();
    }

    private static void AppendModelSummary(StringBuilder s, Entity entity, bool idLessCreate, bool createWithId)
    {
        var entityType = entity.FullyQualifiedName;
        s.Append("/// <summary>The form model for <see cref=\"").Append(entityType)
            .AppendLine("\" />, generated by Rask from its mapped properties.</summary>");
        s.AppendLine("/// <remarks>");
        // Names only the writes this entity actually got — a model without a parameterless constructor has
        // no Create at all, one whose key only the caller can supply has no id-less one, and one without
        // no id has none to create or update by.
        var writes = new List<string>();
        if (idLessCreate)
        {
            writes.Add("<c>" + entity.Name + ".Create(model)</c>");
        }

        if (createWithId)
        {
            writes.Add("<c>" + entity.Name + ".Create(id, model)</c>");
        }

        if (!entity.IsChild && entity.IdTypeName is not null)
        {
            writes.Add("<c>" + entity.Name + ".Update(id, model)</c>");
        }

        s.Append("/// Bind it with <c>Form.Model(model)</c>")
            .Append(writes.Count == 0 ? "" : "; persist it with " + JoinWrites(writes))
            .AppendLine(".");
        if (entity.IsChild)
        {
            s.Append("/// It is a CHILD model: it belongs to the <c>")
                .Append(entity.Name)
                .AppendLine("</c> list on its aggregate's model, and is saved with it.");
            s.AppendLine("/// It carries an <c>Id</c> so a save knows which stored child each row is — a row with none is a new one.");
        }
        else if (entity.IdTypeName is not null)
        {
            s.AppendLine("/// It carries no id: the id is passed beside it, so a posted form cannot point a write at another row.");
        }

        s.AppendLine("/// Every property is nullable so a field can be empty; one whose column cannot be is required, and a null clears the rest.");
        s.AppendLine("/// </remarks>");
    }

    private static void AppendModelConstructors(StringBuilder s, Entity entity)
    {
        var entityType = entity.FullyQualifiedName;
        var modelName = entity.Name + ModelSuffix;
        if (entity.Constructible)
        {
            s.Append("    /// <summary>A model holding <see cref=\"").Append(entityType)
                .AppendLine("\" />'s own defaults — what its constructor and property initializers set.</summary>");
            s.Append("    public ").Append(modelName).Append("() => ").Append(modelName)
                .AppendLine("Extensions.__Fill(this, " + modelName + "Extensions.__Defaults());");
            s.AppendLine();
            s.AppendLine("    /// <summary>A model with no values yet, filled by the generated <c>ToModel()</c>.</summary>");
            s.Append("    internal ").Append(modelName).AppendLine("(bool blank) => _ = blank;");
            s.AppendLine();
        }

        if (entity.IsChild && entity.IdTypeName is not null)
        {
            s.Append("    /// <summary>Which stored <see cref=\"").Append(entityType)
                .AppendLine("\" /> this row is, or <c>null</c> for one the form just added.</summary>");
            s.AppendLine("    /// <remarks>");
            s.AppendLine("    /// Safe to post, unlike an aggregate's own id: it only ever picks a child of the aggregate being");
            s.AppendLine("    /// saved. An id that matches none of them is treated as a new child rather than followed.");
            s.AppendLine("    /// </remarks>");
            s.Append("    public ").Append(entity.IdTypeName).AppendLine("? Id { get; set; }");
            s.AppendLine();
        }
    }

    private static void AppendModelLists(StringBuilder s, Entity entity)
    {
        var entityType = entity.FullyQualifiedName;
        foreach (var child in entity.Children)
        {
            s.Append("    /// <summary>The form models of <see cref=\"").Append(entityType).Append('.')
                .Append(child.Name).AppendLine("\" />.</summary>");
            s.AppendLine("    /// <remarks>");
            s.AppendLine("    /// <b>What this list holds is what the aggregate holds after the save.</b> A row with no");
            s.AppendLine("    /// <c>Id</c> is added, a row whose <c>Id</c> matches a stored child updates it, and a stored");
            s.AppendLine("    /// child whose id is in none of these rows is REMOVED — so a form that posts a subset deletes");
            s.AppendLine("    /// the rest, and an empty list deletes them all.");
            s.AppendLine("    /// </remarks>");
            s.Append("    public global::System.Collections.Generic.List<").Append(child.ChildModelName)
                .Append("> ").Append(child.Name).AppendLine(" { get; set; } = [];");
            s.AppendLine();
        }

        foreach (var collection in entity.ValueCollections)
        {
            s.Append("    /// <summary>The form values of <see cref=\"").Append(entityType).Append('.')
                .Append(collection.Name).AppendLine("\" />.</summary>");
            s.AppendLine("    /// <remarks>");
            s.AppendLine("    /// <b>What this list holds is what the aggregate holds after the save.</b> These are values,");
            s.AppendLine("    /// so there is no id to match on and nothing to reconcile: the stored collection is replaced by");
            s.AppendLine("    /// this one, and an empty list clears it.");
            s.AppendLine("    /// </remarks>");
            s.Append("    public global::System.Collections.Generic.List<")
                .Append(ElementModelType(collection)).Append("> ").Append(collection.Name)
                .AppendLine(" { get; set; } = [];");
            s.AppendLine();
        }
    }

    private static void AppendModelMembers(StringBuilder s, Entity entity)
    {
        var entityType = entity.FullyQualifiedName;
        foreach (var member in entity.Members)
        {
            s.Append("    /// <summary>The form value of <see cref=\"").Append(entityType).Append('.')
                .Append(member.Name).AppendLine("\" />.</summary>");
            foreach (var attribute in member.Attributes)
            {
                s.Append("    ").AppendLine(attribute);
            }

            s.Append("    public ").Append(member.ModelType).Append(' ').Append(member.Name).AppendLine(" { get; set; }");
            s.AppendLine();
        }

        foreach (var valueObject in entity.ValueObjects.Where(static v => !v.SingleValue))
        {
            s.Append("    /// <summary>The form model for <see cref=\"").Append(valueObject.TypeName)
                .AppendLine("\" />.</summary>");
            s.Append("    public sealed partial class ").AppendLine(valueObject.ModelName);
            s.AppendLine("    {");
            foreach (var member in valueObject.Members)
            {
                s.Append("        /// <summary>The form value of <see cref=\"").Append(valueObject.TypeName)
                    .Append('.').Append(member.Name).AppendLine("\" />.</summary>");
                foreach (var attribute in member.Attributes)
                {
                    s.Append("        ").AppendLine(attribute);
                }

                s.Append("        public ").Append(member.ModelType).Append(' ').Append(member.Name).AppendLine(" { get; set; }");
            }

            s.AppendLine("    }");
            s.AppendLine();
        }
    }

    // The form loop's fill. Deliberately not a read-face query: the read face is flat primitives and
    // the form model keeps value objects nested, so this loads the aggregate and reuses __Fill rather
    // than maintaining a second projection that could drift from it.
    private static void AppendModelFill(StringBuilder s, Entity entity, string idType, bool formModel)
    {
        var entityType = entity.FullyQualifiedName;
        var modelType = FormModelType(entity);
        var modelFillMark = s.Length;
        s.Append("        /// <summary>The edit shape of the <see cref=\"").Append(entityType)
            .AppendLine("\" /> with <paramref name=\"id\" />, ready to bind to a form.</summary>");
        s.AppendLine("        /// <param name=\"id\">The id of the row to fill the form from.</param>");
        s.AppendLine("        /// <param name=\"db\">The context to read through, or <c>null</c> to open one. A given context is not disposed.</param>");
        s.AppendLine("        /// <param name=\"cancellationToken\">Cancels the load.</param>");
        s.Append("        /// <returns>The model, or <c>null</c> when no <see cref=\"").Append(entityType)
            .AppendLine("\" /> has that id.</returns>");
        s.AppendLine("        /// <remarks>");
        s.Append("        ///     The aggregate is loaded whole, so its children arrive as child models. A soft-deleted")
            .AppendLine();
        s.AppendLine("        ///     row is not found, exactly as it is not found by a query.");
        s.AppendLine("        /// </remarks>");
        s.Append("        public static async ").Append(TaskFqn).Append('<').Append(modelType)
            .Append("?> Model(").Append(idType).Append(" id, ").Append(DbParameter).Append(TokenFqn)
            .AppendLine(" cancellationToken = default)");
        s.AppendLine("        {");
        s.Append("            var entity = await ").Append(WritesFqn).Append(".ModelSource<").Append(entityType)
            .AppendLine(">(id!, db, cancellationToken).ConfigureAwait(false);");
        s.AppendLine("            return entity?.ToModel();");
        s.AppendLine("        }");

        Keep(s, formModel, modelFillMark);
    }

    private static void AppendToModel(StringBuilder s, Entity entity)
    {
        var entityType = entity.FullyQualifiedName;
        var modelType = FormModelType(entity);
        s.Append("    extension(").Append(entityType).AppendLine(" entity)");
        s.AppendLine("    {");
        s.Append("        /// <summary>Copies this aggregate into a new <see cref=\"").Append(modelType)
            .AppendLine("\" />, ready to bind to an edit form.</summary>");
        s.Append("        public ").Append(modelType).AppendLine(" ToModel()");
        s.AppendLine("        {");
        s.Append("            var model = new ").Append(modelType).AppendLine(entity.Constructible ? "(blank: true);" : "();");
        s.AppendLine("            __Fill(model, entity);");
        if (HasSelfKey(entity))
        {
            s.AppendLine("            model.__Key = entity.Id;");
        }

        s.AppendLine("            return model;");
        s.AppendLine("        }");
        s.AppendLine("    }");
        s.AppendLine();
    }

    // ---- plumbing ----
    // A model save writes what the form holds. A null clears a property the aggregate declares nullable — the user
    // emptied that field; a non-nullable scalar cannot be null here, since __Validate has refused the model first. A
    // nested value-object model merges what it gives over the value object the aggregate holds.
    // The server's own check of what a form posted: the attributes the form validates with, run directly — no
    // reflection, so a trimmed app keeps every one — before anything is written.
    private static void AppendValidate(StringBuilder s, Entity entity)
    {
        var modelType = FormModelType(entity);
        s.Append("    internal static void __Validate(").Append(modelType).AppendLine(" model)");
        s.AppendLine("    {");
        s.AppendLine("        global::System.Collections.Generic.List<string>? errors = null;");
        foreach (var member in entity.Members.Where(static m => m.Role == ModelMemberRole.Value && m.Write is not null))
        {
            foreach (var check in member.Checks)
            {
                s.Append("        __Check(").Append(check).Append(", model.").Append(member.Name).Append(", \"")
                    .Append(member.Name).AppendLine("\", model, ref errors);");
            }
        }

        s.AppendLine("        if (errors is not null)");
        s.AppendLine("        {");
        s.AppendLine("            throw new global::System.ComponentModel.DataAnnotations.ValidationException(string.Join(\" \", errors));");
        s.AppendLine("        }");
        s.AppendLine("    }");
        s.AppendLine();
        s.Append("    private static void __Check(global::System.ComponentModel.DataAnnotations.ValidationAttribute check, ")
            .Append("object? value, string name, ").Append(modelType)
            .AppendLine(" model, ref global::System.Collections.Generic.List<string>? errors)");
        s.AppendLine("    {");
        s.AppendLine("        // The trim-safe context: it names the model without reflecting over it.");
        s.AppendLine("        var context = new global::System.ComponentModel.DataAnnotations.ValidationContext(model, name, null, null) { MemberName = name };");
        s.AppendLine("        if (check.GetValidationResult(value, context) is { ErrorMessage: { } error })");
        s.AppendLine("        {");
        s.AppendLine("            (errors ??= []).Add(error);");
        s.AppendLine("        }");
        s.AppendLine("    }");
        s.AppendLine();
    }

    private static void AppendApply(StringBuilder s, Entity entity)
    {
        var entityType = entity.FullyQualifiedName;
        var modelType = FormModelType(entity);
        s.Append("    internal static void __Apply(").Append(entityType).Append(" entity, ").Append(modelType)
            .AppendLine(" model)");
        s.AppendLine("    {");
        var local = 0;
        foreach (var member in entity.Members.Where(static m => m.Role == ModelMemberRole.Value && m.Write is not null))
        {
            var given = "__v" + (local++).ToString(CultureInfo.InvariantCulture);
            var value = member.ValueObject switch
            {
                null => given,
                { SingleValue: true } single => BuildExpression(single, _ => given),
                { } valueObject => MergeExpression(given, "entity." + member.Name, valueObject, member.Nullable, ref local),
            };

            s.Append("        if (model.").Append(member.Name).Append(" is { } ").Append(given).AppendLine(")");
            s.AppendLine("        {");
            s.Append("            ").AppendLine(Assignment(member.Write!, "entity", member.Name, value));
            s.AppendLine("        }");

            if (member.Nullable)
            {
                s.AppendLine("        else");
                s.AppendLine("        {");
                s.Append("            ").AppendLine(Assignment(member.Write!, "entity", member.Name, "null"));
                s.AppendLine("        }");
            }
        }

        foreach (var child in entity.Children)
        {
            EmitChildSync(s, child);
        }

        foreach (var collection in entity.ValueCollections)
        {
            EmitValueCollectionSync(s, collection);
        }

        s.AppendLine("    }");
        s.AppendLine();
    }

    private static void AppendFill(StringBuilder s, Entity entity)
    {
        var entityType = entity.FullyQualifiedName;
        var modelType = FormModelType(entity);
        s.Append("    internal static void __Fill(").Append(modelType).Append(" model, ").Append(entityType).AppendLine(" entity)");
        s.AppendLine("    {");
        foreach (var member in entity.Members)
        {
            var value = member.ValueObject is null
                ? "entity." + member.Name
                : ToModelExpression("entity." + member.Name, member.ValueObject, member.Nullable, modelType);
            s.Append("        model.").Append(member.Name).Append(" = ").Append(value).AppendLine(";");
        }

        foreach (var child in entity.Children)
        {
            s.Append("        model.").Append(child.Name).Append(" = new global::System.Collections.Generic.List<")
                .Append(child.ChildModelName).AppendLine(">();");
            s.Append("        foreach (var __child in entity.").Append(child.Name).AppendLine(")");
            s.AppendLine("        {");
            s.Append("            var __childModel = ").Append(child.ChildModelName)
                .AppendLine("Extensions.__ToModel(__child);");
            s.AppendLine("            __childModel.Id = __child.Id;");
            s.Append("            model.").Append(child.Name).AppendLine(".Add(__childModel);");
            s.AppendLine("        }");
            s.AppendLine();
        }

        foreach (var collection in entity.ValueCollections)
        {
            s.Append("        model.").Append(collection.Name)
                .Append(" = new global::System.Collections.Generic.List<")
                .Append(ElementModelType(collection, modelType)).AppendLine(">();");
            s.Append("        foreach (var __value in entity.").Append(collection.Name).AppendLine(")");
            s.AppendLine("        {");
            s.Append("            model.").Append(collection.Name).Append(".Add(")
                // The trailing `!` because ToModelExpression guards a reference-typed value object against
                // null, and an element of the collection is never null — the list holds values, not slots.
                .Append(collection.ElementModel switch
                {
                    { SingleValue: false } elementShape => ToModelExpression("__value", elementShape, nullable: false, modelType) + "!",
                    { } single => ToModelExpression("__value", single, nullable: false, modelType),
                    null => "__value",
                })
                .AppendLine(");");
            s.AppendLine("        }");
            s.AppendLine();
        }

        s.AppendLine("    }");

        s.AppendLine();
    }

    // The same thing ToModel() does, callable by name: a parent fills its children through this rather than
    // through the extension member, which would have to be in scope where the parent's file is generated.
    private static void AppendToModelByName(StringBuilder s, Entity entity)
    {
        var entityType = entity.FullyQualifiedName;
        var modelType = FormModelType(entity);
        s.Append("    internal static ").Append(modelType).Append(" __ToModel(").Append(entityType)
            .AppendLine(" entity)");
        s.AppendLine("    {");
        s.Append("        var model = new ").Append(modelType).AppendLine(entity.Constructible ? "(blank: true);" : "();");
        s.AppendLine("        __Fill(model, entity);");
        s.AppendLine("        return model;");
        s.AppendLine("    }");
    }

    private static void AppendEntityPlumbing(StringBuilder s, Entity entity)
    {
        var entityType = entity.FullyQualifiedName;
        if (entity.Constructible)
        {
            s.AppendLine();
            s.Append("    internal static ").Append(entityType).AppendLine(" __Defaults() => __New();");
            s.AppendLine();
            s.Append("    [").Append(UnsafeAccessor).Append('(').Append(UnsafeAccessorKind).AppendLine(".Constructor)]");
            s.Append("    private static extern ").Append(entityType).AppendLine(" __New();");
        }

        // What a parent's sync creates for a posted row that matches no stored child: a new child carrying the
        // key its own type assigns, never the one the form sent.
        if (entity.IsChild && entity.Constructible)
        {
            s.AppendLine();
            s.Append("    internal static ").Append(entityType).AppendLine(" __NewChild()");
            s.AppendLine("    {");
            AppendNewEntity(s, entity, withId: false);
            s.AppendLine("        return entity;");
            s.AppendLine("    }");
        }

        foreach (var collection in entity.ValueCollections.Where(static c => c.ThroughField))
        {
            s.AppendLine();
            s.Append("    /// <summary>The field behind <c>").Append(collection.Name)
                .AppendLine("</c>, which hands out a read-only view.</summary>");
            s.Append("    [").Append(UnsafeAccessor).Append('(').Append(UnsafeAccessorKind)
                .Append(".Field, Name = \"").Append(collection.FieldName).AppendLine("\")]");
            s.Append("    private static extern ref ").Append(collection.FieldTypeName).Append(" __Values_")
                .Append(collection.Name).Append('(').Append(entityType).AppendLine(" entity);");
        }

        foreach (var child in entity.Children.Where(static c => c.ThroughField))
        {
            s.AppendLine();
            s.Append("    /// <summary>The field behind <c>").Append(child.Name)
                .AppendLine("</c>, which hands out a read-only view.</summary>");
            s.Append("    [").Append(UnsafeAccessor).Append('(').Append(UnsafeAccessorKind)
                .Append(".Field, Name = \"").Append(child.FieldName).AppendLine("\")]");
            s.Append("    private static extern ref ").Append(child.FieldTypeName).Append(" __Field_")
                .Append(child.Name).Append('(').Append(entityType).AppendLine(" entity);");
        }

        if (entity.KeyWrite is { Kind: not ModelWriteKind.Public } key)
        {
            EmitAccessor(s, key, "Id");
        }
    }

    private static void AppendModelAccessors(StringBuilder s, Entity entity)
    {
        foreach (var member in entity.Members)
        {
            if (member.Write is { Kind: not ModelWriteKind.Public } write)
            {
                EmitAccessor(s, write, member.Name);
            }
        }

        foreach (var valueObject in entity.ValueObjects)
        {
            EmitValueObjectBuild(s, valueObject);
        }
    }

    private static void AppendKeyRemarks(StringBuilder s, Entity entity)
    {
        switch (entity.KeySource)
        {
            case KeySource.Guid:
                s.AppendLine("        /// <remarks>The key is a new version-7 <see cref=\"global::System.Guid\" />, unless the constructor already set one.</remarks>");
                break;
            case KeySource.Store:
                s.AppendLine("        /// <remarks>The key is assigned by the database when the row is inserted.</remarks>");
                break;
        }
    }

    // `var entity = __New();` and its key — the caller's for an id overload, a new version-7 Guid when nothing set one,
    // or nothing at all where the store assigns it.
    private static void AppendNewEntity(StringBuilder s, Entity entity, bool withId)
    {
        if (withId && entity.KeyIsReference)
        {
            s.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(id);");
        }

        s.AppendLine("            var entity = __New();");

        if (withId)
        {
            s.Append("            ").AppendLine(Assignment(entity.KeyWrite!, "entity", "Id", "id"));
        }
        else if (entity.KeySource == KeySource.Guid && entity.KeyWrite is { } generatedKey)
        {
            s.Append("            if (global::System.Collections.Generic.EqualityComparer<").Append(entity.IdTypeName)
                .AppendLine(">.Default.Equals(entity.Id, default!))");
            s.AppendLine("            {");
            s.Append("                ").AppendLine(Assignment(generatedKey, "entity", "Id", entity.KeyFactory!));
            s.AppendLine("            }");
        }
    }

    // Create(model) exists only where a key can be produced without the caller (see KeySourceOf); the Guid
    // case needs a way into Entity<TId>.Id to put it there.
    private static bool IdLessCreate(Entity entity) =>
        entity.Constructible && entity.KeySource switch
        {
            KeySource.None or KeySource.Store => true,
            KeySource.Guid => entity.KeyWrite is not null,
            _ => false,
        };

    // Not for a key the store generates: an explicit value in an identity column is refused on SQL Server
    // (IDENTITY_INSERT is off) and, on PostgreSQL, accepted without moving the sequence — which then collides.
    private static bool CreateWithId(Entity entity) =>
        entity.Constructible && entity.IdTypeName is not null && entity.KeyWrite is not null &&
        entity.KeySource != KeySource.Store;
}
