<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rask.Core\Rask.Core.csproj"/>
    <ProjectReference Include="..\Rask.Validation.DataAnnotations\Rask.Validation.DataAnnotations.csproj"/>
    <ProjectReference Include="..\Rask.Validation.FluentValidation\Rask.Validation.FluentValidation.csproj"/>
    <ProjectReference Include="..\Rask.Generators\Rask.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MinVer" Version="7.0.0" />
  </ItemGroup>

</Project>
