<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rask.Core\Rask.Core.csproj"/>
    <ProjectReference Include="..\Rask.Generators\Rask.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="build\**" Pack="true" PackagePath="build\"/>
  </ItemGroup>

</Project>
