using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Rask.Cqrs.Generators;

/// <summary>One remote message, reduced to what the TypeScript side needs to know about it.</summary>
internal sealed class TypeScriptContract
{
    public string WireName { get; set; } = string.Empty;

    /// <summary>The verb the transport uses: <c>query</c>, <c>command</c> or <c>notification</c>.</summary>
    public string Kind { get; set; } = string.Empty;

    public WireType Message { get; set; } = null!;

    /// <summary>Null for a message that answers with nothing.</summary>
    public WireType? Result { get; set; }

    public bool ReturnsFile { get; set; }

    /// <summary>
    ///     The wire names of the message's file-carrying properties, in declaration order.
    /// </summary>
    /// <remarks>
    ///     Order is the contract: the server pairs a multipart part with a property by the index the
    ///     message reserved for it. Getting the order wrong does not fail — it hands the handler
    ///     somebody else's file.
    /// </remarks>
    public IReadOnlyList<string> FileProperties { get; set; } = [];
}

/// <summary>
///     Renders the two TypeScript files a front end consumes: the types, and the message factories
///     that bind a wire name to its payload and result.
/// </summary>
internal static class TypeScriptModule
{
    private const string Header =
        "// <auto-generated> by Rask. Regenerated on every build; edits are lost. </auto-generated>\n";

    /// <summary>
    ///     The aliases for wire forms that are strings rather than instants.
    /// </summary>
    /// <remarks>
    ///     Named rather than inlined as <c>string</c> so the intent survives into the editor: a
    ///     signature that says <c>DateOnly</c> tells a reader it is a calendar date and not a
    ///     timestamp, which is exactly the distinction that goes wrong otherwise.
    /// </remarks>
    private const string Aliases = """
        /** A GUID, as its canonical string form. */
        export type Guid = string;
        /** A calendar date, `YYYY-MM-DD`. Deliberately not a Date: `new Date("2026-08-25")` is UTC
         *  midnight, so anyone west of UTC would render it as the 24th. */
        export type DateOnly = string;
        /** A time of day, `HH:mm:ss.fffffff`. Seven fractional digits, which `Date` cannot parse. */
        export type TimeOnly = string;
        /** A length of time, `[-][d.]hh:mm:ss[.fffffff]`. Not an ISO-8601 duration. */
        export type Duration = string;
        /** Bytes, base64-encoded. */
        export type Base64 = string;
        """;

    public static (string Contracts, string Messages) Build(IReadOnlyList<TypeScriptContract> contracts)
    {
        var emitter = new TypeScriptEmitter();
        var factories = new StringBuilder();
        var imported = new SortedSet<string>(System.StringComparer.Ordinal);

        foreach (var contract in contracts.OrderBy(c => c.WireName, System.StringComparer.Ordinal))
        {
            var payload = emitter.Ensure(contract.Message);
            var result = ResultType(emitter, contract);

            Remember(imported, payload);
            Remember(imported, result);

            factories.AppendLine(Factory(contract, payload, result, ResultShape(emitter, contract)));
        }

        return (BuildContracts(emitter), BuildMessages(factories.ToString(), imported));
    }

    private static string ResultType(TypeScriptEmitter emitter, TypeScriptContract contract)
    {
        if (contract.ReturnsFile)
        {
            // The handler streams a file rather than JSON, so the client hands back a download.
            return "RaskDownload";
        }

        return contract.Result is { } result ? emitter.Ensure(result) : "void";
    }

    /// <summary>
    ///     The named shape the answer revives against, and how many containers stand in front of it.
    /// </summary>
    /// <remarks>
    ///     A shape with nothing to revive returns null rather than its name: carrying it would make
    ///     the client walk every property of every response of that type to discover there is nothing
    ///     to do. <see cref="ShapeDescriptor.IsEmpty" /> is transitive — a shape holding a shape that
    ///     holds a date is not empty — so this cannot skip a walk that was needed.
    /// </remarks>
    private static NestedShape? ResultShape(TypeScriptEmitter emitter, TypeScriptContract contract)
    {
        if (contract.ReturnsFile || contract.Result is not { } result)
        {
            return null;
        }

        var inner = result;
        var depth = 0;
        while (inner.Kind is WireKind.Nullable or WireKind.Sequence or WireKind.Dictionary)
        {
            if (inner.Kind != WireKind.Nullable)
            {
                depth++;
            }

            inner = inner.Inner!;
        }

        if (inner.Kind != WireKind.Object)
        {
            return null;
        }

        var name = emitter.Ensure(inner);
        return emitter.Shapes.TryGetValue(name, out var shape) && !shape.IsEmpty
            ? new NestedShape(name, depth)
            : null;
    }

    /// <summary>Records a named type so <c>messages.ts</c> imports exactly what it references.</summary>
    private static void Remember(SortedSet<string> imported, string expression)
    {
        foreach (var token in expression.Split(['[', ']', '|', '<', '>', ',', ' ', '(', ')'])
                     .Where(t => t.Length > 0))
        {
            // Anything that is not a built-in or a primitive is a name contracts.ts declares.
            if (token is "null" or "void" or "number" or "string" or "boolean" or "unknown"
                or "Record" or "Date" or "File" or "Blob" or "RaskDownload")
            {
                continue;
            }

            imported.Add(token);
        }
    }

    private static string Factory(
        TypeScriptContract contract,
        string payload,
        string result,
        NestedShape? resultShape)
    {
        var name = CamelCase(Leaf(contract.WireName));
        var spec = new StringBuilder();
        spec.Append("  name: '").Append(contract.WireName).Append("',\n");
        spec.Append("  kind: '").Append(contract.Kind).Append("',\n");

        if (contract.FileProperties.Count > 0)
        {
            spec.Append("  files: [")
                .Append(string.Join(", ", contract.FileProperties.Select(p => "'" + p + "'")))
                .Append("],\n");
        }

        if (contract.ReturnsFile)
        {
            spec.Append("  returnsFile: true,\n");
        }

        if (resultShape is { } shape)
        {
            spec.Append("  result: ['").Append(shape.Name).Append("', ")
                .Append(shape.Depth.ToString(CultureInfo.InvariantCulture)).Append("],\n");
        }

        return "export const " + name + " = message<" + payload + ", " + result + ", '" + contract.Kind
               + "'>({\n" + spec + "});\n";
    }

    private static string BuildContracts(TypeScriptEmitter emitter)
    {
        var sb = new StringBuilder();
        sb.Append(Header).AppendLine();
        sb.AppendLine(Aliases).AppendLine();
        sb.Append(emitter.Declarations);

        sb.AppendLine("""
            /**
             * Which properties of each shape carry an instant, and which lead to another shape.
             *
             * The client revives exactly these into `Date` objects. It does not sniff strings: a regex
             * reviver converts a product code or an ETag that merely looks like a timestamp, silently.
             * Nothing here is guessed — the C# type said so.
             *
             * The number beside a nested shape is how many arrays or dictionaries stand between the
             * property and it. Both arrive as plain objects in JSON, so without the count the runtime
             * would revive a dictionary's keys as if they were the shape's own properties.
             */
            """);

        sb.AppendLine("export const shapes = {");
        foreach (var entry in emitter.Shapes.OrderBy(s => s.Key, System.StringComparer.Ordinal))
        {
            var name = entry.Key;
            var shape = entry.Value;
            if (shape.IsEmpty)
            {
                // Nothing to do at runtime, so nothing to carry.
                continue;
            }

            sb.Append("  ").Append(name).Append(": { instants: [")
                .Append(string.Join(", ", shape.Instants.Select(i => "'" + i + "'")))
                .Append("], nested: {")
                .Append(string.Join(
                    ", ",
                    shape.Nested.Select(n =>
                        " " + n.Key + ": ['" + n.Value.Name + "', "
                        + n.Value.Depth.ToString(CultureInfo.InvariantCulture) + "]")))
                .AppendLine(shape.Nested.Count > 0 ? " } }," : "} },");
        }

        sb.AppendLine("} as const;");
        return sb.ToString();
    }

    private static string BuildMessages(string factories, SortedSet<string> imported)
    {
        var sb = new StringBuilder();
        sb.Append(Header).AppendLine();
        sb.AppendLine("import { message, registerShapes } from './client';");
        sb.AppendLine("import { shapes } from './contracts';");

        if (imported.Count > 0)
        {
            sb.Append("import type { ").Append(string.Join(", ", imported)).AppendLine(" } from './contracts';");
        }

        sb.AppendLine();
        sb.AppendLine("""
            // Handed to the client here rather than imported by it, so client.ts stays independent of
            // the generated files: a scaffolded app type-checks before its first build has produced
            // any. Importing this module is what arms date revival, which is why every call site
            // reaches the server through a factory from here.
            registerShapes(shapes);
            """);
        sb.AppendLine();
        sb.Append(factories);
        return sb.ToString();
    }

    /// <summary>The type name without its namespace, which is what a factory is named after.</summary>
    private static string Leaf(string wireName)
    {
        var dot = wireName.LastIndexOf('.');
        return dot >= 0 ? wireName.Substring(dot + 1) : wireName;
    }

    /// <summary>
    ///     Lower-cases the first letter, so the factory does not collide with the interface of the
    ///     same name in <c>contracts.ts</c>.
    /// </summary>
    /// <remarks>
    ///     The factory yields, not the type: a signature reads better naming the shape than the verb,
    ///     and the type is what shows in an editor tooltip.
    /// </remarks>
    private static string CamelCase(string name) =>
        name.Length == 0
            ? name
            : char.ToLowerInvariant(name[0]).ToString(CultureInfo.InvariantCulture) + name.Substring(1);
}
