using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace Rask.External.Tasks;

/// <summary>One island, as the bundler needs to see it.</summary>
internal sealed class ExternalEntry
{
    /// <summary>The island's name — the key the browser resolves a module by.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Absolute path to the front-end file sitting beside the C# class.</summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>Which adapter wraps it — a key from <see cref="ExternalRuntime.All" />.</summary>
    public string Runtime { get; set; } = ExternalRuntime.React.Key;
}

/// <summary>
///     Writes the bundler's inputs: one entry module per island, and the config that builds them.
/// </summary>
/// <remarks>
///     <para>
///         The generated entry is what keeps a component ordinary. It imports the author's file and
///         wraps it with its runtime's adapter, so <c>Chart.tsx</c> stays a plain React component with
///         no Rask import in it and no knowledge that it is an island at all.
///     </para>
///     <para>
///         Plain string generation in C# rather than MSBuild, for the same reason the CQRS TypeScript
///         is: this is testable, and an MSBuild property carrying a JavaScript object literal is not.
///     </para>
/// </remarks>
internal static class ExternalBuildPlan
{
    private const string Header =
        "// <auto-generated> by Rask. Regenerated on every build; edits are lost. </auto-generated>";

    /// <summary>The entry module that pairs an island's component with its adapter.</summary>
    /// <remarks>
    ///     One shape for every runtime, which is what the table buys: bind the author's default export
    ///     to a name, wrap it with that runtime's factory, re-export. The runtimes differ only in what
    ///     the default export IS — a component everywhere else, a registered tag NAME for Lit, because
    ///     a custom element registers its own tag and nothing about the file reveals it. Importing the
    ///     module is also what runs that registration side effect.
    /// </remarks>
    /// <exception cref="InvalidOperationException">The island names a runtime nothing declares.</exception>
    public static string EntryModule(ExternalEntry island, string adapterDirectory)
    {
        var runtime = ExternalRuntime.Find(island.Runtime)
                      ?? throw new InvalidOperationException(
                          $"Island '{island.Name}' names the runtime '{island.Runtime}', which Rask has no adapter "
                          + $"for. Known runtimes: {ExternalRuntime.KeyList}.");

        var source = Specifier(island.Source);
        var adapter = Specifier(Path.Combine(adapterDirectory, runtime.AdapterModule));

        return $$"""
            {{Header}}
            import {{runtime.ImportName}} from '{{source}}'
            import { {{runtime.AdapterFactory}} } from '{{adapter}}'

            export default {{runtime.AdapterFactory}}({{runtime.ImportName}})

            """;
    }

    /// <summary>
    ///     The Vite config that builds one chunk per island and writes the runtime's manifest.
    /// </summary>
    /// <param name="islands">The islands, already paired with their entry files.</param>
    /// <param name="entryDirectory">Where the generated entry modules live.</param>
    /// <param name="outputDirectory">Where the built chunks land.</param>
    /// <param name="manifestPath">The manifest file <c>rask-external.js</c> fetches.</param>
    /// <param name="publicBase">The URL prefix the built files are served from.</param>
    /// <param name="tsConfigPath">The app's tsconfig, for the one plugin that needs to be told. May be null.</param>
    /// <exception cref="InvalidOperationException">
    ///     The islands name a combination no config can express — see <see cref="Refuse" />.
    /// </exception>
    public static string ViteConfig(
        IReadOnlyList<ExternalEntry> islands,
        string entryDirectory,
        string outputDirectory,
        string manifestPath,
        string publicBase,
        string? tsConfigPath = null)
    {
        var input = new StringBuilder();
        foreach (var island in islands)
        {
            var entry = Posix(Path.Combine(entryDirectory, island.Name + ".entry.ts"));
            input.AppendLine($"  {Literal(island.Name)}: '{entry}',");
        }

        // A plugin is imported only when an island actually uses that runtime, so a Lit-only app is
        // never asked to install @vitejs/plugin-react to build — and a Vue-only app is not either.
        // Ordered by the table rather than by the islands, so the config is byte-identical whatever
        // order the components were discovered in: this file is a bundler input compared against what
        // is already on disk, and rewriting it restarts the dev server's dependency graph.
        var present = ExternalRuntime.All
            .Where(r => islands.Any(i => string.Equals(i.Runtime, r.Key, StringComparison.Ordinal)))
            .ToList();

        Refuse(islands, present);

        var used = present.Where(r => r.PluginImport is not null).ToList();

        var pluginImports = string.Concat(used.Select(r => $"import {r.PluginImport}\n"));
        var pluginCalls = string.Concat(used.Select(r => $"{PluginCall(r, present, islands, tsConfigPath)}, "));

        return $$"""
            {{Header}}
            import { defineConfig } from 'vite'
            import { writeFileSync, mkdirSync } from 'node:fs'
            import { dirname } from 'node:path'
            {{pluginImports}}
            const input = {
            {{input.ToString().TrimEnd()}}
            }

            // Writes the table rask-external.js fetches: island name -> the hashed chunk that mounts it.
            // Taken from the bundle rollup actually emitted rather than predicted from the config, so a
            // renamed or re-hashed chunk cannot drift out of the manifest that points at it.
            function raskIslandManifest() {
              return {
                name: 'rask-external-manifest',
                writeBundle(_options, bundle) {
                  const map = {}
                  for (const [file, chunk] of Object.entries(bundle)) {
                    if (chunk.type === 'chunk' && chunk.isEntry) {
                      map[chunk.name] = {{Literal(publicBase)}} + file
                    }
                  }
                  const path = {{Literal(manifestPath.Replace("\\", "/"))}}
                  mkdirSync(dirname(path), { recursive: true })
                  writeFileSync(path, JSON.stringify(map, null, 2))
                },
              }
            }

            export default defineConfig({
              plugins: [{{pluginCalls}}raskIslandManifest()],
              build: {
                outDir: {{Literal(Posix(outputDirectory))}},
                emptyOutDir: true,
                rollupOptions: {
                  input,
                  // Without this the chunk has NO exports at all. Vite treats an application entry as a
                  // side-effect script and defaults preserveEntrySignatures to false, so Rollup drops the
                  // `export default` the entry module was generated to carry — and the client runtime
                  // then reports a chunk that "does not default-export an adapter", which is true, and
                  // says nothing about why. The bundle builds, ships, loads, and mounts nothing.
                  preserveEntrySignatures: 'strict',
                  output: { entryFileNames: 'assets/[name]-[hash].js', chunkFileNames: 'assets/[name]-[hash].js' },
                },
              },
            })

            """;
    }

    /// <summary>
    ///     One plugin's call expression, scoped to its own islands when another runtime competes for
    ///     the same files.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Scoped by DIRECTORY, never by file, and that distinction was measured rather than
    ///         reasoned about. A file-level <c>include</c> naming the island itself transforms the
    ///         island correctly and leaves every module it IMPORTS to whichever plugin claims the rest
    ///         of the tree: a Solid island importing a <c>Row.tsx</c> beside it built green, emitted a
    ///         shared <c>jsxRuntime</c> chunk, and shipped a Preact vnode into Solid's renderer. A
    ///         directory scope covers the helpers, because that is where they live.
    ///     </para>
    ///     <para>
    ///         Only applied when it is needed. With one JSX runtime in the project there is nothing to
    ///         disambiguate, and an unscoped plugin is both simpler to read and safe — it sees files
    ///         no other plugin wants.
    ///     </para>
    /// </remarks>
    private static string PluginCall(
        ExternalRuntime runtime,
        IReadOnlyList<ExternalRuntime> present,
        IReadOnlyList<ExternalEntry> islands,
        string? tsConfigPath)
    {
        var options = new List<string>();

        if (runtime.PluginOptions is { Length: > 0 } baseline)
        {
            options.Add(baseline);
        }

        // A tsconfig Rask writes, never the app's own.
        //
        // The plugin looks for tsconfig.app.json and only WARNS when it is missing, then builds anyway
        // with the compiler configured by nothing — so it does need to be told. But pointing it at the
        // app's tsconfig.json breaks the build outright: that file carries "noEmit": true, which is
        // correct for a type-check and fatal here, because ngtsc then emits nothing and rolldown
        // reports `"default" is not exported by <island>.ts` for every .ts island in the project —
        // naming files that plainly export one. Measured: bare and include-scoped both build; the
        // app's tsconfig fails; a generated one without noEmit builds AND silences the warning.
        if (ReferenceEquals(runtime, ExternalRuntime.Angular) && tsConfigPath is { Length: > 0 })
        {
            options.Add($"tsconfig: {Literal(Posix(tsConfigPath))}");
        }

        if (present.Any(runtime.SharesExtensionWith))
        {
            var globs = Directories(islands, runtime)
                .Select(d => Literal(d + "/**/*" + Extensions(runtime)))
                .ToList();

            if (globs.Count > 0)
            {
                options.Add("include: [" + string.Join(", ", globs) + "]");
            }
        }

        return options.Count == 0
            ? $"{runtime.PluginFactory}()"
            : $"{runtime.PluginFactory}({{ {string.Join(", ", options)} }})";
    }

    /// <summary>
    ///     The tsconfig the Angular plugin compiles against, or null when the project has no Angular
    ///     island.
    /// </summary>
    /// <remarks>
    ///     Written rather than borrowed. The app's own tsconfig is the obvious candidate and the wrong
    ///     one: it carries <c>"noEmit": true</c> — correct for a type-check, fatal for a compiler whose
    ///     output is the bundle — and the failure names neither Angular nor noEmit, only a missing
    ///     default export in a file that has one. This config exists to emit, so it says nothing about
    ///     noEmit at all.
    /// </remarks>
    public static string? AngularTsConfig(IReadOnlyList<ExternalEntry> islands, string directory)
    {
        var files = islands
            .Where(i => string.Equals(i.Runtime, ExternalRuntime.Angular.Key, StringComparison.Ordinal))
            .Select(i => Posix(i.Source))
            .OrderBy(f => f, StringComparer.Ordinal)
            .ToList();

        if (files.Count == 0)
        {
            return null;
        }

        var json = new StringBuilder();
        json.AppendLine("{");
        json.AppendLine("  // <auto-generated/> Rask writes this for @analogjs/vite-plugin-angular.");
        json.AppendLine("  // Deliberately NOT the app's tsconfig. That one suppresses emit for its");
        json.AppendLine("  // type-check, which leaves ngtsc producing nothing and every .ts island in");
        json.AppendLine("  // the project without a default export. This config exists to emit.");
        json.AppendLine("  \"compilerOptions\": {");
        json.AppendLine("    \"target\": \"es2022\",");
        json.AppendLine("    \"module\": \"esnext\",");
        json.AppendLine("    \"moduleResolution\": \"bundler\",");
        json.AppendLine("    \"strict\": true,");
        json.AppendLine("    \"skipLibCheck\": true,");
        // Angular's decorators are the TypeScript 4 form; Lit 3's standard decorators need this off,
        // which is why this config covers the Angular islands only.
        json.AppendLine("    \"experimentalDecorators\": true,");
        json.AppendLine("    \"useDefineForClassFields\": false,");
        json.AppendLine("    \"paths\": {");
        json.Append("      \"@rask/*\": [\"").Append(Posix(directory)).AppendLine("/types/*\"]");
        json.AppendLine("    }");
        json.AppendLine("  },");
        json.AppendLine("  \"files\": [");

        for (var i = 0; i < files.Count; i++)
        {
            json.Append("    \"").Append(files[i]).Append('"')
                .AppendLine(i == files.Count - 1 ? string.Empty : ",");
        }

        json.AppendLine("  ]");
        json.AppendLine("}");

        return json.ToString();
    }

    /// <summary>The distinct directories a runtime's islands live in, sorted so the config is stable.</summary>
    private static IEnumerable<string> Directories(IReadOnlyList<ExternalEntry> islands, ExternalRuntime runtime) =>
        islands
            .Where(i => string.Equals(i.Runtime, runtime.Key, StringComparison.Ordinal))
            .Select(i => Posix(Path.GetDirectoryName(i.Source) ?? string.Empty))
            .Where(d => d.Length > 0)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(d => d, StringComparer.Ordinal);

    /// <summary>A runtime's extensions as one brace expansion, e.g. <c>.{jsx,tsx}</c>.</summary>
    private static string Extensions(ExternalRuntime runtime)
    {
        var bare = runtime.Extensions
            .Select(e => e.TrimStart('.'))
            .OrderBy(e => e, StringComparer.Ordinal)
            .ToList();

        return bare.Count == 1 ? "." + bare[0] : ".{" + string.Join(",", bare) + "}";
    }

    /// <summary>
    ///     Refuses the island combinations no generated config could build correctly.
    /// </summary>
    /// <remarks>
    ///     Both of these used to be possible to express and impossible to notice. Named here, at the
    ///     point the config would have been written, so the message can name the islands rather than
    ///     leaving npm or the browser to describe the symptom.
    /// </remarks>
    /// <exception cref="InvalidOperationException">The combination cannot be built.</exception>
    private static void Refuse(IReadOnlyList<ExternalEntry> islands, IReadOnlyList<ExternalRuntime> present)
    {
        // React and Preact cannot be INSTALLED together, let alone configured: @vitejs/plugin-react
        // resolves Babel 8 and @preact/preset-vite pins a @babel/core@"7.x" peer. Left to npm, the
        // failure is an ERESOLVE tree that names four Babel packages and neither island.
        if (present.Contains(ExternalRuntime.React) && present.Contains(ExternalRuntime.Preact))
        {
            throw new InvalidOperationException(
                "Rask islands: this project has both React and Preact islands ("
                + Naming(islands, ExternalRuntime.React) + " and " + Naming(islands, ExternalRuntime.Preact)
                + "), and their Vite plugins cannot be installed side by side — @vitejs/plugin-react "
                + "resolves Babel 8 while @preact/preset-vite pins @babel/core 7. Pick one for the "
                + "project. A Preact island can also be rendered by ReactComponent if the app aliases "
                + "react to preact/compat.");
        }

        // Two runtimes that claim the same extension CAN share a project, but not a directory tree:
        // each plugin is confined to the directories its own islands live in, so overlapping trees
        // leave both claiming the same files. Whichever loses compiles the other's island — and every
        // helper beside it — with the wrong transform, which builds, ships, and mounts nothing.
        //
        // Ancestry counts, not just equality. A React island in Features/Islands and a Solid one in
        // Features/Islands/Solid look like different directories and are not: React's scope is
        // 'Features/Islands/**', which contains Solid's islands whole.
        foreach (var a in present)
        {
            foreach (var b in present)
            {
                if (string.CompareOrdinal(a.Key, b.Key) >= 0 || !a.SharesExtensionWith(b))
                {
                    continue;
                }

                foreach (var left in Directories(islands, a))
                {
                    foreach (var right in Directories(islands, b))
                    {
                        if (!Overlaps(left, right))
                        {
                            continue;
                        }

                        throw new InvalidOperationException(
                            $"Rask islands: the {a.Key} island(s) in '{left}' ({Naming(islands, a, left)}) and "
                            + $"the {b.Key} island(s) in '{right}' ({Naming(islands, b, right)}) share a "
                            + "directory tree, and both runtimes compile "
                            + string.Join("/", a.Extensions.Where(e => b.Extensions.Contains(e, StringComparer.Ordinal)))
                            + ". Each plugin is scoped to the directories its own islands live in, so "
                            + "overlapping trees leave one of them compiling the other's island — and the "
                            + "helper modules beside it — with the wrong transform. That builds, ships, and "
                            + "then mounts nothing. Give each runtime a folder of its own, and do not nest "
                            + "one inside the other.");
                    }
                }
            }
        }
    }

    /// <summary>Whether two island directories are the same, or one contains the other.</summary>
    private static bool Overlaps(string left, string right) =>
        string.Equals(left, right, StringComparison.Ordinal)
        || left.StartsWith(right + "/", StringComparison.Ordinal)
        || right.StartsWith(left + "/", StringComparison.Ordinal);

    /// <summary>The islands of one runtime, named for an error message. Optionally one directory's.</summary>
    private static string Naming(
        IReadOnlyList<ExternalEntry> islands, ExternalRuntime runtime, string? directory = null) =>
        string.Join(
            ", ",
            islands
                .Where(i => string.Equals(i.Runtime, runtime.Key, StringComparison.Ordinal))
                .Where(i => directory is null
                            || string.Equals(
                                Posix(Path.GetDirectoryName(i.Source) ?? string.Empty),
                                directory,
                                StringComparison.Ordinal))
                .Select(i => i.Name)
                .OrderBy(n => n, StringComparer.Ordinal));

    /// <summary>
    ///     Forward slashes, always.
    /// </summary>
    /// <remarks>
    ///     A Windows path inside a JavaScript string literal is a string full of escape sequences:
    ///     <c>C:\app\src</c> reads <c>\a</c> and <c>\s</c>, and the import silently resolves somewhere
    ///     else. Node and Vite both accept forward slashes on Windows, so normalising is the fix rather
    ///     than escaping.
    /// </remarks>
    private static string Posix(string path) => path.Replace("\\", "/");

    /// <summary>
    ///     A path as a module specifier the bundler will treat as a path.
    /// </summary>
    /// <remarks>
    ///     A relative path with no leading <c>./</c> is not a relative specifier — it is a BARE one,
    ///     which every bundler resolves against <c>node_modules</c>. So
    ///     <c>obj/Debug/net10.0/rask-external/rask/react</c> fails looking for a package called
    ///     <c>obj</c>, naming something nobody wrote. The targets pass absolute paths; this makes the
    ///     rule hold anyway rather than depending on a caller getting it right.
    /// </remarks>
    private static string Specifier(string path)
    {
        var posix = Posix(path);
        if (posix.StartsWith("/", StringComparison.Ordinal)
            || posix.StartsWith("./", StringComparison.Ordinal)
            || posix.StartsWith("../", StringComparison.Ordinal)
            || (posix.Length > 1 && posix[1] == ':'))
        {
            return posix;
        }

        return "./" + posix;
    }

    /// <summary>A JavaScript string literal, quoted and escaped.</summary>
    private static string Literal(string value)
    {
        var sb = new StringBuilder("'");
        foreach (var c in value)
        {
            switch (c)
            {
                case '\'':
                case '\\':
                    sb.Append('\\').Append(c);
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                default:
                    if (c < ' ')
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        return sb.Append('\'').ToString();
    }

    /// <summary>
    ///     Writes <paramref name="content" /> only if it would change.
    /// </summary>
    /// <remarks>
    ///     Load-bearing rather than an optimisation, exactly as in Rask.Spa.Tasks: these files are
    ///     bundler inputs, so rewriting an identical one on every build restarts the dev server's
    ///     dependency graph and can loop a watch build against itself.
    /// </remarks>
    public static bool WriteIfDifferent(string path, string content)
    {
        if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
        {
            return false;
        }

        var directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(path, content);
        return true;
    }
}
