using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace Rask.External.Tasks;

/// <summary>One island, as the bundler needs to see it.</summary>
internal sealed class ExternalEntry
{
    /// <summary>The island's name — the key the browser resolves a module by.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Absolute path to the front-end file sitting beside the C# class.</summary>
    public string Source { get; set; } = string.Empty;

    /// <summary>Which adapter wraps it — a key from <see cref="ExternalRuntime.All" />.</summary>
    public string Runtime { get; set; } = ExternalRuntime.React.Key;
}

/// <summary>
///     Writes the bundler's inputs: one entry module per island, and the config that builds them.
/// </summary>
/// <remarks>
///     <para>
///         The generated entry is what keeps a component ordinary. It imports the author's file and
///         wraps it with its runtime's adapter, so <c>Chart.tsx</c> stays a plain React component with
///         no Rask import in it and no knowledge that it is an island at all.
///     </para>
///     <para>
///         Plain string generation in C# rather than MSBuild, for the same reason the CQRS TypeScript
///         is: this is testable, and an MSBuild property carrying a JavaScript object literal is not.
///     </para>
/// </remarks>
internal static class ExternalBuildPlan
{
    private const string Header =
        "// <auto-generated> by Rask. Regenerated on every build; edits are lost. </auto-generated>";

    /// <summary>The entry module that pairs an island's component with its adapter.</summary>
    /// <remarks>
    ///     One shape for every runtime, which is what the table buys: bind the author's default export
    ///     to a name, wrap it with that runtime's factory, re-export. The runtimes differ only in what
    ///     the default export IS — a component everywhere else, a registered tag NAME for Lit, because
    ///     a custom element registers its own tag and nothing about the file reveals it. Importing the
    ///     module is also what runs that registration side effect.
    /// </remarks>
    /// <exception cref="InvalidOperationException">The island names a runtime nothing declares.</exception>
    public static string EntryModule(ExternalEntry island, string adapterDirectory)
    {
        var runtime = ExternalRuntime.Find(island.Runtime)
                      ?? throw new InvalidOperationException(
                          $"Island '{island.Name}' names the runtime '{island.Runtime}', which Rask has no adapter "
                          + $"for. Known runtimes: {ExternalRuntime.KeyList}.");

        var source = Specifier(island.Source);
        var adapter = Specifier(Path.Combine(adapterDirectory, runtime.AdapterModule));

        return $$"""
            {{Header}}
            import {{runtime.ImportName}} from '{{source}}'
            import { {{runtime.AdapterFactory}} } from '{{adapter}}'

            export default {{runtime.AdapterFactory}}({{runtime.ImportName}})

            """;
    }

    /// <summary>
    ///     The Vite config that builds one chunk per island and writes the runtime's manifest.
    /// </summary>
    /// <param name="islands">The islands, already paired with their entry files.</param>
    /// <param name="entryDirectory">Where the generated entry modules live.</param>
    /// <param name="outputDirectory">Where the built chunks land.</param>
    /// <param name="manifestPath">The manifest file <c>rask-external.js</c> fetches.</param>
    /// <param name="publicBase">The URL prefix the built files are served from.</param>
    public static string ViteConfig(
        IReadOnlyList<ExternalEntry> islands,
        string entryDirectory,
        string outputDirectory,
        string manifestPath,
        string publicBase)
    {
        var input = new StringBuilder();
        foreach (var island in islands)
        {
            var entry = Posix(Path.Combine(entryDirectory, island.Name + ".entry.ts"));
            input.AppendLine($"  {Literal(island.Name)}: '{entry}',");
        }

        // A plugin is imported only when an island actually uses that runtime, so a Lit-only app is
        // never asked to install @vitejs/plugin-react to build — and a Vue-only app is not either.
        // Ordered by the table rather than by the islands, so the config is byte-identical whatever
        // order the components were discovered in: this file is a bundler input compared against what
        // is already on disk, and rewriting it restarts the dev server's dependency graph.
        var used = ExternalRuntime.All
            .Where(r => r.PluginImport is not null)
            .Where(r => islands.Any(i => string.Equals(i.Runtime, r.Key, StringComparison.Ordinal)))
            .ToList();

        var pluginImports = string.Concat(used.Select(r => $"import {r.PluginImport}\n"));
        var pluginCalls = string.Concat(used.Select(r => $"{r.PluginCall}, "));

        return $$"""
            {{Header}}
            import { defineConfig } from 'vite'
            import { writeFileSync, mkdirSync } from 'node:fs'
            import { dirname } from 'node:path'
            {{pluginImports}}
            const input = {
            {{input.ToString().TrimEnd()}}
            }

            // Writes the table rask-external.js fetches: island name -> the hashed chunk that mounts it.
            // Taken from the bundle rollup actually emitted rather than predicted from the config, so a
            // renamed or re-hashed chunk cannot drift out of the manifest that points at it.
            function raskIslandManifest() {
              return {
                name: 'rask-external-manifest',
                writeBundle(_options, bundle) {
                  const map = {}
                  for (const [file, chunk] of Object.entries(bundle)) {
                    if (chunk.type === 'chunk' && chunk.isEntry) {
                      map[chunk.name] = {{Literal(publicBase)}} + file
                    }
                  }
                  const path = {{Literal(manifestPath.Replace("\\", "/"))}}
                  mkdirSync(dirname(path), { recursive: true })
                  writeFileSync(path, JSON.stringify(map, null, 2))
                },
              }
            }

            export default defineConfig({
              plugins: [{{pluginCalls}}raskIslandManifest()],
              build: {
                outDir: {{Literal(Posix(outputDirectory))}},
                emptyOutDir: true,
                rollupOptions: {
                  input,
                  // Without this the chunk has NO exports at all. Vite treats an application entry as a
                  // side-effect script and defaults preserveEntrySignatures to false, so Rollup drops the
                  // `export default` the entry module was generated to carry — and the client runtime
                  // then reports a chunk that "does not default-export an adapter", which is true, and
                  // says nothing about why. The bundle builds, ships, loads, and mounts nothing.
                  preserveEntrySignatures: 'strict',
                  output: { entryFileNames: 'assets/[name]-[hash].js', chunkFileNames: 'assets/[name]-[hash].js' },
                },
              },
            })

            """;
    }

    /// <summary>
    ///     Forward slashes, always.
    /// </summary>
    /// <remarks>
    ///     A Windows path inside a JavaScript string literal is a string full of escape sequences:
    ///     <c>C:\app\src</c> reads <c>\a</c> and <c>\s</c>, and the import silently resolves somewhere
    ///     else. Node and Vite both accept forward slashes on Windows, so normalising is the fix rather
    ///     than escaping.
    /// </remarks>
    private static string Posix(string path) => path.Replace("\\", "/");

    /// <summary>
    ///     A path as a module specifier the bundler will treat as a path.
    /// </summary>
    /// <remarks>
    ///     A relative path with no leading <c>./</c> is not a relative specifier — it is a BARE one,
    ///     which every bundler resolves against <c>node_modules</c>. So
    ///     <c>obj/Debug/net10.0/rask-external/rask/react</c> fails looking for a package called
    ///     <c>obj</c>, naming something nobody wrote. The targets pass absolute paths; this makes the
    ///     rule hold anyway rather than depending on a caller getting it right.
    /// </remarks>
    private static string Specifier(string path)
    {
        var posix = Posix(path);
        if (posix.StartsWith("/", StringComparison.Ordinal)
            || posix.StartsWith("./", StringComparison.Ordinal)
            || posix.StartsWith("../", StringComparison.Ordinal)
            || (posix.Length > 1 && posix[1] == ':'))
        {
            return posix;
        }

        return "./" + posix;
    }

    /// <summary>A JavaScript string literal, quoted and escaped.</summary>
    private static string Literal(string value)
    {
        var sb = new StringBuilder("'");
        foreach (var c in value)
        {
            switch (c)
            {
                case '\'':
                case '\\':
                    sb.Append('\\').Append(c);
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                default:
                    if (c < ' ')
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        return sb.Append('\'').ToString();
    }

    /// <summary>
    ///     Writes <paramref name="content" /> only if it would change.
    /// </summary>
    /// <remarks>
    ///     Load-bearing rather than an optimisation, exactly as in Rask.Spa.Tasks: these files are
    ///     bundler inputs, so rewriting an identical one on every build restarts the dev server's
    ///     dependency graph and can loop a watch build against itself.
    /// </remarks>
    public static bool WriteIfDifferent(string path, string content)
    {
        if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
        {
            return false;
        }

        var directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(path, content);
        return true;
    }
}
